### ISSUE TITLE
Replace/deprecate the outdated spec repo with an in-repo schema

### ISSUE THREAD

**Issue by cybtachyon** [pattern-lab/patternlab-node#1009]
As per the previous discussion in https://github.com/pattern-lab/patternlab-node/pull/1000

> Did we already link in the doc/spec updates PR for this or do I need to go make one to https://github.com/pattern-lab/the-spec/ to update the spec & docs?
>
>@cybtachyon Spec? What spec? (Seriously, all I see is rough outline that hasn’t gotten updated in a long time).
>
>IMHO, what we REALLY need is a schema that lives in the same repo as the rest of PL’s code (not a separate repo that’s guaranteed to go out of date). That’s the sort of thing that can get tested against, have documentation generated from it, and can get enforced.

**Comment by sghoweri** [comment]
Thanks @cybtachyon!

**Comment by cybtachyon** [comment]
@sghoweri Do we have any examples of another working repo for what this would look like?

**Comment by cybtachyon** [comment]
Please upvote the original comment with a 👍 if this issue is important to you.

This issue is in our internal backlog.
