### ISSUE TITLE
Support Pattern Search

### ISSUE THREAD

**Issue by getsetbro** [pattern-lab/patternlab-node#101]
http://getsetbro.com/pl-nodeV8/public/

Page Follow and Auto Reload do not seem to do anything in the settings menu.

**Comment by bmuenzenmeyer** [comment]
To be honest, I don't recall specifically investigating support for search during the port, which has been in dev for over a year and morphed as PL PHP has a bit. 

I will investigate this as part of v1.0.0 (a contribution is welcome too :smile: ). I will be renaming this issue to "Support Pattern Search."

Page follow was investigated in https://github.com/pattern-lab/patternlab-node/pull/86 but navigation did not work as expected. This is something I'd like to get working at some point. I've opened an issue for this https://github.com/pattern-lab/patternlab-node/issues/103. 

Live reload works oob with the grunt tasks when launched as `grunt serve`. This option should just be removed from PL Node as it doesn't really make sense. I've opened an issue for this: https://github.com/pattern-lab/patternlab-node/issues/102

**Comment by bmuenzenmeyer** [comment]
This is currently turned off by default in the navigation, but we should just get it working :)

**Comment by bmuenzenmeyer** [comment]
Hey @getsetbro this was just pushed to dev branch. If you could upgrade and verify functionality I would appreciate it. Otherwise I'll hammer on it a bit more too :)

**Comment by getsetbro** [comment]
Boom. Roasted.

**Comment by christophrumpel** [comment]
Is the search functionality already in the current release? Can't find any information about it?

**Comment by bmuenzenmeyer** [comment]
Hi @christophrumpel 

you should see it on the current release on the top right of the style guide

![image](https://cloud.githubusercontent.com/assets/298435/10456622/e502f948-7187-11e5-8124-2248c88d3937.png)

**Comment by christophrumpel** [comment]
Ah I see. Thanks. I thought there might be some info in the documentation on how it works or something similar. But I will try it now myself. Thx!
