### ISSUE TITLE
Remove Pattern Type, Subtype, and Pattern Order mechanic using ##- in the filename

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1028]
As documented in our [feature review](https://github.com/orgs/pattern-lab/projects/3#card-23742746) I am planning to remove the `00-atoms/` means of ordering in favor of markdown.

* Metadata should not be baked into file names - it mucks with git history
* It complicates the code immensely, leading to issues like #890

When this issue is finished, specify `order` within the optional markdown frontmatter to specify the order in which PL generates the UI.

**source/_patterns/atoms.md**
``` yaml
order: 1
---
# Atoms are small
```

**_patterns/atoms/buttons.md**
``` yaml
order: 1
---
# Buttons are the next big thing.
```

**_patterns/atoms/buttons/calltoaction.md**
``` yaml
order: 3
---
# Try a click today
```

Related: https://github.com/pattern-lab/patternlab-node/issues/415

**Comment by bradfrost** [comment]
Yep, this is a good move!

**Comment by sghoweri** [comment]
@bmuenzenmeyer is markdown going to be the only way this Pattern-specific data gets lifted or would other data formats we parse like JSON or Yaml (... or even Javascript) also going to be supported?

**Comment by bmuenzenmeyer** [comment]
pattern-specific data works with JSON as always. I feel as if someone had tried or did succeed in also supporting Yaml. We have code in core that can load both but I'd have to check. 

the `order` metadata is pattern documentation: https://patternlab.io/docs/documenting-patterns/

**Comment by sghoweri** [comment]
@bmuenzenmeyer another quick question or two relating to this one: 

1. Is the plan to temporarily disable this feature (to get things in a more stable / predictable spot) but potentially bringing things back in the future (perhaps with #1031?) or is the idea to retire this particular feature indefinitely?

2. Isn't this a major breaking change...? If so, is this a major breaking change for "v3.0" or do we need to bump our semver across the board to `v4.x` to play it safe?

CC @lwpinion

**Comment by sghoweri** [comment]
@bmuenzenmeyer just read the feature roadmap and yup, file system hacks do suck. 👍
