### ISSUE TITLE
[uikit-workshop] View All Drawers Do Not Open

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1029]
[This comment](https://github.com/pattern-lab/patternlab-node/pull/960#issuecomment-433780121) is still relevant - opening an issue for that

_Originally posted by @bmuenzenmeyer in https://github.com/pattern-lab/patternlab-node/pull/960#issuecomment-509696558_

![image](https://user-images.githubusercontent.com/298435/60903197-808a6d00-a236-11e9-9f67-e87e8ceabb09.png)

**Comment by sghoweri** [comment]
@bmuenzenmeyer this is the same issue as https://github.com/pattern-lab/patternlab-node/issues/1057, yes?

**Comment by bmuenzenmeyer** [comment]
looks like it to me

**Comment by sghoweri** [comment]
Same with this one -- closing out since https://github.com/pattern-lab/patternlab-node/pull/1094 should have addressed this!!
