### ISSUE TITLE
Reinvestigate page-follow

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#103]
Resurrect https://github.com/pattern-lab/patternlab-node/pull/86 and get this working some day

**Comment by dmolsen** [comment]
[BrowserSync](http://www.browsersync.io)?

**Comment by bmuenzenmeyer** [comment]
That's what I integrated for a moment but the iframe nab messaging was not
keeping up. I think it's possible but I didn't want it holding up a minor
rev. I should put back into a branch for experimentation.

**Comment by ivanmayes** [comment]
Just FYI, browsersync hit 2.0 and now has a seperate UI for syncing devices, getting error reporting in one place, etc.  I've used it with a fork of patternlab and can sync devices to a page via the UI History Panel, but the Patternlab nav still doesn't trigger it.  Will take some time at some point to find the event its listening for and maybe we can just trigger that event when the ui changes.

**Comment by bmuenzenmeyer** [comment]
That's exactly where I got and then stopped. I'm hoping the fix is simple,
only subtle. Thanks for the info on the new 2.0
