### ISSUE TITLE
Change lerna to fixed version mode

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1040]
Related to https://github.com/pattern-lab/patternlab-node/issues/1039

for simplicity's sake we should consider abandoning lerna independent mode and affixing our versioning of the entire ecosystem at a time. so core@4 works with cli@4 works with @pattern-lab/plugin-foo@4 etc.

i like independent versioning because i believe in semver but it's clearly causing confusion

**Comment by sghoweri** [comment]
100% agree with this -- we made the exact same move early on with https://github.com/bolt-design-system/bolt (switching from independent to fixed versioning) and it's helped other devs a TON with knowing if X version of a component or dependency has been tested and works with Y version of some other monorepo package. 👍

**Comment by bmuenzenmeyer** [comment]
having done this already, would you agree the general steps for this change be:

1. manually change all versions to say 3.`SOMETHING`
2. change the lerna config option
3. release as normal
