### ISSUE TITLE
Menu & View All list breaks if pattern name and folder name are identical

### ISSUE THREAD

**Issue by coreylafferty** [pattern-lab/patternlab-node#1049]
I am using Pattern Lab Node `v3.0.3` on `Windows`, with Node `v10.15.1`, using the `Twig` Edition.

##### Expected Behavior
All patterns show on the View All page and are properly nested in their parent item in the navigation.

##### Actual Behavior
If a filename matches that of the parent folder, the resulting menu shows the item outside the parent folder.  The same pattern does NOT show up on the View All page.

##### Steps to Reproduce

1. Start up a fresh copy of Pattern Lab Node, using the Twig engine and Twig starter kit.
2. Look at the Atoms / Buttons pattern in the menu and file system as an example. 
3. Notice that the Buttons item does not show in a Buttons folder (despite the file being 00-atoms/06-buttons/00-buttons.twig) and that Buttons does not show in either the main View All list or the Atoms category View All list.  

 
![image](https://user-images.githubusercontent.com/1557952/64197140-482c9700-ce53-11e9-9ec4-4f0ec1bd5314.png)

 
4.  As a clearer test, create the following four files to see how the menu handles similar patterns when the parent folder does and does not match one of them:

**Folder name (cats) does NOT match a pattern filename in it since it is plural**
/_patterns/01-molecules/cats/cat.twig
/_patterns/01-molecules/cats/cat-special.twig

**Folder name (dog) does match a pattern filename in it**
/_patterns/01-molecules/dog/dog.twig
/_patterns/01-molecules/dog/dog-special.twig

![image](https://user-images.githubusercontent.com/1557952/64197036-1adfe900-ce53-11e9-8012-2da45c5b998c.png)

The two 'cat' files behave as expected, properly nested in a 'Cats' folder.  The dog items do not, with the 'dog' folder being created without a toggle to open it and 'dog special' not showing at all -- the other pattern shows outside the dog folder but does not show in the View All list (similar to the buttons example above).

**Comment by sghoweri** [comment]
CC @bmuenzenmeyer 

I’d definitely want to double check the Nav component to make sure there isn’t a logic error however this could potentially be a core PL Node issue as well (I can’t recall seeing this issue using the new UIKit with PL PHP...) 🤔

**Comment by bmuenzenmeyer** [comment]
i wouldn't be surprised if this was a core issue

**Comment by coreylafferty** [comment]
This issue was present before the recent UI updates and does not affect the PHP version of PL, so I assume it's an issue in PL Node core.  We've dug into it a bit, but so far haven't had much luck tracking down a fix.  It's particularly problematic with our theme because all of our patterns are organized according to the BEM class names so most of our folder names match the file names...  e.g., _/components/button/button.twig_, _components/button/button--small.twig_, etc.

**Comment by kryp71c** [comment]
The identical folder name issue stems from changes made to core in this [commit](https://github.com/pattern-lab/patternlab-node/commit/b30ed5c30b9a63eeffeae6b9a527ccc07ac8fecb#diff-811dc08dbb9437f8b472a21f0c9bd66e)

To test: comment out [this line in objcet-factory.js](https://github.com/pattern-lab/patternlab-node/blob/d1344d396b180a02c8a3aebecd88adfc08679ad3/packages/core/src/lib/object_factory.js#L220)

The menu structure should now be intact. However, you'll find that the parent links are broken. [Reverting object-factory.js to the state before the above commit](https://github.com/pattern-lab/patternlab-node/blob/4d9c243624cb15fe929865c4793dc9078e55503b/packages/core/src/lib/object_factory.js) fixes the menu issues.

**Comment by kmonahan** [comment]
@coreylafferty and I have been looking into this one, and as @kryp71c notes above, this looks to be related to the work done in PR #992. I've submitted a PR that limits the special handling of patterns that match their directory name to patterns that follow the structure `patternType/patternSubType/pattern/pattern.*`, which I think should work for both our use case and the one in the original PR. From comparing against a PHP version project with similar folder structures, it looks like that's how that version works as well--folders nested one level deep are treated as pattern subtype groupings and folders two levels deep are treated as patterns.

**Comment by zhawkins** [comment]
I've also run into this issue as well (with buttons too oddly enough).

![Buttons nested under the button directory]https://user-images.githubusercontent.com/2671663/64715376-56e7ff00-d48e-11e9-9ec6-1c0f415af787.png)

Can confirm https://github.com/pattern-lab/patternlab-node/pull/1054 fixes the issue. 🎉

**Comment by coreylafferty** [comment]
@bmuenzenmeyer see https://github.com/pattern-lab/patternlab-node/pull/1054.  Thanks!
