### ISSUE TITLE
'View All' for each subsection in menus

### ISSUE THREAD

**Issue by ivanmayes** [pattern-lab/patternlab-node#105]
PHP version has 'View All' links and pages for each subsection of the menu, very helpful for certain groupings as your building.

**Comment by walmokrani** [comment]
I'am working on it . I have generated the links and the pages successfully. I have only one problem, everything works well when I tap the url to navigate to each view-all pages but it doesn't works when I do it via the menu links. I have not been able to fix the problem. Can you please give it a try ? https://github.com/walmokrani/patternlab-node/tree/dev

**Comment by bmuenzenmeyer** [comment]
Hey @walmokrani 

Thanks so much for throwing your hat in the ring and helping out - I will take a look at this tonight and hopefully we can get to the bottom of it.

**Comment by walmokrani** [comment]
Hey @bmuenzenmeyer , I have finally made it, it works perfectly, I have submitted a PR.

**Comment by ivanmayes** [comment]
Thanks @walmokrani!

**Comment by walmokrani** [comment]
you are welcome @ivanmayes

**Comment by bmuenzenmeyer** [comment]
For some reason this did not close when dev went to master
