### ISSUE TITLE
Code panel expanding bug

### ISSUE THREAD

**Issue by iris-i** [pattern-lab/patternlab-node#1057]
I am using Pattern Lab Node `v3.0.3` on `Mac`, with Node `vX.X.X`, using a `Vanilla` Edition.

##### Expected Behavior
When you click the dropdown button to open/close the code info panel for any pattern, the info pane should get toggled.

##### Actual Behavior
I noticed that for each pattern I can only click the dropdown arrow to open and close the info pane (with the pattern description and markup) once. If I try to toggle it multiple times, it does not open until I toggle the info pane in a different component.
Also, if I stop the --serve script and re-run it, I can no longer open the info pane for any pattern.

##### Steps to Reproduce
1. Install with demo content and start up the server.
2. Click the dropdown arrow to view code info for any pattern multiple times. It will open and close just once.
3. Click on any other pattern's info dropdown button and then click on the first pattern you tested. It will open & close just once.

From conversations in gitter, (thanks @sghoweri!) this is a known issue and is part of the ongoing UIKit refactoring process.

**Comment by sghoweri** [comment]
Definitely a known bug and definitely annoying. Let’s see if we can get this bug squashed for the next UIKit release! 🤞

**Comment by sghoweri** [comment]
Closing this out - the updates that went out with https://github.com/pattern-lab/patternlab-node/pull/1094 should have taken care of this bug!
