### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by simonseddon** [pattern-lab/patternlab-node#1063]
Hi there. I've been very keen to work with Pattern Lab and each time I've tried over the years I've hit hurdles which have led to wasted hours and just dropping the idea altogether, in favour of just making my own simplistic version. I've added this note as I think many front-end developers like myself have had a similar experience.

How about making a start-finish documentation which isn't so on the fence about language, build-process, starter kit, version of PL, etc.. whichever flavour of PL the team thinks is best for most people? So far I've got as far as installing PL via the CLI but been completely stumped as to which direction to take and which version (if any) of the documentation applies to it. Soon thereafter I start uttering such things as "over-engineered" which I know isn't fair but shows my frustration.

**Comment by bradfrost** [comment]
Hey @simonseddon thanks for the feedback. Pattern Lab has come a long way over the last 6 years, and with it comes a lot of baggage. Updating the documentation is a high priority for me over the coming months.

**Comment by simonseddon** [comment]
Thanks @bradfrost I'll keep my eyes peeled and totally appreciate everything you and the team have put in to this! Once I've grokked it I'd love to make a start-finish video series of the entire process, for others with similar hurdles. Next week I'm starting front-end dev on a large WP multisite (60+ hotel properties) using shared UI with slight variations depending on sub-brand. PL seems like a perfect fit for this, with the Twig and variant features, so I'll have one more stab at it over the weekend :)

**Comment by ringods** [comment]
@bradfrost @sghoweri @bmuenzenmeyer isn't it time to replace the outdated site on the main domain with the preview which is built and visible on Netlify? Documentation is always lagging. Having the main site built from the [docs](https://github.com/pattern-lab/patternlab-node/tree/dev/packages/docs) will also prevent people to look at the outdated [website](https://github.com/pattern-lab/website/).

I recently started collaborating on `engine-twig`. While I can say that I know my way around PL as a user, I still miss a lot of information to succesfully contribute to this project. Any contribution on the docs side is not visible on the main domain.

**Comment by bmuenzenmeyer** [comment]
it's live! I think it's still pointing to `dev` - but that's still better.

I am closing this issue as too vague to act upon. @simonseddon if you want to contribute videos I am sure we can find a home for them once built, perhaps under https://patternlab.io/resources/
