### ISSUE TITLE
Shorthand Include Syntax in Pattern Lab Node ^3

### ISSUE THREAD

**Issue by davidmoret** [pattern-lab/patternlab-node#1068]
Hi everyone,

I am using Pattern Lab Node v3.0.3 with engine-twig-php v3.0.3 on Mac, with Node v10.16.0, using a Gulp Edition.
When I use the shorthand include syntax, it doesn't work.
I have a pattern in 01-atoms/03-images/image/demo/image-demo.twig and when I try to include it via {% include "atoms-image-demo"%} I have this console error : Error trying to render... "atoms-image-demo" template is not defined in...
Is the shorthand include syntax still relevant in Pattern Lab Node 3 ?

Thank you in advance for this clarification :)

**Comment by bmuenzenmeyer** [comment]
does the shorthand include syntax work in Twig? Our goal is to rid Pattern Lab of custom conventions that increase lock in

**Comment by davidmoret** [comment]
Ok, thanks for the answer.

**Comment by perriard** [comment]
> does the shorthand include syntax work in Twig? Our goal is to rid Pattern Lab of custom conventions that increase lock in

I'm not sure I understand the answer. In the docs https://patternlab.io/docs/including-patterns/ there are shorthand syntax examples, but it does not seem to work for me (node version, twig engine).

Edit: using {% include "atoms-logo" %} to include 00-atoms/04-images/00-logo.twig does not work.
