### ISSUE TITLE
Error serving PL after installing custom starterkit

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/patternlab-node#1070]
@bmuenzenmeyer running `npm create pattern-lab, I chose the following:

<img width="730" alt="Screen Shot 2019-10-11 at 4 34 19 PM" src="https://user-images.githubusercontent.com/383701/66683248-fd1d5500-ec44-11e9-8082-66d384d372ad.png">

I pointed to the newly added [vanilla handlebars starterkit](https://www.npmjs.com/package/@pattern-lab/starterkit-handlebars-vanilla).

When I went to build the project via `npm run pl:serve` I get the following error: 

```
⊙ patternlab → serve: Serving your files …
Pattern Lab Node v3.0.3
Pattern Engine handlebars: good to go
Pattern Engine mustache: good to go
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

ERROR: missing an essential file from /Users/frostbd/Desktop/pattern-lab/node_modules/@pattern-lab/uikit-workshop./node_modules/styleguidekit-mustache-default/views/. Pattern Lab won't work without this file.


Configuration key [paths.source.patternlabFiles] inside patternlab-config.json was found as the string './node_modules/styleguidekit-mustache-default/views/'
Since Pattern Lab Node Core 3.0.0 this key is an object. Suggest you update this key following this issue: https://github.com/pattern-lab/patternlab-node/issues/683.


Configuration key [debug] inside patternlab-config.json was found. As of Pattern Lab Node Core 3.0.0 this key is replaced with a new key, [logLevel]. This is a string with possible values ['debug', 'info', 'warning', 'error', 'quiet'].
Turning on 'info', 'warning', and 'error' levels by default, unless [logLevel] is present. If that is the case, [debug] has no effect.

Incremental builds enabled.
Pattern Lab is watching for changes to files under ./source/
```

<img width="917" alt="Screen Shot 2019-10-11 at 4 35 25 PM" src="https://user-images.githubusercontent.com/383701/66683321-2b9b3000-ec45-11e9-96b4-b3faccbaad18.png">

Looking at `patternlab-config.json` yields the following:

```
"patternlabFiles": "./node_modules/styleguidekit-mustache-default/views/",
```

Not sure what to update this to in order to get things to work.

**Comment by bmuenzenmeyer** [comment]
taking a look

**Comment by bmuenzenmeyer** [comment]
oh i see what is happening - the startkit is merging in an old config - un momento

**Comment by bmuenzenmeyer** [comment]
@bradfrost please try again.  Left you a DM about the sass

**Comment by bmuenzenmeyer** [comment]
this is fixed
