### ISSUE TITLE
Figure out why postMessage has inconsistent calls/results

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#108]
Sometimes needs to be a string and sometimes needs to be an object

Here's an example usage of an object, in fact I hacked it to just parse the stringified object. 
https://github.com/pattern-lab/patternlab-node/blob/fc4d4208147981fc02953afb956f7960253c1f26/public/styleguide/js/code-viewer.js#L300

There are places all over pattern lab that pass in the object, however:

https://github.com/pattern-lab/patternlab-node/search?utf8=%E2%9C%93&q=JSON.parse%28obj%29

The combination of these two usages makes evaluation at https://github.com/pattern-lab/patternlab-node/blob/master/public/styleguide/js/postmessage.js#L54 fail.

I am probably just overlooking something, but I dedicated look would be smart.

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

So IE something or other expects postMessage to be a string as opposed to an object FWIW. I tried to standardize on string but I could have missed ones. I'm working through the JS over the next few weeks if you want to follow along in `pattern-lab/styleguide-assets-default`. A bunch of front-end stuff needs borked in PL2.

**Comment by bmuenzenmeyer** [comment]
Ah that gives me some clues - thanks for the thoughts :D
