### ISSUE TITLE
Disable live reload?

### ISSUE THREAD

**Issue by erik-peterson-fox** [pattern-lab/patternlab-node#1084]
I am using Pattern Lab Node 1.0.4 (Pattern Lab Node Core version: 3.0.5)
 on `Windows 10`, with Node `v10.16.3`, using a `Vanilla?` Edition. I assume it's vanilla edition because I used the docs https://patternlab.io/docs/installation.html and do not have grunt or gulp involved to my knowledge.

##### Expected Behavior
My devops team wants me to disable the websockets - we want to deploy patternlab to a test server so qa and designers can test there... but I wasn't able to find how to disable live reload.

##### Actual Behavior
I found a --no-watch command in the cli but it has no effect, no configuration options seem to be available to otherwise shut this behavior off.

**Comment by erik-peterson-fox** [comment]
I should note also that while I know the pl:build script can be used to generate something in the public directory which can be deployed, we can't deep link to any specific patterns, making it hard to share links which point to specific patterns like we can with the server.

**Comment by bmuenzenmeyer** [comment]
does `pl:build` meet your needs? PL is a static site generator so the contents of Pattern Lab's generation  are output to `public/` by default, which the server hosts for you.

**Comment by erik-peterson-fox** [comment]
I'm very sorry. It seems like it does meet my needs. I forgot to retry that after upgrading to PL 2
