### ISSUE TITLE
pl-c-viewport-size off by 30px

### ISSUE THREAD

**Issue by savwheel** [pattern-lab/patternlab-node#1085]
Hi there! I came across a small bug in relation to the viewport sizing on the PL Banner. 
The `pl-c-viewport-size` includes the width of the `pl-c-viewport__resizer`(30px). This makes the number shown 30px bigger than what the actual viewport width is.

<img width="299" alt="Screen Shot 2019-10-24 at 9 22 57 AM" src="https://user-images.githubusercontent.com/35963106/67489945-6d15dd00-f640-11e9-8084-2b59a66acc6a.png">

It's a small issue but make's resizing for mobile a little more difficult.

**Comment by erik-peterson-fox** [comment]
I was about to raise a similar issue... the difference is larger for me though... here's a screenshot of the width displayed to the user and the actual width of the html (when hovering over it in devtools)

![image](https://user-images.githubusercontent.com/44481565/67520533-0a8c0380-f677-11e9-8366-d948561a2787.png)

**Comment by erik-peterson-fox** [comment]
Possibly a clone of this issue or is already addressed by it https://github.com/pattern-lab/patternlab-node/issues/1062
