### ISSUE TITLE
Patternlab 3 Handlebars With Bootstrap version 4 

### ISSUE THREAD

**Issue by Rajawebz** [pattern-lab/patternlab-node#1090]
I am using Pattern Lab Node `v.3.0.4` on `Windows`, with Node `v.10.16.3`, using a `Handlebars Custom edition` Edition.

##### Expected Behavior
              Once the page is build after installation ,it shows all menus like "atoms,molecules,organisms,templates,pages." pattern info.And in menu option by clicking show pattern info also it shows.
![screen-1](https://user-images.githubusercontent.com/40914685/68116122-10f46800-ff20-11e9-8f9c-9f1eac386040.PNG)

![screen-3](https://user-images.githubusercontent.com/40914685/68116301-76e0ef80-ff20-11e9-809e-49fceccaa842.PNG)

##### Actual Behavior
            But here once  the page is rebuild using the command "npm run pl:serve".It shows pattern info for menus "templates,pages" by clicking menu show pattern info.But for menus like "atoms, molecules,organisms" it doesn't show the pattern info and by clicking the drop down icon from each pattern also it doesn't show the pattern info.

![screen-2](https://user-images.githubusercontent.com/40914685/68116319-85c7a200-ff20-11e9-9f8a-61e90ade2fa3.PNG)

![screen-4](https://user-images.githubusercontent.com/40914685/68116334-91b36400-ff20-11e9-9076-82d00ac76764.PNG)

Help me to fix this issue.

**Comment by kentr** [comment]
@Rajawebz If you don't need handlebars, I've started a twig Bootstrap4 starterkit: https://www.npmjs.com/package/@kentr/starterkit-twig-bootstrap4

I'm still figuring out how to make the installation work correctly with the new monorepo & `npm`, but it works if you simply install the patterns manually into an existing PHP / Twig pattern lab project.
