### ISSUE TITLE
Can't scroll the menu on mobile devices when I'm in landscape mode

### ISSUE THREAD

**Issue by cgahmann** [pattern-lab/patternlab-node#1091]
I can't scroll the menu on mobile devices when I'm in landscape mode. So I cannot get to the lower menu items.
Tested on http://demo.patternlab.io/

![landscape-mode](https://user-images.githubusercontent.com/13014767/68121959-8739a000-ff09-11e9-8ce0-0243cca1155d.png)

**Comment by bmuenzenmeyer** [comment]
this demo is not representative of the current state of the UI and will not be fixed.
can you retest on https://patternlab-handlebars-preview.netlify.com
