### ISSUE TITLE
Reload a second level patterns page

### ISSUE THREAD

**Issue by davidmoret** [pattern-lab/patternlab-node#1095]
Hi, I am using Pattern Lab Node `v3.0.1` on `Linux`, with Node `v10.16.0`, using a `Gulp` Edition.

##### Expected Behavior
I would like to reload a second level page.

##### Actual Behavior
When I enter a second level url in my browser (ex: http://localhost:3000/?P=viewall-atoms-fields), the page is well rendered but the url changes immediately after the page is loaded (http://localhost:3000/p=viewall-Atoms-01-Atoms).

Has anyone noticed similar behavior? I may be doing something wrong ..

**Comment by Nuuou** [comment]
I'm experiencing an identical issue as the one you've outline, where the second-tier has a quick URL change, and subsequent reloading results in a blank inner iframe.

I am using Pattern Lab Node `v5.3.0` on `Linux`, with Node `v12.13.0`, using a `Vanilla` Edition.

**Comment by Nuuou** [comment]
I believe these are related:
Issue: https://github.com/pattern-lab/patternlab-node/issues/890#issuecomment-483380465
Recent PR: https://github.com/pattern-lab/patternlab-node/pull/1058

When removing the numbered folder names from the comment in the first link, this fixes my issue.

**Comment by davidmoret** [comment]
Thanks for the answer.
I renamed my folders, do some tests on the md files and folder structure, but without success. Without md file I can't accès to /?p=viewall-molecules-blocks and with md the url change to /?p=viewall-molecules-molecules.
