### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#11]
https://github.com/pattern-lab/patternlab-php/issues/22

**Comment by mateuspv** [comment]
I normally use git/git tags for this kind of problem, but here come some Ideas:

command: patternlab generate version:my-release
```
        ./build
       ├── latest
       └── version-my-release

```
1 - copy the latest version
2 - paste as version-XXX
3 - Our "public" folder now is "./build/latest"
4 - The folders are visible in the pattern lab menu

**Comment by bmuenzenmeyer** [comment]
I like your git approach,  and know of many teams that use version control
systems to achieve this.

As you imply by the pseudocode (are you a PL PHP user?), finding something
more approachable and integrated into the ui is what is desired.

As it currently stands,  this is a far future item in my book, if ever, but
thanks for the thoughts!

**Comment by bmuenzenmeyer** [comment]
This issue has been opened forever.
Closing
