### ISSUE TITLE
Unnamespaced button style in uikit-workshop

### ISSUE THREAD

**Issue by cbirdsong** [pattern-lab/patternlab-node#1109]
The button styles in this file were causing an inheritance issue in my CSS: https://github.com/pattern-lab/patternlab-node/blob/dev/packages/uikit-workshop/src/sass/scss/02-base/_reset.scss

**Comment by mfranzke** [comment]
Response

**Comment by mfranzke** [comment]
hello bot

**Comment by mfranzke** [comment]
A potential fix has been provided.

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
