### ISSUE TITLE
What is the purpose of the oPatternItem object ?

### ISSUE THREAD

**Issue by walmokrani** [pattern-lab/patternlab-node#111]
Sorry for my bad english.  I'am trying to read the code and can't figure out the purpose of the oPatternItem object in the builder\object_factory.js file. Why is it there ? please

**Comment by bmuenzenmeyer** [comment]
Hi @walmokrani 

Looks like some dead code, as this shows: [https://github.com/pattern-lab/patternlab-node/search?utf8=%E2%9C%93&q=oPatternItem](https://github.com/pattern-lab/patternlab-node/search?utf8=%E2%9C%93&q=oPatternItem) it's only included there and in the tests. I will make sure to remove it next release, or you may submit a PR to the `dev` branch if you want to help out :)

**Comment by bmuenzenmeyer** [comment]
Just pushed this to dev - will close once it reaches master
