### ISSUE TITLE
Pattern-parameters being deleted after first call

### ISSUE THREAD

**Issue by EmKaCe** [pattern-lab/patternlab-node#1110]
Hello, I am currently noticing an issue with patternlab-node v5.4.2 on Windows 10 using the vanilla edition with mustache.

Pattern parameters are not working as they are supposed to. The included pattern seems to "fire and forget" about the variable that has been passed and doesn't identify Strings as set parameters.

##### My use-case

testmolecule.mustache
```
{{> atoms-testatom(foo: "bar")}}
{{> atoms-testatom(foo: true)}}
```

testatom.mustache
```
{{#foo}}
    <p>Set to: {{foo}}</p>
{{/foo}}
{{^foo}}
    <p>Not set!</p>
{{/foo}}
```

##### Expected Behavior

```
<p>Set to: bar</p>
<p>Set to:</p>
```

##### Actual Behavior

```
<p>Not set!</p>
<p>Set to: </p>
<p>Not set!</p>
```

**Comment by perriard** [comment]
I have this issue too.
A simple example is a form input, the labels for="" comes out empty

<input type="text" id="{{id}}" class="form-control" {{readonly}} {{hidden}}>
    <label for="{{id}}">{{label}}</label>

**Comment by JosefBredereck** [comment]
Could you please check if you have `cleanPublic` on `false` in your patternlab config?
