### ISSUE TITLE
Annotations and status at Patternlab 3

### ISSUE THREAD

**Issue by mhlozek** [pattern-lab/patternlab-node#1115]
Are annotations and statuses implemented at Patternlab 3 yet?
I tried to create _annotations folder with annotations.json file, but annotations aren't visible on info panel :( and I have the same problem with pattern status.

**Comment by bmuenzenmeyer** [comment]
we think this is a known uikit-workshop problem, right @sghoweri ?

statuses worked last i checked...

**Comment by sghoweri** [comment]
I'll have to double-check but I do know that annotations were one of the items on the refactor list needing to get re-reviewed (and likely updated at the UIKit level).

Will let you guys know once I have a little more info!

**Comment by sghoweri** [comment]
^ statuses worked last i checked...

@bmuenzenmeyer I thought so as well... 🤔

**Comment by mhlozek** [comment]
Statuses are ok - I had error in my .md file. 
Thank you for letting me know.
