### ISSUE TITLE
Scrollbars in Pattern Flyouts in Edge 18

### ISSUE THREAD

**Issue by OktarinTentakel** [pattern-lab/patternlab-node#1124]
Using my local setup with Patternlab Node and Uikit Workshop as well as your own example

https://patternlab-handlebars-preview.netlify.com/

I see scrollbars appearing on the corners of the top pattern flyouts. Of course this is a b-bug, since it's not breaking anything. It's just a little ugly. :D

![Bildschirmfoto 2020-02-11 um 10 42 17](https://user-images.githubusercontent.com/4561418/74225737-8f993800-4cbb-11ea-8dd0-a5a3d0c7352c.png)

**Comment by sghoweri** [comment]
Yeah, the horizontal scrollbars especially aren't great... 🤦‍♂ 

PR's are most certainly welcomed to polish this up! Otherwise I'll do my best to get around to this soon (hopefully this coming weekend 🤞)

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
