### ISSUE TITLE
Semantic and Data Structure Problems with lodash's merge in Pseudopattern Hunter

### ISSUE THREAD

**Issue by OktarinTentakel** [pattern-lab/patternlab-node#1127]
I asked this question a week ago in Gitter, but no response so far, so instead of asking this repeatedly in a rythmic fashion, I'll just put this in a ticket:

Hi there,

migrating from Pattern Lab 2 to PL3 I was suprised to find the way pseudo pattern data is constructed being changed. It seems that data is now merged via lodash's _.merge in the pseudo pattern hunter whereas before it was replaced key by key.

I definitely see the appeal of this change for many cases, however this makes practical construction of pattern examples sometimes a little bit difficult and counter-intuitive.

An example:
I have a tabs pattern with 5 tabs as the main json.
Now I want to construct a reduced pseudo variant only showing 2 tabs.

In PL2 I could just overwrite the tabs-array with a new array in the variant, but the PL3 merge just replaces indices one and two and keeps the rest like it is. Of course I could switch the variants, but in my opinion the main json should always show the "default" usage, therefore I am not really free to do this.

Do you have any suggestion on how to handle this?

Of course I could null out single entries in an array, but I'd have to handle that explicitly in template, which again, is cumbersome. The current fact that we can not reset/overwrite a complete array results in technical contraints to logical structures, which should not be the case in my opinion.

In my opinion, the old way of doing a deep extend/assign made total sense, but I also see the pros of the current implementation in certain cases.

My proposal would be this: make the algo configurable via config and maybe allow a pattern-based override.

**Comment by OktarinTentakel** [comment]
Any news on this?

This is still a major problem for us.

**Comment by JosefBredereck** [comment]
I will take a look on this topic at the weekend. Thanks for identifying the root cause so far.

**Comment by JosefBredereck** [comment]
I'm a little ambivalent on the matter. As you already mentioned both cases have their advantages and disadvantages. Also, there are multiple different ways of giving configurations to do it the one or the other way, but after thinking the whole weekend about this case I didn't come to a proper solution.

**Comment by OktarinTentakel** [comment]
@JosefBredereck 

This ambivalence you mention is exactly the problem with keeping the current solution static.

It's a matter of perspective and design philosophy, but at the same time there is no clear winner in terms of semantics or elegance.

My problem is simply, that I cannot follow a perfectly logical and battle-proven way of building patterns any more without working against the system and adding PL data logic to templates (which is not a good idea).

My proposal:

Both algos have their right to exists, are implemented, known and well tested. Just keep the lodash merge as default, but give me a config option to swap the function with the old method. Call it "pseuoPatternMergeArrays" or something and set it to true by default (since the array behaviour is the only really significant and counter-intuitive difference).

For extra flexibility you could document the (rather simple) interface for the merging and offer the option to overwrite the default with a custom implementation.

Both variants individually or together would be alright for me, but having to circumvent automagic array merging via template source make me sad. I'd rather live with more data reptition as before.

**Comment by JosefBredereck** [comment]
Ok, I'll create an pr and let's see what the others think about that ticket.

**Comment by OktarinTentakel** [comment]
Thanks

**Comment by bmuenzenmeyer** [comment]
> My problem is simply, that I cannot follow a perfectly logical and battle-proven way of building patterns any more without working against the system and adding PL data logic to templates (which is not a good idea).

well said!

**Comment by sghoweri** [comment]
Issue was released with v5.11.1

**Comment by smurrayatwork** [comment]
@sghoweri @JosefBredereck  It doesn't appear that this issue was fixed for engine-twig-php. Would it be possible to fix that engine as well, or should that engine not be used?

**Comment by JosefBredereck** [comment]
@smurrayatwork That's a very good question. Since it was part of the core package it should be fixed also.
I never used this engine so I cannot test or say where the issue comes from. Do you have a test package or repo somewhere?
