### ISSUE TITLE
No Watch installed

### ISSUE THREAD

**Issue by HecOsbRod** [pattern-lab/patternlab-node#1130]
I just recently installed pattern-lab with the following options:
- Handlebars
- Handlebars base patterns

It doesn't come with any watch file (gulp, grunt or npm)

I'm running `mac` with `node v12.15.0`

**Comment by bmuenzenmeyer** [comment]
running `npm run pl:serve` starts pattern lab in watch mode by default. does this meet your needs?

**Comment by HecOsbRod** [comment]
It is not listening to scss or component changes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mfranzke** [comment]
Patternlab.io itself doesn‘t provide any CSS preprocessor (like sass/scss) compiling functionality and that for not a watcher - so you‘re perfectly free to choose one on your own.

And what exactly do you mean by component changes? Using the command that Brian has mentioned should start a watcher for *.hbs file changes and reload the pattern page in the browser after you did a change.

**Comment by hmalaud** [comment]
Just installed PL node version and it's not watching CSS changes either.

**Comment by mfranzke** [comment]
> Just installed PL node version and it's not watching CSS changes either.
> You might want to have a look at #1064, it fixed CSS watch for me.

Oh, yeah, missed that aspect.
