### ISSUE TITLE
improvement: ability to configure default pattern info code panel

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1155]
Being able to configure the initial pattern info code panel instead of always using the pattern template being used by the design system e.g. offers showing the `HTML` code initially.

That HTML code might be the most relevant code for diverse systems or target template usage in larger constructs or enterprises, where a central design system team e.g. uses handlebars, but the HTML gets integrated into several different template languages afterwards.

**Comment by mfranzke** [comment]
Actually the merge request for this ticket just needs to get reviewed ... and merged.

**Comment by JosefBredereck** [comment]
The issue was released with v5.13.0 🎉
