### ISSUE TITLE
The headline in new Docs not rendered properly

### ISSUE THREAD

**Issue by JosefBredereck** [pattern-lab/patternlab-node#1158]
[Managing Pattern Assets](https://patternlab-docs-preview.netlify.app/docs/managing-pattern-assets/)

Images tell you more than 1000 words 😄 

![grafik](https://user-images.githubusercontent.com/13408112/80242832-4d4e8880-8666-11ea-9adb-d076257d557c.png)

**Comment by bradfrost** [comment]
@JosefBredereck Fun! Thanks for the heads up.

**Comment by mfranzke** [comment]
Actually the merge request for this ticket just needs to get reviewed ... and merged.

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
