### ISSUE TITLE
fix(plugintabs): enabling multiple file formats

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1163]
@bmuenzenmeyer your overwrite with commit b82bd129fdbe48de95b62d75fb7fe95cea896b7e of the [placeholders `<<type>>` and `<<typeUC>>` (to hardcoded `scss`)](https://github.com/pattern-lab/patternlab-node/blob/73eac976461f4e587b0c30668942c4895aea319f/packages/plugin-tab/src/snippet.js#L3-L11) that are used within the script https://github.com/pattern-lab/patternlab-node/blob/dev/packages/plugin-tab/index.js now results in that only one file (and only `scss` filetype/language) could get configured within the `patternlab-config.json`.

It looks to me like that this happened by accident - I would than like to offer to fix this (and some other small parts) for this to work correctly again, if the change didn't happen on purpose.

**Comment by bmuenzenmeyer** [comment]
yes this looks like a bug to me - though only that portion. the intent of that commit was still to check for `window.patternlab` && `window.patternlab.panels`
