### ISSUE TITLE
Docs to review for deletion

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1164]
packages/docs/src/docs/advanced-integration-with-grunt.md
packages/docs/src/docs/pattern-converting.md
packages/docs/src/docs/generating-css.md
packages/docs/src/docs/advanced-integration-with-compass.md
packages/docs/src/docs/advanced-page-follow.md

**Comment by mfranzke** [comment]
Fight the bot
