### ISSUE TITLE
New Docs Site: Can't Close Nav By Tapping Outside on Mobile

### ISSUE THREAD

**Issue by sghoweri** [pattern-lab/patternlab-node#1169]
##### Expected Behavior
Tapping anywhere outside of the main Nav while expanded will automatically close the main Nav (aka like how Dropdowns normally work)

##### Actual Behavior
Nav remains open when tapping / interacting with any UI outside of it.

![6F05C89D-AE40-4A3A-A71F-6E0352294331](https://user-images.githubusercontent.com/1617209/80540459-5cd81500-8977-11ea-8fbf-3737d6d360e2.png)

**Comment by mfranzke** [comment]
Fight the bot

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
