### ISSUE TITLE
New Docs Site: Expand Nav has z-index issues on smaller screens

### ISSUE THREAD

**Issue by sghoweri** [pattern-lab/patternlab-node#1170]
![E1B248EB-2C86-476A-81A4-4FE55DF703C9](https://user-images.githubusercontent.com/1617209/80540668-ba6c6180-8977-11ea-97f0-6daac563e31e.png)

**Comment by mfranzke** [comment]
For some reason the tiles pattern has a `z-index` of 100 defined:
https://github.com/pattern-lab/patternlab-node/blob/8afd3f3694fdde45369516c5d753494f8cfd3784/packages/docs/src/scss/components/_tile.scss#L7

If this would get removed, the navigation wouldn't get overlayed any more. And the reason for defining that `z-index` in general isn't clear to me.
