### ISSUE TITLE
New Docs Site: Overflow Scrolling Issues

### ISSUE THREAD

**Issue by sghoweri** [pattern-lab/patternlab-node#1171]
![35AFDE4F-5964-456F-A9D9-85B820191CB1](https://user-images.githubusercontent.com/1617209/80540883-25b63380-8978-11ea-9269-c9dbaa32e9b1.gif)

**Comment by mfranzke** [comment]
This is related to the codes content not wrapping, compare to e.g.:
![image](https://user-images.githubusercontent.com/787658/84569274-857c6880-ad85-11ea-97bb-ce5a51e736fa.png)

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
