### ISSUE TITLE
Deprecate Style Modifiers 

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1177]
Converted from https://github.com/orgs/pattern-lab/projects/3

http://patternlab.io/docs/pattern-stylemodifier.html

**BM: Template Engines** accomplish this in their own way. Kill this mustachism

**Comment by JosefBredereck** [comment]
What exactly are style modifiers? I know the pattern parameters but forgot the other since the docs are not available anymore.

**Comment by mfranzke** [comment]
> What exactly are style modifiers? I know the pattern parameters but forgot the other since the docs are not available anymore.

Here‘s their previous specs content:
https://web.archive.org/web/20180710175641/http://patternlab.io/docs/pattern-stylemodifier.html

I‘ll try to find more details/issue regarding their deprecation.

**Comment by bmuenzenmeyer** [comment]
We wanted to deprecate them because it was another place where PL created a proprietary mustache extension that locked pattern content into PL but not the broader community. You couldn't migrate your PL patterns into 11ty or some such thing that understood mustache.

This desire to get back to vanilla support for template languages drove a lot of decisions.
