### ISSUE TITLE
Github Actions over Travis-CI?

### ISSUE THREAD

**Issue by ringods** [pattern-lab/patternlab-node#1185]
I have converted a few personal projects already to Github Actions with positive outcome.

Here are a few of the things I find beneficial on Github Actions:

* one can create multiple workflows in separate files (e.g. build vs website publish)
* workflows can be triggered by different types of events e.g. git commits, webhooks, cron
* Github Actions is *much* faster

What do we need to know whether or not this project will make the switch?

**Comment by bmuenzenmeyer** [comment]
I'd be curious to see how this evolves! I only tried out GH actions briefly when they came out - and reducing our footprint feels like a good thing to me.

**Comment by ringods** [comment]
@bmuenzenmeyer just updated the issue descriptioin. 😉

**Comment by bmuenzenmeyer** [comment]
> What do we need to know whether or not this project will make the switch?

we need someone to commit to the work and shepherd it through.

Preserving the minimum PR flow should be the first goal. Netlify integrations already do the docs site preview and handlebars preview - but if that can be done some other way I am open to it.

**Comment by ringods** [comment]
@bmuenzenmeyer while working on #1225, I was following up on the roundtrip time for Github Actions and Travis. After 2 hours, Travis hasn't even started running the build for my last commit...

<img width="962" alt="travis-delay" src="https://user-images.githubusercontent.com/77923/88482214-2868fa80-cf60-11ea-9d35-74e5ccbe58b7.png">
