### ISSUE TITLE
Cleanup core published files

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1186]
It looks like core current publishes test and .nyc_output, or perhaps everything.

We need to use the `files` key in the pacakge.json to omit things from publication.

<details><summary>partial log...</summary>
erna notice 14B     test/files/_handlebars-test-patterns/00-atoms/00-global/00-helloworld.h
bs
lerna notice 51B     test/files/_handlebars-test-patterns/00-molecules/00-global/00-hellowor
lds.hbs
lerna notice 46B     test/files/_handlebars-test-patterns/00-molecules/00-global/00-hidden-p
attern-tester.hbs
lerna notice 35B     test/files/_handlebars-test-patterns/00-atoms/00-global/10-at-partial-b
lock.hbs
lerna notice 75B     test/files/_handlebars-test-patterns/00-molecules/00-global/10-call-at-
partial-block.hbs
lerna notice 552B    test/files/_meta/_00-head.html

lerna notice 21B     test/files/_underscore-test-patterns/00-atoms/00-global/_00-hidden.html

lerna notice 68B     test/files/_meta/_01-foot.html

lerna notice 189B    test/files/_underscore-test-patterns/00-molecules/00-global/00-call-ato
m-with-molecule-data.html
lerna notice 31B     test/files/_underscore-test-patterns/00-atoms/00-global/00-helloworld-w
ithdata.html
lerna notice 14B     test/files/_underscore-test-patterns/00-atoms/00-global/00-helloworld.h
tml
lerna notice 117B    test/files/_underscore-test-patterns/00-molecules/00-global/00-hellowor
lds.html
lerna notice 74B     test/files/_underscore-test-patterns/00-molecules/00-global/00-hidden-p
attern-tester.html
lerna notice 0       pattern_exports/test-paramParent.html

lerna notice 60B     .eslintrc.js

lerna notice 1.4kB   test/addPattern_tests.js

lerna notice 1.4kB   src/lib/addPattern.js

lerna notice 2.4kB   test/annotation_exporter_tests.js

lerna notice 3.4kB   src/lib/annotation_exporter.js

lerna notice 803B    test/files/annotations.js

lerna notice 1.4kB   src/lib/buildFooter.js

lerna notice 1.8kB   test/buildListItems_tests.js

lerna notice 1.1kB   src/lib/buildListItems.js

lerna notice 9.2kB   src/lib/buildPatterns.js

lerna notice 1.3kB   test/changes_hunter_tests.js

lerna notice 3.8kB   src/lib/changes_hunter.js

lerna notice 645B    src/lib/cleanBuildDirectory.js

lerna notice 7.1kB   src/lib/compose.js

lerna notice 1.7kB   test/copier_tests.js

lerna notice 3.3kB   src/lib/copier.js

lerna notice 690B    src/lib/copyFile.js

lerna notice 345B    test/data_loader_tests.js

lerna notice 2.0kB   src/lib/data_loader.js

lerna notice 1.7kB   src/lib/decompose.js

lerna notice 882B    scripts/docs.js

lerna notice 11.6kB  test/engine_handlebars_tests.js

lerna notice 8.2kB   test/engine_liquid_tests.js

lerna notice 7.7kB   test/engine_mustache_tests.js

lerna notice 1.4kB   test/engine_react_tests.js

lerna notice 8.2kB   test/engine_twig_tests.js

lerna notice 4.2kB   test/engine_underscore_tests.js

lerna notice 3.6kB   src/lib/events.js

lerna notice 3.3kB   src/lib/expandPartials.js

lerna notice 1.9kB   test/exportData_tests.js

lerna notice 2.8kB   src/lib/exportData.js

lerna notice 1.6kB   src/lib/findModules.js

lerna notice 2.0kB   test/get_tests.js

lerna notice 1.4kB   src/lib/get.js

lerna notice 9.3kB   test/index_tests.js

lerna notice 11.5kB  src/index.js

lerna notice 411B    src/lib/isScopedPackage.js

lerna notice 397B    src/lib/json_copy.js

lerna notice 24.6kB  test/lineage_hunter_tests.js

lerna notice 5.9kB   src/lib/lineage_hunter.js

lerna notice 1.9kB   test/list_item_hunter_tests.js

lerna notice 1.4kB   src/lib/list_item_hunter.js

lerna notice 3.0kB   test/loadPattern_tests.js

lerna notice 6.2kB   src/lib/loadPattern.js

lerna notice 775B    src/lib/loadPatternGraph.js

lerna notice 2.9kB   src/lib/loaduikits.js

lerna notice 3.3kB   test/loaduitkits_tests.js

lerna notice 1.5kB   src/lib/log.js

lerna notice 1.7kB   test/markdown_parser_tests.js

lerna notice 1.6kB   src/lib/markdown_parser.js

lerna notice 3.6kB   test/markModifiedPatterns_tests.js

lerna notice 1.7kB   src/lib/markModifiedPatterns.js

lerna notice 8.7kB   test/object_factory_tests.js

lerna notice 8.7kB   src/lib/object_factory.js

lerna notice 15.2kB  test/parameter_hunter_tests.js

lerna notice 13.3kB  src/lib/parameter_hunter.js

lerna notice 3.5kB   test/parseAllLinks_tests.js

lerna notice 644B    src/lib/parseAllLinks.js

lerna notice 1.9kB   src/lib/parseLink.js

lerna notice 7.2kB   test/pattern_engines_tests.js

lerna notice 8.1kB   src/lib/pattern_engines.js

lerna notice 2.3kB   src/lib/pattern_exporter.js

lerna notice 3.4kB   src/lib/pattern_graph_dot.js

lerna notice 16.2kB  test/pattern_graph_tests.js

lerna notice 13.0kB  src/lib/pattern_graph.js

lerna notice 1.9kB   test/pattern_registry_tests.js

lerna notice 2.6kB   src/lib/pattern_registry.js

lerna notice 1.6kB   test/patternlab_tests.js

lerna notice 11.1kB  src/lib/patternlab.js

lerna notice 1.9kB   src/lib/plugin_manager.js

lerna notice 879B    src/lib/processIterative.js

lerna notice 1.2kB   src/lib/processMetaPattern.js

lerna notice 16.3kB  test/processRecursive_tests.js

lerna notice 753B    src/lib/processRecursive.js

lerna notice 3.9kB   test/pseudopattern_hunter_tests.js

lerna notice 4.1kB   src/lib/pseudopattern_hunter.js

lerna notice 2.3kB   src/lib/readDocumentation.js

lerna notice 329B    src/lib/render.js

lerna notice 1.4kB   test/replaceParameter_tests.js

lerna notice 1.0kB   src/lib/replaceParameter.js

lerna notice 3.9kB   src/lib/server.js

lerna notice 4.0kB   src/lib/starterkit_manager.js

lerna notice 2.3kB   test/style_modifier_hunter_tests.js

lerna notice 1.5kB   src/lib/style_modifier_hunter.js

lerna notice 1.6kB   test/util/test_utils.js

lerna notice 16.9kB  test/ui_builder_tests.js

lerna notice 32.0kB  src/lib/ui_builder.js

lerna notice 1.2kB   test/uikitExcludePattern_tests.js

lerna notice 198B    src/lib/uikitExcludePattern.js

lerna notice 1.2kB   test/watchAssets_tests.js

lerna notice 2.0kB   src/lib/watchAssets.js

lerna notice 997B    test/watchPatternLabFiles_tests.js

lerna notice 3.6kB   src/lib/watchPatternLabFiles.js

lerna notice 120B    test/files/_handlebars-test-patterns/00-molecules/00-global/00-call-ato
m-with-molecule-data.json
lerna notice 120B    test/files/_underscore-test-patterns/00-molecules/00-global/00-call-ato
m-with-molecule-data.json
lerna notice 64B     test/files/_handlebars-test-patterns/00-atoms/00-global/00-helloworld-w
ithdata.json
lerna notice 64B     test/files/_underscore-test-patterns/00-atoms/00-global/00-helloworld-w
ithdata.json
lerna notice 34B     test/files/_patterns/00-test/03-styled-atom.json

lerna notice 39B     test/files/_patterns/00-test/03-styled-atom~alt.json

lerna notice 108.6kB .nyc_output/04f99990-c431-4f46-a6fa-57ce6c1621ac.json

lerna notice 1.7kB   .nyc_output/processinfo/04f99990-c431-4f46-a6fa-57ce6c1621ac.json      

lerna notice 5.4kB   .nyc_output/059f8db9-70c8-4b83-b27f-a9a197f1f4e7.json

lerna notice 678B    .nyc_output/processinfo/059f8db9-70c8-4b83-b27f-a9a197f1f4e7.json      

lerna notice 79.8kB  .nyc_output/179b6aa2-275a-4f09-a6d2-e72d4f664099.json

lerna notice 1.3kB   .nyc_output/processinfo/179b6aa2-275a-4f09-a6d2-e72d4f664099.json      

lerna notice 99.1kB  .nyc_output/1de702d2-3304-40ba-9bca-f73cd9edc094.json

lerna notice 1.5kB   .nyc_output/processinfo/1de702d2-3304-40ba-9bca-f73cd9edc094.json      

lerna notice 105.7kB .nyc_output/22709fed-8879-45d8-b8b4-aa4de7be8981.json

lerna notice 1.7kB   .nyc_output/processinfo/22709fed-8879-45d8-b8b4-aa4de7be8981.json      

lerna notice 2.6kB   .nyc_output/2983d37b-1979-4fd9-921a-c92d82d36e06.json

lerna notice 672B    .nyc_output/processinfo/2983d37b-1979-4fd9-921a-c92d82d36e06.json      

lerna notice 4.9kB   .nyc_output/2b38896a-aaa7-45b3-a7c7-d58003acd6d4.json

lerna notice 755B    .nyc_output/processinfo/2b38896a-aaa7-45b3-a7c7-d58003acd6d4.json      

lerna notice 164.9kB .nyc_output/39ecd8db-c4c4-4fe5-b499-8fb459435fa8.json

lerna notice 2.6kB   .nyc_output/processinfo/39ecd8db-c4c4-4fe5-b499-8fb459435fa8.json      

lerna notice 27B     test/files/_patterns/00-test/474-pseudomodifier~test.json

lerna notice 36.4kB  .nyc_output/4ae82bd6-5b7f-4548-8119-38484f5c278e.json

lerna notice 949B    .nyc_output/processinfo/4ae82bd6-5b7f-4548-8119-38484f5c278e.json      

lerna notice 42.9kB  .nyc_output/4b0e5264-c0d7-4ac3-acb1-a3cc1efc8518.json

lerna notice 1.0kB   .nyc_output/processinfo/4b0e5264-c0d7-4ac3-acb1-a3cc1efc8518.json      

lerna notice 334.1kB .nyc_output/51d7bf48-f057-4028-8bd1-678721aa0049.json

lerna notice 4.3kB   .nyc_output/processinfo/51d7bf48-f057-4028-8bd1-678721aa0049.json      

lerna notice 171.4kB .nyc_output/54eb5ed7-71b0-4dc3-a21d-a2eb486a7d2a.json

lerna notice 2.7kB   .nyc_output/processinfo/54eb5ed7-71b0-4dc3-a21d-a2eb486a7d2a.json      

lerna notice 75.4kB  .nyc_output/5dd487d2-8e68-4dab-b434-39aba9ad056f.json

lerna notice 1.4kB   .nyc_output/processinfo/5dd487d2-8e68-4dab-b434-39aba9ad056f.json      

lerna notice 86.3kB  .nyc_output/62ffe0d4-619e-403c-9353-92bdeb411ae8.json

lerna notice 1.5kB   .nyc_output/processinfo/62ffe0d4-619e-403c-9353-92bdeb411ae8.json      

lerna notice 10.2kB  .nyc_output/715fc3e5-08f8-4bd4-8081-7904c21ef780.json

lerna notice 865B    .nyc_output/processinfo/715fc3e5-08f8-4bd4-8081-7904c21ef780.json      

lerna notice 12.4kB  .nyc_output/784e8f87-a36f-450c-b966-75b388db3a2b.json

lerna notice 821B    .nyc_output/processinfo/784e8f87-a36f-450c-b966-75b388db3a2b.json      

lerna notice 882B    .nyc_output/7ca5e045-af29-4455-be09-26abbda882d8.json

lerna notice 688B    .nyc_output/processinfo/7ca5e045-af29-4455-be09-26abbda882d8.json      

lerna notice 36.3kB  .nyc_output/7f086e08-06d0-47eb-8809-3264af16dddc.json

lerna notice 951B    .nyc_output/processinfo/7f086e08-06d0-47eb-8809-3264af16dddc.json      

lerna notice 69.8kB  .nyc_output/7fbcc7e6-7de5-4997-b934-6cd53274da30.json

lerna notice 1.2kB   .nyc_output/processinfo/7fbcc7e6-7de5-4997-b934-6cd53274da30.json      

lerna notice 119.6kB .nyc_output/878f810d-0125-4602-9883-deedd244b552.json

lerna notice 1.8kB   .nyc_output/processinfo/878f810d-0125-4602-9883-deedd244b552.json      

lerna notice 165.3kB .nyc_output/9a5f2b2f-d9c3-4328-8976-54d6d3598ed8.json

lerna notice 2.6kB   .nyc_output/processinfo/9a5f2b2f-d9c3-4328-8976-54d6d3598ed8.json      

lerna notice 81.3kB  .nyc_output/9c51f821-3bf1-4abd-8cdc-a47883f74c28.json

lerna notice 1.4kB   .nyc_output/processinfo/9c51f821-3bf1-4abd-8cdc-a47883f74c28.json      

lerna notice 72.8kB  .nyc_output/a78e1d9d-efe6-4003-aa2a-e3310d31c599.json

lerna notice 1.2kB   .nyc_output/processinfo/a78e1d9d-efe6-4003-aa2a-e3310d31c599.json      

lerna notice 123.5kB .nyc_output/a9ac3d8c-cda8-4d19-bfec-d9fb99dbeea2.json

lerna notice 1.9kB   .nyc_output/processinfo/a9ac3d8c-cda8-4d19-bfec-d9fb99dbeea2.json      

lerna notice 152.7kB .nyc_output/abef0e38-4d73-49e5-8362-69ac48d958f4.json

lerna notice 2.3kB   .nyc_output/processinfo/abef0e38-4d73-49e5-8362-69ac48d958f4.json      

lerna notice 2B      .nyc_output/af9059d9-ad16-4b20-8b8d-869781e5d28f.json

lerna notice 501B    .nyc_output/processinfo/af9059d9-ad16-4b20-8b8d-869781e5d28f.json      

lerna notice 4.2kB   .nyc_output/b3f41d51-efe1-45d5-b0fa-8d05196901dc.json

lerna notice 664B    .nyc_output/processinfo/b3f41d51-efe1-45d5-b0fa-8d05196901dc.json      

lerna notice 105.7kB .nyc_output/be5bf231-48b7-4f50-8168-44a6edae798f.json

lerna notice 1.7kB   .nyc_output/processinfo/be5bf231-48b7-4f50-8168-44a6edae798f.json      

lerna notice 6.3kB   .nyc_output/c29e2cd3-4dab-44de-ad3e-9dffb4cc4b3d.json

lerna notice 737B    .nyc_output/processinfo/c29e2cd3-4dab-44de-ad3e-9dffb4cc4b3d.json      

lerna notice 59.8kB  .nyc_output/c511463e-8d3c-47c0-bbf9-3b5438a51fab.json

lerna notice 1.3kB   .nyc_output/processinfo/c511463e-8d3c-47c0-bbf9-3b5438a51fab.json      

lerna notice 69.9kB  .nyc_output/c9e42940-e4ab-4dd4-bd0c-b2f6a77ffafa.json

lerna notice 1.2kB   .nyc_output/processinfo/c9e42940-e4ab-4dd4-bd0c-b2f6a77ffafa.json      

lerna notice 73.2kB  .nyc_output/d71a2260-9e72-410d-8cc3-ba316ac2e93e.json

lerna notice 1.2kB   .nyc_output/processinfo/d71a2260-9e72-410d-8cc3-ba316ac2e93e.json      

lerna notice 105.7kB .nyc_output/d9c96d85-e15c-4de6-904e-68260999bef4.json

lerna notice 1.7kB   .nyc_output/processinfo/d9c96d85-e15c-4de6-904e-68260999bef4.json      

lerna notice 50B     test/files/_data/data.json

lerna notice 7.5kB   test/public/dependencyGraph.json

lerna notice 83.1kB  .nyc_output/e58e1f87-a7d9-4c39-9f81-55545b85c393.json

lerna notice 1.4kB   .nyc_output/processinfo/e58e1f87-a7d9-4c39-9f81-55545b85c393.json      

lerna notice 73.3kB  .nyc_output/e7094480-b9d6-407b-9c4e-3a2d5ba17c1f.json

lerna notice 1.2kB   .nyc_output/processinfo/e7094480-b9d6-407b-9c4e-3a2d5ba17c1f.json      

lerna notice 105.7kB .nyc_output/eadaa695-17e4-4488-ab77-1b7011e08b53.json

lerna notice 1.7kB   .nyc_output/processinfo/eadaa695-17e4-4488-ab77-1b7011e08b53.json      

lerna notice 105.7kB .nyc_output/f1e24efe-f9d9-4a1a-94ff-dcc976df1ea2.json

lerna notice 1.7kB   .nyc_output/processinfo/f1e24efe-f9d9-4a1a-94ff-dcc976df1ea2.json      

lerna notice 22B     test/files/_data/foo-other.json

lerna notice 19B     test/files/_data/foo.json

lerna notice 31.3kB  .nyc_output/processinfo/index.json

lerna notice 254B    test/files/_data/listitems.json

lerna notice 110B    test/files/_patterns/00-test/listWithListItems.listitems.json

lerna notice 166B    test/files/_patterns/00-test/nav.json

lerna notice 2.1kB   package.json

lerna notice 33B     test/files/_patterns/00-test/paramParent.json

lerna notice 2.6kB   patternlab-config.json

lerna notice 2.3kB   test/util/patternlab-config.json

lerna notice 277B    test/public/testDependencyGraph.json

lerna notice 111B    test/files/_react-test-patterns/00-atoms/00-general/HelloWorld.jsx     

lerna notice 591B    test/files/_liquid_test-patterns/00-molecules/00-general/00-media-objec
t.liquid
lerna notice 171B    test/files/_liquid_test-patterns/00-atoms/00-general/08-button.liquid  

lerna notice 413B    test/files/_liquid_test-patterns/00-atoms/00-general/09-image.liquid   

lerna notice 164B    test/files/_patterns/00-test/00-foo.md

lerna notice 144B    test/files/_patterns/00-test/01-bar.md

lerna notice 12B     test/files/_patterns/00-test/02-baz.md

lerna notice 29B     test/files/_patterns/00-test/03-styled-atom.md

lerna notice 379B    test/files/annotations.md

lerna notice 21.9kB  CHANGELOG.md

lerna notice 7.0kB   docs/events.md

lerna notice 237B    test/files/nav.md

lerna notice 35B     test/files/_patterns/patternType1/patternSubType1.md

lerna notice 9.8kB   docs/README.md

lerna notice 6.2kB   README.md

lerna notice 0       test/files/_meta/_00-head.mustache

lerna notice 23B     test/files/_patterns/00-test/_00-hidden-pattern.mustache

lerna notice 0       test/files/_meta/_01-foot.mustache

lerna notice 59B     test/files/_patterns/00-test/_ignored-pattern.mustache

lerna notice 17B     test/files/_patterns/00-test/00-foo.mustache

lerna notice 5B      test/files/_patterns/00-test/01-bar.mustache

lerna notice 3B      test/files/_patterns/00-test/02-baz.mustache

lerna notice 70B     test/files/_patterns/00-test/03-styled-atom.mustache

lerna notice 178B    test/files/_patterns/00-test/04-group.mustache

lerna notice 238B    test/files/_patterns/00-test/05-group2.mustache

lerna notice 171B    test/files/_patterns/00-test/06-mixed.mustache

lerna notice 213B    test/files/_patterns/00-test/07-mixed-params.mustache

lerna notice 192B    test/files/_patterns/00-test/08-bookend-params.mustache

lerna notice 163B    test/files/_patterns/00-test/09-bookend.mustache

lerna notice 162B    test/files/_patterns/00-test/10-multiple-classes-numeric.mustache      

lerna notice 171B    test/files/_patterns/00-test/11-bookend-listitem.mustache

lerna notice 32B     test/files/_patterns/00-test/12-another-styled-atom.mustache

lerna notice 107B    test/files/_patterns/00-test/13-listitem.mustache

lerna notice 17B     test/files/_patterns/00-test/14-inception.mustache

lerna notice 67B     test/files/_patterns/00-test/15-hidden-pattern-tester.mustache

lerna notice 49B     test/files/_patterns/00-test/474-pseudomodifier.mustache

lerna notice 41B     test/files/_patterns/00-test/539-a.mustache

lerna notice 65B     test/files/_patterns/00-test/539-b.mustache

lerna notice 34B     test/files/_patterns/00-test/539-c.mustache

lerna notice 94B     test/files/_patterns/00-test/553-repeatedListItems.mustache

lerna notice 55B     test/files/_patterns/00-test/685-list.mustache

lerna notice 7B      test/files/_patterns/patternType1/patternSubType2/black.mustache       

lerna notice 6B      test/files/_patterns/patternType1/patternSubType1/blue.mustache        

lerna notice 59B     test/files/_patterns/00-test/comment-tag.mustache

lerna notice 40B     test/files/_patterns/00-test/comment.mustache

lerna notice 0       test/files/partials/general-footer.mustache

lerna notice 0       test/files/partials/general-header.mustache

lerna notice 6B      test/files/_patterns/patternType1/patternSubType2/grey.mustache        

lerna notice 33B     test/files/_patterns/00-test/link.mustache

lerna notice 44B     test/files/_patterns/00-test/linkInParameter.mustache

lerna notice 66B     test/files/_patterns/00-test/listWithListItems.mustache

lerna notice 61B     test/files/_patterns/00-test/listWithPartial.mustache

lerna notice 26B     test/files/_patterns/00-test/mirror.mustache

lerna notice 143B    test/files/_patterns/00-test/nav.mustache

lerna notice 174B    test/files/_patterns/00-test/parameterTags.mustache

lerna notice 61B     test/files/_patterns/00-test/paramMiddle.mustache

lerna notice 47B     test/files/_patterns/00-test/paramParent.mustache

lerna notice 0       test/files/partials/patternSection.mustache

lerna notice 0       test/files/partials/patternSectionSubtype.mustache

lerna notice 5B      test/files/_patterns/patternType1/patternSubType1/red.mustache

lerna notice 130B    test/files/_patterns/00-test/sticky-comment-verbose.mustache

lerna notice 127B    test/files/_patterns/00-test/sticky-comment.mustache

lerna notice 0       test/files/viewall.mustache

lerna notice 7B      test/files/_patterns/patternType1/patternSubType2/white.mustache       

lerna notice 8B      test/files/_patterns/patternType1/patternSubType1/yellow.mustache      

lerna notice 591B    test/files/_twig-test-patterns/00-molecules/00-general/00-media-object.
twig
lerna notice 171B    test/files/_twig-test-patterns/00-atoms/00-general/08-button.twig      

lerna notice 413B    test/files/_twig-test-patterns/00-atoms/00-general/09-image.twig       

lerna notice 24B     test/files/_data/data.yaml

lerna notice 22B     test/files/_data/data.yml

lerna notice === Tarball Details ===
lerna notice name:          @pattern-lab/core
lerna notice version:       5.9.3
lerna notice filename:      pattern-lab-core-5.9.3.tgz
lerna notice package size:  527.1 kB
lerna notice unpacked size: 3.5 MB
lerna notice shasum:        be73aeddf214fb89836b4c8ad789332896cbbb1d
lerna notice integrity:     sha512-YPglfMjhWwJzh[...]EJnFjQXEM/LFA==
lerna notice total files:   281
lerna notice
lerna http fetch PUT 200 https://registry.npmjs.org/@pattern-lab%2fcore 9452ms
lerna success published @pattern-lab/cli 5.9.3
</details>

**Comment by bmuenzenmeyer** [comment]
pulled down the package and confirmed

![image](https://user-images.githubusercontent.com/298435/80808348-f7f20a00-8b84-11ea-9cd8-17ce76dad26d.png)

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
