### ISSUE TITLE
View All Nav Logic Needs to Guard Against Index Out of Bounds Errors

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#119]
Was using 0.9.0 today at work and https://github.com/pattern-lab/patternlab-node/blob/master/builder/patternlab.js#L370 is bombing on the last pattern.

**Comment by bmuenzenmeyer** [comment]
I think changing the line to 

`
if (!patternlab.patterns[i+1] || pattern.patternSubGroup !== patternlab.patterns[i + 1].patternSubGroup) {
` 

will fix it

**Comment by walmokrani** [comment]
Effectively, it solves the problem. Thank you
