### ISSUE TITLE
Cut off navigation when too many menu items

### ISSUE THREAD

**Issue by thethomic** [pattern-lab/patternlab-node#1205]
I am using Pattern Lab Node `v5.10.1` on `Windows`, with Node `v12.12.0`, using a `Gulp Mustache` Edition.

##### Expected Behavior
The Patternlab navigation should be fully usable when having many pages and beeing left aligned.

##### Actual Behavior
When the Patternlab navigation has many entries (27 of top and sublevel in my case), the content is cut off. The problem comes through the css rule: 
`.pl-is-active + .pl-js-acc-panel {
    max-height: calc(100vh - 2rem - 2rem);
}`

![image](https://user-images.githubusercontent.com/49404031/81609879-e7d5f800-93d8-11ea-9c25-9323910b7424.png)

##### Steps to Reproduce
Have a left sided patternlab navigation where the numer of top or second level entries exceeds the screen height.

**Comment by mfranzke** [comment]
@thethomic thanks for providing this finding. Do you have the possibility to even also support by providing a possible solution for that problem?

**Comment by thethomic** [comment]
@mfranzke Sure!
As far as I can assume, the max-height on the ´.pl-js-acc-panel´ is only used for translate-animation purposes when opening the subnavigation. But because the maxHeight is limited to `calc(100vh - 2rem - 2rem);` and the overflow is set to `hidden` contents will be cut when too many.

1. You can remove that maxHeight and ignore the translation-animation getting lost. 
(I do recommend to have an animation to show that the navigation changed, but the timing is currently set to 0.1s so you barely see it anyway.)
2. You can set the maxHeight to another virtually sufficient value like 300vh. 
For that case you need to enlarge the transition timing to eg. 0.5s to have a visible effect.
But even 300vh might one day be not enough and the maxHeight-animation is getting less perfect when sizing small vs. sizing large navigations (standard maxHeight animation problem). 
3. Do the calculations by JS (no recommendation)
4. I usually don't animate opening navigations by maxHeight but by slightly animating line height or vertical paddings or margins. The navigation then "pops in" but then still animates vertically what's enough for the eye to understand that it just appeared

**Comment by mfranzke** [comment]
@sghoweri I think UI Kit is mainly your part of knowledge here, isn‘t it?

**Comment by JosefBredereck** [comment]
The issue was released with v5.13.0 🎉
