### ISSUE TITLE
docs(attributes): modified related to latest implementations

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1207]
The attributes `state` and `tags` have been implemented and that for the docs need to get updated.

~~@bmuenzenmeyer as the `excludedTags` feature out of #844 #1079 has been implemented and released, where would you like to have the feature documented? The [`states`](https://patternlab.io/docs/using-pattern-states/) have an [exclusive docs page](https://patternlab.io/docs/using-pattern-states/), the attributes in general are [partly documented and mentioned on the documenting patterns docs page](https://patternlab.io/docs/documenting-patterns/).
If you even already do have this topic in your backlog, we could of course as well close this ticket with the current relevant changes.~~
As the `tags` currently mainly seem to be used for the `excludedTags` feature, I've just added a simple overview to [pattern documentation docs page](https://patternlab.io/docs/documenting-patterns/).

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
