### ISSUE TITLE
Implement hidden key in frontmatter

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1209]
I've been reconciling https://patternlab.io/docs/documenting-patterns/ with #1208 - I realized that we have support for parsing all these keys, yet core may not do something yet with all of them:

* `excludeFromStyleguide`
* **`hidden`**
* `links`
* `order`
* `state`
* `tags`
* `title`

This issue is limited to adding `hidden` functionality to https://github.com/pattern-lab/patternlab-node/blob/dev/packages/core/src/lib/ui_builder.js#L83-L90

**Comment by mfranzke** [comment]
> This issue is limited to adding `hidden` functionality to https://github.com/pattern-lab/patternlab-node/blob/dev/packages/core/src/lib/ui_builder.js#L83-L90

... and documenting it on https://patternlab.io/docs/hiding-patterns-in-the-navigation/

**Comment by mfranzke** [comment]
fight the bot
