### ISSUE TITLE
Pseudopatterns should support the ##-ordering system.

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#121]
https://github.com/pattern-lab/patternlab-node#pseudo-patterns

A user currently has to keep the base exactly the same when using pseudo-patterns, which can result in the variations occurring before the base pattern in the navigation.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer I think this was fixed in pr #152 and/or #157

**Comment by bmuenzenmeyer** [comment]
@e2tha-e could very well be - I had some similar hunches. I'll make sure to double check once I overcome this pesky cold and revert my environment from node 4...

**Comment by bmuenzenmeyer** [comment]
This is resolved too. Pretty obvious, considering we ship with an example.

Thanks for the issue clean up!
