### ISSUE TITLE
Partial build option in Node doesn't work

### ISSUE THREAD

**Issue by portfolioris** [pattern-lab/patternlab-node#1210]
I am using @pattern-lab/core `v5.10.1` on `Mac`, with Node `v12.16.1`, not using an Edition.

##### Expected Behavior
Setting the option `cleanPublic` to false via the build function should do a partial build.

##### Actual Behavior
The option is not used, so the function always runs a full build.

##### Steps to Reproduce
In a node or gulp script:

```
const pl = patternlabNode(config);
pl.build({
  cleanPublic: false,
});
```

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
