### ISSUE TITLE
chore(releasenotes): PL v5.10.1 contributors partly incorrect

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1215]
The release description on https://github.com/pattern-lab/patternlab-node/releases/tag/v5.10.1 includes some incorrect contributors mentions:

> Support for manual viewport size input & reintroduce resize key combinations #1167 (@mfranzke @sghoweri @bmuenzenmeyer)

credits me, but should actually mention @JosefBredereck and @bradfrost instead.

> Implement exclude tags feature. #1140 (drupal@pascalcrott.del @bmuenzenmeyer @sghoweri @mfranzke)

is missing @JosefBredereck

> fix(uikitworkshop): preventing cropping pattern parts #1174 #1175 (mfr@nzke.net @sghoweri)

> fix(docs): google lighthouse error - bg and text contrast ratio #1197 #1198 (mfr@nzke.net)

> chore(docs): simple typo #1194 (mfr@nzke.net)

> chore(links): prevent redirects both on internal as well as external URLs #1195 #1196 (mfr@nzke.net @bmuenzenmeyer)

> fix(docs): resolving broken links in new docs site #1192 #1193 (mfr@nzke.net @bmuenzenmeyer)

just asking to use my github username instead of emailaddress here, please.

**Comment by mfranzke** [comment]
Fight the bot

**Comment by JosefBredereck** [comment]
done

**Comment by mfranzke** [comment]
> done

Ehre wem Ehre gebührt ! ;-)
