### ISSUE TITLE
No css for pattern state "inprogress"

### ISSUE THREAD

**Issue by perriard** [pattern-lab/patternlab-node#1216]
I am using Pattern Lab Node `v5.7.0` on ` Mac `, with Node `v11.3.0`, using a ` Custom` Edition.

##### Expected Behavior
Pattern state "inprogress" produces a red dot

##### Actual Behavior
Pattern state "inprogress" produces a blue dot (defaults to the .pl-c-pattern-state styling - there is no --inprogress variant in the uikit _pattern-states.scss)

**Comment by mfranzke** [comment]
@perriard thanks a lot for that finding. I've even already provided a fix and recognized another inconsistency within the spec.

**Comment by sghoweri** [comment]
Issue was released with v5.11.1
