### ISSUE TITLE
Remove Travis integration in favor of Github Actions

### ISSUE THREAD

**Issue by ringods** [pattern-lab/patternlab-node#1241]
Hello @bmuenzenmeyer, @sghoweri, @JosefBredereck & other team members,

I have two reviewed and approved pull requests in the queue, but I can't merge them as Travis CI results do not seem to come in, even after days. Travis CI results seem to be a required check before merging.

Can we ditch Travis CI completely and make the Github Actions check the new required one?

Ringo

**Comment by sghoweri** [comment]
👀

**Comment by sghoweri** [comment]
👀

**Comment by JosefBredereck** [comment]
https://docs.github.com/en/github/administering-a-repository/about-required-status-checks
