### ISSUE TITLE
Using 'pattern' in url causes 404s

### ISSUE THREAD

**Issue by jkbyln** [pattern-lab/patternlab-node#125]
I set this up under a url like:
dev.url.com/patterns/

After generating a site under public and uploading it to my server, I was getting 404's on patterns when I click into one from the top navigation bar.

Turns out postmessage.js has a regex of
```
/patterns\/(.*)$/
```
defined on line 91, which was giving me issues because my url already contained the string 'patterns'.

Minor issue, but it would be nice if it matched something less generic, or took the possibility of /patterns/patterns/ into account.

**Comment by bmuenzenmeyer** [comment]
Hi @jkbyln thanks for reporting this - I will try to take a look at it this weekend but am up against some deadlines.

**Comment by bmuenzenmeyer** [comment]
The pathing and naming standards should be more robust - I believe this is something Dave has really striven for with PL v2

**Comment by jkbyln** [comment]
No problem! If I find a solution to this should I submit a pull request to patternlab-node or to patternlab-php?

**Comment by bmuenzenmeyer** [comment]
@jkbyln most likely patternlab-node

**Comment by scottnath** [comment]
@jkbyln I just ran into this too with a git repo with 'patterns' in the name causing out gh-pages version of the site to not work. Have you found the solution yet?

@bmuenzenmeyer has a solution for this been put into PL v2?

thanks!
scott

**Comment by bmuenzenmeyer** [comment]
I'd like to see a solution to this for PL node v1.0.

I am in the middle of some major reworking for v0.10 and then will attempt
to incorporate this bug fix soon after. Looking at this closer, this sounds
like an issue with the client frontend meaning it probably does apply to
pattern lab PHP as well. I will make sure to check that project too.

Either way, thanks for the continued support and interest in pattern lab
node!

**Comment by bmuenzenmeyer** [comment]
I'll stretch for this in v0.10.0 since it's causing angst for folks

**Comment by scottnath** [comment]
Morning @bmuenzenmeyer ,

Thanks for looking into this. I wasn't able to find the regex where this search/conversion is happening or I would have submitted a PR for you. Is this something happening in multiple places?

Thanks for looking into it.

Scott

**Comment by jkbyln** [comment]
@scottnath The line is right here:
https://github.com/pattern-lab/patternlab-node/blob/master/public/styleguide/js/postmessage.js#L91

I really suck at regex but maybe something like
```javascript
var re = /(.*)\/patterns(.*)patterns\/(.*)$/
```
would work as a temp fix if you have "patterns" in your url

**Comment by scottnath** [comment]
Hi @jkbyln, @bmuenzenmeyer 

I put in a pull request:
https://github.com/pattern-lab/patternlab-node/pull/129

This changes PLab in a number of files, but if a user does not add `baseurl` to the config.json, then there will be no changes to the way Pattern Lab Node works.

Happy to make any changes to the PR you'd like.

hope this helps,
Scott
