### ISSUE TITLE
npm create pattern-lab with edition twig throws an error and hangs

### ISSUE THREAD

**Issue by joville** [pattern-lab/patternlab-node#1257]
I am using Pattern Lab Node `v.5.13.1` on `Mac`, with Node `v14.9` (also in earlier node version vom v12 on), using the `Twig Edition`.

##### Expected Behavior

Clean install of the pattern-lab twig demo in any directory

##### Actual Behavior

Installation of the twig edition throws actually an error and hangs.

```
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig(node:66426) UnhandledPromiseRejectionWarning: Error: Cannot find module '@pattern-lab/edition-twig/package.json'
Require stack:
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/ask.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/cli-actions/init.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at resolveFileInPackage (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:10:18)
    at resolvePackageFolder (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:18:23)
    at resolveDirInPackage (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:26:20)
    at /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/install-edition.js:38:7
    at Generator.next (<anonymous>)
    at spwn (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js:75:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig
```

##### Steps to Reproduce

1) `npm create pattern-lab`
2) `? Please specify a directory for your Pattern Lab project. ./`
3) `? What templating language do you want to use with Pattern Lab? Twig (PHP)`
4) `? What initial patterns do you want included in your project? Twig (PHP) demo patterns (full demo website and patterns)`
5) `? Are you happy with your choices? (Hit enter for YES)? Yes`

**Comment by ringods** [comment]
@joville looking into the issue. Workaround you can use for the time being. Run this from within your new pattern-lab project folder:

```sh
$ npm init
$ npm install create-pattern-lab
$ npm create pattern-lab
```

**Comment by jerseycheese** [comment]
Reporting in that I also experience this in Node v12.18.3, in Pattern Lab Node v.5.13.1 on Mac.

**Comment by megclaypool** [comment]
I'm also experiencing this using Node v10.21.0 and v12.18.2 on macOS 10.15.6 

The workaround allowed me to install the node version of pattern lab. However, I'm running into further problems which may or may not be related:

I selected the PHP twig version and elected to install the sample patterns. However, when I `npm run build` and then `npm run serve` I get an empty lab with no visible patterns.  I checked the patternlab-config.json file, and it sure *looks* like the patterns are in the right place in the source folder... There are no error messages, just no patterns 🙁 

<img width="288" alt="Screen Shot 2020-09-22 at 09 38 21" src="https://user-images.githubusercontent.com/22053927/93911563-6744d380-fcb7-11ea-8b78-e60341b94e53.png">

<img width="1551" alt="Screen Shot 2020-09-22 at 09 36 24" src="https://user-images.githubusercontent.com/22053927/93911363-264cbf00-fcb7-11ea-8c3a-55f3a9328ab7.png">

**Comment by Leftere** [comment]
I'm on  node --version v12.18.3, on windows 10 and I get the same problem, 

(Use `node --trace-warnings ...` to show where the warning was created)
(node:66426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig

**Comment by mark-casias** [comment]
I am getting the same issue, in a few different versions of node (nvm versions v14.0.0, v13.9.0, v10.22.1, v10.9.0)

```? Are you happy with your choices? (Hit enter for YES)? Yes
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig(node:51441) UnhandledPromiseRejectionWarning: Error: Cannot find module '@pattern-lab/edition-twig/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at resolveFileInPackage (/Users/mark/.npm/_npx/51279/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:10:18)
    at resolvePackageFolder (/Users/mark/.npm/_npx/51279/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:18:23)
    at resolveDirInPackage (/Users/mark/.npm/_npx/51279/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:26:20)
    at /Users/mark/.npm/_npx/51279/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/install-edition.js:38:7
    at Generator.next (<anonymous>)
    at spwn (/Users/mark/.npm/_npx/51279/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js:75:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:51441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:51441) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig```

**Comment by mark-casias** [comment]
I have even tried manually installing `@pattern-lab/edition-twig` and `@pattern-lab/engine-twig-php` to no avail

**Comment by mark-casias** [comment]
I recant my previous statements. I wonder if there was just a tubes glitch because I went back and tried it today with no error on v12.10.0 and v13.9.0 with the following

```sh
$ mkdir fred
$ cd fred
$ npm init
$ npm install create-pattern-lab
$ npm create pattern-lab
```

**Comment by lhridley** [comment]
Oooh, waiting on the above MR (#1266 ) to get merged....working on some internal workflows that would be much easier if the "npm create" process could run successfully to completion. :)

**Comment by guenyoo** [comment]
I have the same issue as the original poster. npm create pattern-lab hands out a UnhandledPromiseRejectionWarning and the install is not progressing.

**Comment by mfranzke** [comment]
> I have the same issue as the original poster. npm create pattern-lab hands out a UnhandledPromiseRejectionWarning and the install is not progressing.

@guenyoo this is the topic we've discussed with #1412, isn't it ?

**Comment by guenyoo** [comment]
@mfranzke yes it was. I've commented here first but I've seen that this issue was closed so I created a new one.
