### ISSUE TITLE
Update engine-twig-php to latest @basalt/twig-renderer

### ISSUE THREAD

**Issue by jryanconklin** [pattern-lab/patternlab-node#1259]
I am using Pattern Lab Node `v5.13.1` on `Mac`, with Node `v12.18.0` `Custom` Edition.

##### Expected Behavior
* Twig Env uses 2 or better.

##### Actual Behavior
* Twig Env is 1.4.2 (basalt twig renderer needs update in package)

##### Steps to Reproduce
* Install latest `@pattern-lab/engine-twig-php`
* View Twig env version

**Comment by pcate-fls** [comment]
I'd love to see @basalt/twig-renderer updated as well. I'm using Patternlab with Drupal, and Drupal 9 uses Twig 2.
