### ISSUE TITLE
Saving scss file copy it to public

### ISSUE THREAD

**Issue by ghost** [pattern-lab/patternlab-node#1260]
I am using Pattern Lab Node `v5.13.1` on `Windows`, with Node `v12.18.4`, using a `Vanilla` Edition. I installed it with Handlebars and Handlebars base patterns.

##### Expected Behavior
Whenever I save one of the included .scss files nothing should happen. 

##### Actual Behavior
Whenever I save one of the included .scss files it gets copied to the public folder with the same folder structure.

##### Steps to Reproduce
Setup a pattern-lab node version with Handelbars and Handlebars base patterns. Remove the public folder and then save one of the scss files. The file will now have been copied to the public folder.

**Comment by mfranzke** [comment]
There seems to be an (regarding to my research) undocumented patternlab configuration entry, by which you could define filetypes that are potentially meant to get ignored (according to my interpretation of the internal variables name "assetsToIgnore").
The configuration entries key is `transformedAssetTypes`, like e.g. in your case:
``` json
{
  "cacheBust": true,
  "cleanPublic": true,
  "defaultPattern": "all",
  "defaultShowPatternInfo": false,
  "transformedAssetTypes": ["scss"],
}
```

@sghoweri / @JosefBredereck that's mainly my interpretation of what I've found in the code. Is that correct? Should I follow up by documenting that included functionality ?

**Comment by ghost** [comment]
Thank you @mfranzke that did it for me.

**Comment by JosefBredereck** [comment]
@mfranzke, as it seems to work, it would be great to have documentation for that.

**Comment by mfranzke** [comment]
> @mfranzke, as it seems to work, it would be great to have documentation for that.

Sure, I‘ll take care if that with #1261

**Comment by ghost** [comment]
A similar question so I ask it here. Is it possible to ignore specific folders also?

**Comment by mfranzke** [comment]
@raxion, to my impression this setting is mainly meant to exclude specific filetypes from being copied, compare to the code https://github.com/pattern-lab/patternlab-node/blob/dev/packages/core/src/lib/watchAssets.js#L32 and than from line 40.

**Comment by ghost** [comment]
I understand. I also realized that I can have another folder on the same level as js and css for other file types (scss and ts) that I don't want to be watched by Patternlab so that works for me.
