### ISSUE TITLE
Install fails on OpenSUSE LEAP 15,2

### ISSUE THREAD

**Issue by jimrome** [pattern-lab/patternlab-node#1271]
My install failed today. First I installed npm:
`zypper install npm
Loading repository data...
Reading installed packages...
'npm' not found in package names. Trying capabilities.
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  nodejs8 nodejs8-devel nodejs-common npm8

The following 2 recommended packages were automatically selected:
  nodejs8-devel npm8

4 new packages to install.
Overall download size: 9.1 MiB. Already cached: 0 B. After the operation, additional 40.2 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package nodejs-common-2.0-lp152.3.2.noarch                                           (1/4),   8.1 KiB (  230   B unpacked)
Retrieving: nodejs-common-2.0-lp152.3.2.noarch.rpm ............................................................................[done]
Retrieving package nodejs8-8.17.0-lp152.3.4.1.x86_64                                            (2/4),   5.3 MiB ( 20.0 MiB unpacked)
Retrieving: nodejs8-8.17.0-lp152.3.4.1.x86_64.rpm .................................................................[done (3.7 MiB/s)]
Retrieving package nodejs8-devel-8.17.0-lp152.3.4.1.x86_64                                      (3/4), 193.0 KiB (737.2 KiB unpacked)
Retrieving: nodejs8-devel-8.17.0-lp152.3.4.1.x86_64.rpm .......................................................................[done]
Retrieving package npm8-8.17.0-lp152.3.4.1.x86_64                                               (4/4),   3.7 MiB ( 19.4 MiB unpacked)
Retrieving: npm8-8.17.0-lp152.3.4.1.x86_64.rpm ....................................................................[done (3.0 MiB/s)]

Checking for file conflicts: ..................................................................................................[done]
(1/4) Installing: nodejs-common-2.0-lp152.3.2.noarch ..........................................................................[done]
(2/4) Installing: nodejs8-8.17.0-lp152.3.4.1.x86_64 ...........................................................................[done]
Additional rpm output:
update-alternatives: using /usr/bin/node8 to provide /usr/bin/node-default (node-default) in auto mode

(3/4) Installing: nodejs8-devel-8.17.0-lp152.3.4.1.x86_64 .....................................................................[done]
(4/4) Installing: npm8-8.17.0-lp152.3.4.1.x86_64 ..............................................................................[done]
Additional rpm output:
update-alternatives: using /usr/bin/npm8 to provide /usr/bin/npm-default (npm-default) in auto mode
update-alternatives: using /usr/bin/npx8 to provide /usr/bin/npx-default (npx-default) in auto mode`
-----------
Then I tried to create pattern-lab:
` #npm create pattern-lab
npx: installed 477 in 18.277s
? Please specify a directory for your Pattern Lab project. /usr/local/patternlab
? What templating language do you want to use with Pattern Lab? Twig (PHP)
? What initial patterns do you want included in your project? Twig (PHP) demo patterns (full demo website and patterns)
? Are you happy with your choices? (Hit enter for YES)? Yes
⠋ Setting up Pattern Lab in /usr/local/patternlab(node:21840) UnhandledPromiseRejectionWarning: Error: Cannot find module '/usr/local/patternlab/package.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at installEdition (/root/.npm/_npx/21788/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/install-edition.js:23:15)
    at /root/.npm/_npx/21788/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/cli-actions/init.js:53:29
    at Generator.next (<anonymous>)
    at spwn (/root/.npm/_npx/21788/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js:78:25)
    at <anonymous>
(node:21840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

##### Expected Behavior
Should install

**Comment by JosefBredereck** [comment]
Could you try to use a newer version of nodejs than nodejs8?

**Comment by jimrome** [comment]
Yes, npm14 and node js 14 worked. Thanks.
You might specify needed versions.

**Comment by mfranzke** [comment]
@jimrome I would suggest to use either exactly or at least version 12.12.0, as specified within https://github.com/pattern-lab/patternlab-node/blob/dev/.nvmrc
