### ISSUE TITLE
Ordering is not perfect yet

### ISSUE THREAD

**Issue by JosefBredereck** [pattern-lab/patternlab-node#1282]
From @coreylafferty on Gitter

If an ordered folder has a subfolder, it seems to break the MD ordering in odd ways. For example, if you put 'order: -1' in an MD file for a folder whose siblings have no defined order, it moves it to the top of the list as expected. However, if that folder has a subfolder, it reverts to alphabetical order and is no longer at the top. The only way I found to fix this was to explicitly define the order of it and all siblings and positive numbers. Here are the tests I ran and the results (all should have resulted in a menu that ordered the folders C, then A, then B, but only two of the tests did this).

```
Test 1:
_patterns/test/a/test.twig
_patterns/test/b/test.twig
_patterns/test/c/test.twig
_patterns/test/c/_c.md (order: -1)
RESULT IN MENU: C / A / B (PASS)

Test 2:
_patterns/test/a/test.twig
_patterns/test/b/test.twig
_patterns/test/c/test.twig
_patterns/test/c/_c.md (order: -1)
_patterns/test/c/subfolder/subfolder.twig
RESULT IN MENU: A / B / C (FAIL)

Test 3:
_patterns/test/a/test.twig
_patterns/test/a_a.md (order: 0)
_patterns/test/b/test.twig
_patterns/test/b/_b.md (order: 0)
_patterns/test/c/test.twig
_patterns/test/c/_c.md (order: -1)
_patterns/test/c/subfolder/subfolder.twig
RESULT IN MENU: A / B / C (FAIL)

Test 4:
_patterns/test/a/test.twig
_patterns/test/a_a.md (order: 2)
_patterns/test/b/test.twig
_patterns/test/b/_b.md (order: 2)
_patterns/test/c/test.twig
_patterns/test/c/_c.md (order: 1)
_patterns/test/c/subfolder/subfolder.twig
RESULT IN MENU: C / A / B  (PASS)
```

**Comment by JosefBredereck** [comment]
Another comment from Gitter:
`a sidenote; the order in the .md file does not work, if there's no title: in the file.`

**Comment by perriard** [comment]
I've done a bit of testing too.

**Desired outcome:**
Atoms
Molecules
Organisms
Templates
Pages
Subsites

**To get this to work, my .md files are numbered as follow;**
_atoms.md -1
_molecules.md -1
_organisms.md -1
_templates.md -1
_pages.md 0
_subsites.md 1

**If I order them from 0 to 5 the result is;**
Atoms
Subsites
Molecules
Organisms
Templates
Pages

**And from 1 to 6;**
Subsites
Atoms
Molecules
Organisms
Templates
Pages

**Comment by JosefBredereck** [comment]
I will have time to handle these issues on the weekend at the earliest.

@perriard the issue that patterns not getting sorted without the title attribute in the .md file I cannot reproduce. It works as expected.

These tests are good to implement for our automated testing.
