### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by chazchumley** [pattern-lab/patternlab-node#1286]
Simply changing from 5.13.3 to 5.14.0 for pattern lab core produces a TypeError.
Also ERROR: missing an essential file from /node_modules/@pattern-lab/uikit-workshop[object Object]. Pattern Lab won't work without this file.

**Comment by JosefBredereck** [comment]
Please have a look at https://github.com/pattern-lab/patternlab-node/releases/tag/v5.14.0

**Comment by chazchumley** [comment]
@JosefBredereck thank you, that did the trick.
