### ISSUE TITLE
Can't deeply nest patterns

### ISSUE THREAD

**Issue by BenSheridanEdwards** [pattern-lab/patternlab-node#1290]
I am using Pattern Lab core v5.13.1 on Mac, with Node v12.12.0, using a Grunt Edition.

As me and my team are building out pseudo pattern variations in PatternLab, I'm looking into how we can more deeply nest our patterns. 

Looking at the documentation I saw two ways of doing this: 

1. Adding `allPatternsAreDeeplyNested": true` to our patternlab-config.json. Then creating a new folder and putting the pattern mustache and markdown files inside:

![Screenshot 2021-02-19 at 13 47 48](https://user-images.githubusercontent.com/42347559/108512531-44940680-72b9-11eb-9b04-54bd677c3e67.png)
![Screenshot 2021-02-19 at 13 55 26](https://user-images.githubusercontent.com/42347559/108513177-21b62200-72ba-11eb-80d7-a608e9ebfaef.png)

But when I start up PatternLab, my button variants sit on the same level under button/:

<img width="197" alt="Screenshot 2021-02-19 at 13 47 39" src="https://user-images.githubusercontent.com/42347559/108512583-583f6d00-72b9-11eb-8f7c-d047615753f8.png">

2. The second way I learned about involved adding `deeplyNested: true` as an attribute in the markdown file of the pattern to be deeply nested.

![Screenshot 2021-02-19 at 13 52 46](https://user-images.githubusercontent.com/42347559/108512895-c08e4e80-72b9-11eb-8460-1cc6a32ff649.png)

But this didn't change the output: 

<img width="197" alt="Screenshot 2021-02-19 at 13 53 53" src="https://user-images.githubusercontent.com/42347559/108513025-e9aedf00-72b9-11eb-9e51-094f5b9d77c6.png">

What am I doing wrong here? Open to any and all suggestions. Thanks in advance for the help!

**Comment by JosefBredereck** [comment]
Hello, thanks for your question.

What do you expect the menu to look like?
We only have two levels of depth.
-> atoms
--> Buttons
----> ButtonComponent1
----> ButtonComponent2
----> ButtonComponent3

Suppose you go to the documentation and read [deeper-nesting](https://patternlab.io/docs/overview-of-patterns/#heading-deeper-nesting) carefully again. It says it's to structure your patterns a bit more on the file system. That does not influence the UI.

**Comment by BenSheridanEdwards** [comment]
@JosefBredereck so can I influence the UI at all for this or is that not yet possible? Apologies for my misunderstanding.

**Comment by JosefBredereck** [comment]
Yes, It is not possible yet.
