### ISSUE TITLE
Configure Web Server to run on HTTPS

### ISSUE THREAD

**Issue by StfBauer** [pattern-lab/patternlab-node#1291]
I am using Pattern Lab Node `v5.14.0` on `Mac`, with Node `v13.14.0`, using a `Gulp`.

##### Expected Behavior
I want to run `pl:server` over HTTPS but cannot find any documentation how I can configure it. The reason for this is I use the CSS styles outputted by the style guide directly as a CSS library for other components.

Those will then run always on an HTTPS we server. For faster development I directly import the output of the web server using a regular CSS import.

##### Actual Behavior
Couldn't find any documentation how to add SSL certificates to the local running web server. Alternatively I could run in a custom gulp task a secondary web server that run on another port using SSL on the public folder.

It would be nice if this would be an option directly inside of pattern-lab.

##### Steps to Reproduce
N/A

**Comment by mfranzke** [comment]
The current documentation doesn't mention anything about this actually (which probably proves some necessary rework), but the documentation of [live-server](https://github.com/pattern-lab/live-server), the underlying server used by patternlab, includes some information on HTTPS: https://github.com/pattern-lab/live-server#https
