### ISSUE TITLE
Component variants display as YML

### ISSUE THREAD

**Issue by mejiaj** [pattern-lab/patternlab-node#1308]
Hello, we're looking to use patternlab with the US Web Design System. When running `npm run pl:build` and serving that via browser-sync we're seeing variants displayed as YML instead of the actual component variant. You can see it in action on our [alert component](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-library--develop-no-patch/?p=viewall-components-usa-alert).

Making [this change](https://gitter.im/pattern-lab/node?at=600c7cb597132e2480fcafe5) proposed by Adrian Richardson in gitter seems to work. Any thoughts on including it codebase? Any advice would be appreciated.

I am using `@pattern-lab/core v5.14.1` and `@pattern-lab/engine-twig v5.14.0` on `Linux`, with Node `v14.16.0`.  You can view the variants in [`src/patterns/components/usa-alert/`](https://github.com/uswds/uswds/tree/jm-library--develop-no-patch/src/patterns/components/usa-alert)

##### Expected Behavior
Variants display properly
![image](https://user-images.githubusercontent.com/3385219/113050913-0668ed00-916b-11eb-9820-93361828372f.png)

##### Actual Behavior
YML being shown
![image](https://user-images.githubusercontent.com/3385219/113050986-18e32680-916b-11eb-96bc-b45b117b0141.png)

##### Steps to Reproduce
- Clone https://github.com/uswds/uswds/tree/jm-library--develop-no-patch
- Run `npm install` and `npm start`

**Comment by mfranzke** [comment]
@mejiaj first of all welcome to the platform, great decision !

The fix [suggested by AdrianRichardson](https://gitter.im/pattern-lab/node?at=600c7cb597132e2480fcafe5) looks very promising to me at least, I've opened a change request for others to review that solution.
