### ISSUE TITLE
Error parsing pseudo-pattern emits only a warning

### ISSUE THREAD

**Issue by andriokha** [pattern-lab/patternlab-node#1315]
I am using Pattern Lab Node `v5.13.2` on `Linux`, with Node `v14.16.0`, using a `Custom` Edition.

##### Expected Behavior

For reasons (#1309) I currently have the log level set to show errors only. I accidentally introduced some invalid yaml to a pseudo-pattern, which I'd expect to cause an error to be issued.

##### Actual Behavior

Nothing is output when the log level's set to `error`.
https://github.com/pattern-lab/patternlab-node/blob/6120e0026c8a514565858089eb72b68664ead077/packages/core/src/lib/pseudopattern_hunter.js#L47-L60

##### Steps to Reproduce

1. Set the log level to `error`.
1. Create a pseudo-pattern, and add the following yaml:
   ```yaml
   make_error: |
     one
    two
   ```
1. Try to build patternlab.

**Comment by mfranzke** [comment]
Thanks again for providing your feedback with a great summary and helpful additional insights.

I think that we should align the different warnings and errors in the system regarding their levels, and will provide a merge request for that.
