### ISSUE TITLE
Is Pattern Lab dead?

### ISSUE THREAD

**Issue by JosefBredereck** [pattern-lab/patternlab-node#1316]
Hello, fellow community,

I'm now struggling with this question for quite some time. But was afraid to ask.
We still have a quite active community when I go by the messages that we get on Gitter, BUT I have a bad feeling that the maintaining developers are not present anymore. Thanks to @mfranzke, some help is still available and recent also some improvements to our codebase.

The problems I experience are
- that no one left that could explain what the intention behind some basic stuff was
- how those engines work and should work (foremost twig and twing knowledge lacks)
- code reviews often stay behind
- I personally have no Idea how and if we pay for our preview pages or our website.
And so on...

So here Is my question. 
**Is Pattern Lab dead?**

Maybe some other aspects.
Do we need a fresh new team?
Do we need a core update to a fresh technology like Typescript?
Can we save the project and get a new view of it?

**Comment by mfranzke** [comment]
that‘s an important topic, thanks for bringing it up. And thanks a lot to you as well for your great work!

Quick answer to your main question: no, it‘s hopefully not dead, especially as there‘s no alternative, and we have a great and stable solution. Of course there are problems and you‘re naming some of the relevant ones.
I‘m working in this industry for more then 20 years now and have even participated in developing a similiar tool to patternlab around 2008 - but what has been achieved with patternlab is just amazing, an important and easy tool especially for newbies, second to none for PHP / Drupal development and still better than any alternatives on the market.

So we‘ll better need to ensure a bright and healthy future, e.g. by enabling and motivating for further contribution.

Let me think about those aspects and come up with a reply asap.
