### ISSUE TITLE
Restructure filesystem to better align concerns and support upgrades

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#133]
Basically https://github.com/pattern-lab/patternlab-php/releases/tag/v0.7.0
* Move _patternlab-files out of source to make upgrading easier for users
* Restructure filesystem to allow for metapatterns
* Make a clearer distinction between source and pl code.
* [x] [
 Edit New issue
meta patterns missing?](https://github.com/pattern-lab/patternlab-node/issues/169)

**UPDATE**
I've mapped this work [on the wiki](https://github.com/pattern-lab/patternlab-node/wiki/Proposed-filesystem-restructure)

**Comment by Xiphe** [comment]
Do you have any plans on how you want to do this?

I've lately put some time into [isolating grunt tooling from our projects](https://github.com/Jimdo/grunt-angular-toolbox).
We achieve that by having all tools in one single npm package that is then loaded and configured in a projects gruntfile. 
I feel that this would be a great way, for this project to maintain upgradability and prevent monkey-patching.

Let me know how you think about this :)

**Comment by e2tha-e** [comment]
Excited for this to happen!

**Comment by bmuenzenmeyer** [comment]
Hi all 

My current scope for this is to clarify the source code which I'd expect a user to alter from the code necessary to make the pattern-lab style guide frontend run. PL-PHP has restructured `source/_patternlab-files/*` out of source for a long time now - and this would be step one. 

I do want to look at the link you provided more and generally create a more future-friendly file structure that is approachable to newcomers.

Stay tuned

**Comment by Xiphe** [comment]
Nice, feel free to contact me if you want to chat :)

Just as a feedback on this topic:
We already have a working design system with our own structure and a bunch of grunt tooling. We would have loved to use pattern-lab as a frontend and follow the suggested structures - Sadly the merge of this project into ours would have been very complicated and we would have lost/rebuild lots of our own tooling. 
It would have been easier if this where a plain npm tool or grunt/gulp task that one can just use in any project. Not saying that it needs to be like this, i can totally see the benefits of having a project scaffold that just works, this is just the story of my team :)

**Comment by Xiphe** [comment]
While re-reading i just figured, that the moving of `_patternlab-files` would totally enable this. These files can then live in their own project that has build tools and everything one can imagine while the pattern-lab project is just the frontend.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer @Xiphe Has there been any development on this? My current work requires this separation of concerns so I'll start on this myself if there's nothing already in development.

**Comment by bmuenzenmeyer** [comment]
No there isn't yet. the roadmap places this after v0.14.0 which has the last big feature gap https://github.com/pattern-lab/patternlab-node/issues/95

I am slow to get to this. Would you want to take a shot at it?

**Comment by bmuenzenmeyer** [comment]
@e2tha-e I was thinking more about this versue #95 I'd hate for us to have a bunch of conflicts due to a giant file reorg while working through this feature. Though I think this can probably get shoe-horned into pattern assembler without too much trouble... 

You've been a workhorse of late, just trying to figure out how best to coordinate our time. Thoughts?

**Comment by bmuenzenmeyer** [comment]
Also sorry for comment spam but I very much intend to include:

* https://github.com/pattern-lab/starterkit-mustache-default
* https://github.com/pattern-lab/styleguidekit-assets-default

both of these repo's into patternlab node as part of this solution and therefore might want to tackle all this myself.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer I haven't begun any work on this, so it would probably be better for you to come up with an approach that accommodates the code in those other repos. I can monkey-patch things like js and css includes in the header and footer for the time being, but it won't be sustainable for very long.

**Comment by Xiphe** [comment]
We're not using patternlab-node right now, so no progress from my site.

**Comment by bmuenzenmeyer** [comment]
Starting this  today
