### ISSUE TITLE
Hello, I'm using the twig version, I can't add my .js

### ISSUE THREAD

**Issue by Recko91** [pattern-lab/patternlab-node#1330]
I am using Pattern Lab Node on `Windows`, with Node `v14.17.0`, using a `Twig` edition.

##### Expected behaviour
I'm looking to integrate my javascript file "moteur.js", so I can actually use it on my forms input.

##### Actual behaviour
When I fill in the "/source/_meta/_foot.twig" file with "<script src="../../public/js/moteur.js"> </script>"
I get this error message in the console
"Uncaught SyntaxError: Unexpected token '<'" in my render

**Comment by mfranzke** [comment]
@Recko91, is there a chance to have a look at your codebase, e.g. is it on github? Elsewhere it would be hard to give you support on this topic.

**Comment by Recko91** [comment]
Hi, thanks for your answer. 
Here is the github of the project: 

[https://github.com/Recko91/patternlabatom](url)

**Comment by mfranzke** [comment]
@Recko91 this is mainly about the reference URL - you don't need to include the public folder there, as the files are even already being served from that one. I've created a merge request within your repo and tested it out via https://www.gitpod.io/#https://github.com/Recko91/patternlabatom/

**Comment by Recko91** [comment]
Thank you for your quick and valuable help!
