### ISSUE TITLE
Problem npm install on MAC osx M1

### ISSUE THREAD

**Issue by Recko91** [pattern-lab/patternlab-node#1332]
I am using Pattern Lab on `Mac` M1, with Node `v16.3.0`, using a `Twig` Edition.

I am trying to run a patternlab on a Mac osx 2020. When I want to do an npm install, this error occurs

[2021-06-17T10_07_06_298Z-debug.log](https://github.com/pattern-lab/patternlab-node/files/6669518/2021-06-17T10_07_06_298Z-debug.log)

Need help

**Comment by mfranzke** [comment]
@Recko91 this looks to me like a problem with Node16 (probably especially as we're still on [node-sass](https://npmjs.com/node-sass) 5, which doesn't seem to support Node 16 already).

Do you have the chance to test Node 15 on your environment as well (probably e.g. via [NVM](https://github.com/nvm-sh/nvm))?

Nevertheless we should be able to provide an update to [node-sass](https://npmjs.com/node-sass) 6 quite quick, which should solve this problem anyhow.

**Comment by Recko91** [comment]
With node 15 it works thank you for your feedback !
