### ISSUE TITLE
transformedAssetTypes is ignored

### ISSUE THREAD

**Issue by renestalder** [pattern-lab/patternlab-node#1339]
I am using Pattern Lab Node `v5.15.0` on `Linux`, with Node `v16`, using a `Twig` Edition.

##### Expected Behavior

When using a preprocessor like PostCSS to process CSS files, you want to deactivate the copy task for CSS. To do this, based on the manual, I would set following property in my pattern lab configuration:

```json
{
  "transformedAssetTypes": ["css", "js"]
}
```

Now building pattern lab, the public css folder set in `paths.public.css` should not contain any CSS files.

##### Actual Behavior

`transformedAssetTypes` seems to ignore the type "css". It copies all the CSS files as configured in `paths.source.css` to `paths.public.css`.

As the preprocessor might be faster in compliling, Pattern Lab is also gonna overwrite any previously compiled CSS.

Actually, after testing further, it seems that setting is not applied any file type. I tested it with `.scss` as file type by setting `transformedAssetTypes` to `["scss"]` and file is still being copied despite the setting.

##### Steps to Reproduce

1. Configure paths for CSS in `paths.source.css` and `paths.public.css`.
2. Add a CSS file to the source path
3. Set the `transformedAssetTypes` to `["css"]`.
3. Run `patternlab build --config ./patternlab-config.json`

**Comment by renestalder** [comment]
Is it possible it is only applied in the `watch` mode and not when building? The only reference for `transformedAssetTypes` I find in the code is in `watchAssets.js`. 

https://github.com/pattern-lab/patternlab-node/blob/639801addbc95648bbb6b992944f332a5a0f4d2c/packages/core/src/lib/watchAssets.js

**Comment by mfranzke** [comment]
@renestalder thanks for reporting this topic. It even also seems to me that `transformedAssetTypes` is only being taken into account on `watch`ing the files, but not during `build`.

@JosefBredereck could you think of any valid reason for that? I would expect that the `transformedAssetTypes` is both necessary during watch as well as build, or am I missing something here (is the output of files probably differing intentionally)?

**Comment by JosefBredereck** [comment]
Phew, I don't know if this is the correct option. We have some old documentation here in the pattern lab wiki which does not match the [patternlab.io](https://patternlab.io/) website.

In my opinion, the functionality should do the same in watch and build mode, so that you don't have different results.

**Comment by JosefBredereck** [comment]
Somewhere in the `copier.js` at `transform_paths`, we could add functionality to ignore specific paths, or in `copyFile.js`, we could add the option to ignore with `transformedAssetTypes`. I currently do not know If `recursive-copy` supports ignoring files or if we have to build something new here.

**Comment by mfranzke** [comment]
I think that I'm nearly done with implementing a solution for this one.
