### ISSUE TITLE
Could not watch changes on Patterns

### ISSUE THREAD

**Issue by epsilon-skolanthasamy** [pattern-lab/patternlab-node#1340]
I am using Pattern Lab Node `v5.15.0` on `Windows`, with Node `v14.16.0`, using a `Gulp` Edition.

##### Expected Behavior
I should be able to watch for the mustache file changes

##### Actual Behavior
Since I have upgraded, the below path is not there anymore.
`var engines = require('./node_modules/patternlab-node/core/lib/pattern_engines');
  return engines.getSupportedFileExtensions();`

**Comment by mfranzke** [comment]
@epsilon-skolanthasamy, thanks a lot for your feedback. Sadly the problem you're reporting is not totally clear to me, so do you have the source code within a publicly available or in a public repository, or at least are you able to provide the relevant parts like e.g. the package.json contents for us to reproduce on your exact setup?

I've mainly recognized that you're referring to a file, which is most likely the one located under the following path, probably this even already helps on your problem:
`node_modules/@pattern-lab/core/src/lib/pattern_engines.js`
The folder structure seems to have been changed with commit 4d9c243624cb15fe929865c4793dc9078e55503b on February, 23 2018

**Comment by epsilon-skolanthasamy** [comment]
Thank you for the URL, i updated that and it is working fine now. I basically want to add utility function for watching changes pattern.
