### ISSUE TITLE
'npm start' does not work after installation (node-handlebars): missing start script

### ISSUE THREAD

**Issue by AndyZH76** [pattern-lab/patternlab-node#1343]
I am using Pattern Lab Node `v5.X.X` on `Mac`, with Node `v14.X`.

##### Expected Behavior
Install that is working with handlebars.

##### Actual Behavior
After installation only the twig-edition can be startet by npm start.
The node-edition (handlebars) cannot be startet by npm start (npm error: missing start script).

##### Steps to Reproduce
Try to install with handlebars and handlebars starter-kit...

**Comment by AndyZH76** [comment]
Thx! 👍

**Comment by mfranzke** [comment]
@AndyZH76 thanks to you for bringing up this topic.
