### ISSUE TITLE
Documentation: updating regarding template language

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1353]
##### Expected Behavior
The documentation still mentions a lot of files with the `.mustache` file ending, and the mustache template language as well.

##### Actual Behavior
As we've switched to handlebars templates as the successor of mustache, I would expect to only have `.hbs` instead of `.mustache` and other mentions of mustache as well.

**Comment by jaishankar02** [comment]
I would like to work on this issue. But as this is my first time in open source can you please help me and elaborate what I have to do

**Comment by jaishankar02** [comment]
I have done some changes can you please tell me whether its right or wrong.  screenshot is attached below for your reference
![Screenshot 2021-12-23 134151](https://user-images.githubusercontent.com/92317436/147209960-d157d615-4f6c-40cf-a112-af13c4bc49d0.jpg)

**Comment by mfranzke** [comment]
@jaishankar02 thanks a lot for your contribution.

This ticket is mainly about changing the documentation (in `/packages/docs`) from the previous template language mustache and its file ending to its successor handlebars (and its file ending `.hbs`).

So it most likely doesn't involve any changes in the other packages or the template files themselves.

I can't clearly identify from the screenshot you've provided, but you've seemed to have duplicated the general template files for header and footer – this isn't necessary, as those are even already in the new handlebars format. So in other words, the documentation in this repository needs to get changed to accommodate the changes that even already happened in the code (base).

**Comment by mfranzke** [comment]
kind of a duplicate to https://github.com/pattern-lab/patternlab-node/issues/1239
