### ISSUE TITLE
Theme support?

### ISSUE THREAD

**Issue by ivanmayes** [pattern-lab/patternlab-node#136]
Would be awesome if there were a way to build and share themes for the style guide with people.  I LOVE patternlab and it makes our life so much easier, but often we have to share this style guide with a client or otherwise non-techy person.  It would be awesome to be able to build something like this: http://sfdc-styleguide.herokuapp.com/?id=isv (which we do currently) without having to compromise some of the potential templating issues of overwriting core files.

It would also be interesting to be able to share out these themes as a way to promote different looks for PL and getting the community involved in creating some different looks that people could opt in for.

Not sure the best way to implement this, if its like wordpress where PL would look in a custom folder for files and default back to core files if they dont exist, or if you just copy the entire folder into a theme and point PL to access those instead of core, but I thought it would be interesting!

**Comment by bmuenzenmeyer** [comment]
Hi @ivanmayes 

I really like this idea and am likewise using a custom skin or theme of pattern lab other than what is shipped. 

Custom CSS is a pretty simple problem to solve, but drastically altering the 'pattern lab chrome' like the ish-controls and all of its subsequent javascript will be a bigger challenge in my opinion. I want to add a well-thought out solution to a [post v1 world](https://github.com/pattern-lab/patternlab-node/issues/134) and would love if you and the community could help me make a good decision with this.

**Comment by bradfrost** [comment]
@ivanmayes @bmuenzenmeyer yep, the way Pattern Lab 2 is being set up creates a clear separation between the Pattern Lab chrome, the patterns inside it, and the pattern engine that runs it. 

For the most part this separation is already there, but we're trying to make it even more explicit.

**Comment by velvetlicious** [comment]
Hi everyone!
I'm just getting ready to user patternlab on a project, and I don't know where to customize the theme/skin.
@bmuenzenmeyer could you share what are you currently using?
@ivanmayes I also loved that styleguide! it's so pretty <3

**Comment by bmuenzenmeyer** [comment]
@velvetlicious I've had it on my todo list to extract my customization into a repo for others to see. It's not terribly different from the default, except it has a side navigation. When I get to this I will update this thread.

**Comment by gael-boyenval** [comment]
+ 1 on this ! 
a simple (and clean) way to override PL CSS from configuration file would be great ! 

```json
     // in patternlab config file
    "patternlab-css-customize" = "../public/patternlab.css"
```
for now i use the ``_meta/00-head.mustache``. and that seem not very clean to me.

**Comment by bmuenzenmeyer** [comment]
The advent of plugins has made this irrelevant. I am working on a theme plugin of sorts, and motivated individuals can and have completely customized the PL UI.
