### ISSUE TITLE
Hiding pattern sub groups ignored 

### ISSUE THREAD

**Issue by renestalder** [pattern-lab/patternlab-node#1366]
I am using Pattern Lab Node `v5.15.1` on `Linux`, with Node `v16`, using a `Twig` Edition.

##### Expected Behavior

If I add `components/buttons/_buttons.md` with the content:

```
---
hidden: true
---
```

That the "Buttons" group does not appear in the output of the documentation.

Relevant part of the patternlab documentation: https://patternlab.io/docs/hiding-patterns-in-the-navigation/#heading-hiding-pattern-sub-groups

##### Actual Behavior

The option seems to be ignored for a whole folder. At least for the Twig edition.

Hiding single files works as documented.

##### Steps to Reproduce

1. Create a sub group structure e.g. "components/buttons".
2. Add a test twig file to that folder, e.g. "components/buttons/test.twig" with some content.
3. This appears in the documentation under the menu "components" as "buttons" then "test".
4. Now add `components/buttons/_buttons.md` with the content above (as in the expected behaviour.
5. The components -> buttons group should now no longer appear in the documentation menu. For me, it still does

Simplified example.

**Comment by mfranzke** [comment]
Quick question in return (just curious about the scope of the problem): as you‘re mentioning twig here, have you even also already tried out the handlebars edition and it works correctly in that one?

**Comment by renestalder** [comment]
@mfranzke I have quickly set up a project with handlebars and the demo project, added a `_forms.md` to the atoms folder with the hidden attribute set, and unless I did something wrong, it also seems to fail in a handlebars project. The forms menu with it's sub components still appears in the UI.

**Comment by mfranzke** [comment]
@renestalder okay, thanks a lot for testing this out as well.

**Comment by renestalder** [comment]
Also clarification: It clearly works on the first level e.g. `_patterns/_atoms/_atoms.md`. Just not for any subgroups after that.

**Comment by JosefBredereck** [comment]
Thanks for the analysis and the very well-written issue.
I created a PR for this topic; sorry for the inconvenience. 🍺
