### ISSUE TITLE
patternlab-config not picking up on helpers.js file

### ISSUE THREAD

**Issue by ultraloveninja** [pattern-lab/patternlab-node#1369]
I am using Pattern Lab Node `v5.15.2` on `Mac`, with Node `v17.0.1`, using the handlebars Edition.

I'm migrating an older project that was using some custom helpers for class names. 

For example in a `radio.hbs` file:

```
<input {{ class ": error" }} type="radio" {{#if required}}required{{/if}} />
```
I was reading through the docs and I had put the helper js file in the `helpers` folder and named it `helpers.js`.

In the config, I updated this to point to the helper file directly:

```
  "engines": {
    "handlebars": {
      "extend": "helpers/helpers.js"
    }
  }
```
Then when I run  `npm run start`

It starts to load but then throws this error:

```
npm run pl:serve


> pl-test@1.0.0 pl:serve
> patternlab serve --config ./patternlab-config.json

⊙ patternlab → serve: Serving your files …
Pattern Lab Node v5.15.2
Pattern Engine handlebars: require(...) is not a function
Pattern Engine mustache: good to go
Pattern Engine handlebars: already loaded, skipping.
Pattern Engine mustache: already loaded, skipping.
Error: Missing helper: "class"
    at Object.<anonymous> (~/code/pl-test/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at Object.wrapper (~/code/pl-test/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (~/code/pl-test/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:143)
    at main (~/code/pl-test/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (~/code/pl-test/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (~/code/pl-test/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at Object.renderPattern (~/code/pl-test/node_modules/@pattern-lab/engine-handlebars/lib/engine_handlebars.js:69:28)
    at Pattern.render (~/code/pl-test/node_modules/@pattern-lab/core/src/lib/object_factory.js:210:35)
    at module.exports (~/code/pl-test/node_modules/@pattern-lab/core/src/lib/render.js:13:18)
    at ~/code/pl-test/node_modules/@pattern-lab/core/src/lib/compose.js:91:37 {
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  endLineNumber: undefined,
  number: undefined
}
Error rendering patterns
```
 To make sure I wasn't missing something, I tested out editing the default configs for the theme as such:

```
  "theme": {
    "color": "dark",
    "density": "compact",
    "layout": "horizontal"
  }
```

This also has no effect when I re-run the `npm run start` as it keeps defaulting to the light theme and vertical layout.

So, I'm not sure if there is something that I'm missing, or if it's not loading in the config file correctly.

Here's the custom helper I'm trying to load as well:

```
module.exports.register = function(Handlebars, options, params) {

  /**
   * Helper name
   * @param  {[type]} str [description]
   * @return {[type]}     [description]
   */
  Handlebars.registerHelper('class', function(str) {
    var count = 0;
    var out = 'class="';
    var classSplit, prop, className;
    var classes = str.split(' ');
    var mustacheRegex = /{{([^}]+)}}/;

    classes.forEach(function(){
      classSplit = classes[count].split(':');
      prop = classSplit[0];
      className = classSplit[1];

      // check if classname has mustache tag in it
      if (typeof className !== 'undefined' && className.match(mustacheRegex)) {
        var dynamicProp = className.match(mustacheRegex)[1];
        className = className.replace(mustacheRegex, this[dynamicProp]);
      }

      if (prop === '' || !!this[prop]) {
        if (count > 0) {
          // add preceding space
          out = out + ' ';
        }
        out = out + (className || prop);
      }
      count++
    }, this);

    out = out + '"';

    return new Handlebars.SafeString(out);
  });

};
```

Let me know if there is anything else that I can provide to test. Thanks!

**Comment by mfranzke** [comment]
I've most likely found the solution:
Removing the `register` method at the first line of your helper file (or in other words, replacing `module.exports.register = function(Handlebars, options, params) {` by `module.exports = function(Handlebars, options, params) {`) let's the error message disappear, which is even also the adaption of the syntax in the example `helpers/test.js` file.

Regarding the other aspects:
- You might be more flexible to stick with the default declaration within the `patternlab-config.json` file, in case that you'll set up further helpers in the future (but that's just my personal opinion):
  ```
  "engines": {
      "handlebars": {
        "extend": "helpers/*.js"
      }
    }
  ```
  And as well name your helper file like the helper method itself: `helpers/class.js`
- Regarding the config settings on `theme` within the `patternlab-config.json` file: Those are stored as defaults within the browsers local cache after first opening pattern lab, so any changes in this specific section might not appear right away without clearing this browsers cache first. A simpler way to try this out as you did it might be the `"logLevel": "info",` setting, changing it to "debug" and seeing an enhanced logging on the console; this would as well prevent any interference from the browser, but still make it clear to you that your changes have been applied to a restarted pattern lab.
