### ISSUE TITLE
Installation is hanging at ⊙ patternlab → Installing edition: @pattern-lab/edition-node

### ISSUE THREAD

**Issue by guenyoo** [pattern-lab/patternlab-node#1412]
I am using Pattern Lab Node `v5.15.5` on `Mac`, with Node `v14.18.0`, using a `Vanilla` Edition.

##### Expected Behavior
I can install and use patternlab with npm create pattern-lab

##### Actual Behavior
Installation throws Unhandled promise rejection error

##### Steps to Reproduce
$ npm create pattern-lab
? Please specify a directory for your Pattern Lab project. ./
? What templating language do you want to use with Pattern Lab? Handlebars
? What initial patterns do you want included in your project? Handlebars base patterns (some basic patterns to get started with)
? Are you happy with your choices? (Hit enter for YES)? Yes
⠋ Setting up Pattern Lab in ./(node:58897) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: yarn add @pattern-lab/edition-node
spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:58897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:58897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ ⊙ patternlab → Installing edition: @pattern-lab/edition-node

Nothing happens after that.

**Comment by mfranzke** [comment]
@guenyoo thanks a lot for reporting this.

Sadly I cannot install Node version 14.18.0 via NVM ("tar: Error opening archive: Unrecognized archive format" and "Binary download failed, trying source."), but have tried with version 14.18.3, and cannot reproduce the problem (even also on a Mac, M1 processor):

<img width="909" alt="image" src="https://user-images.githubusercontent.com/787658/150837865-2bb3bedb-c638-4901-a92c-25a88c97db18.png">

Do you have the chance to try with 14.18.3 as well? Probably the 14.18.0 relates to this problem.

**Comment by guenyoo** [comment]
@mfranzke Thanks for checking - I'll try installing with 14.18.3 and will get back to you.

**Comment by guenyoo** [comment]
@mfranzke I can onfirm that the installation works with node 14.18.3
