### ISSUE TITLE
Add allow-downloads to iframe sandbox options

### ISSUE THREAD

**Issue by eWert-Online** [pattern-lab/patternlab-node#1414]
I am using Pattern Lab Node `v5.15.0` on `Mac`, with Node `v16`, using a `Vanilla` Edition.

Is there a specific reason the [iframe sandbox](https://github.com/pattern-lab/patternlab-node/blob/6fa630e2353ed68295550e59c31148269f3b7cd0/packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.js#L416) does not include the option `allow-downloads`?

Would you add it, if I submit a PR?

**Comment by mfranzke** [comment]
Hi @eWert-Online,

thanks a lot for your contribution.

I've just checked the implementation on https://patternlab-handlebars-preview.netlify.app/?p=all and realized that another option **might be to remove the `sandbox` attribute in total**. The current configuration is kind of "pseudo-security", compare to the good explanation:
> When the embedded document has the same origin as the embedding page, it is **strongly discouraged** to use both `allow-scripts` and `allow-same-origin`, as that lets the embedded document remove the `sandbox` attribute — making it no more secure than not using the `sandbox` attribute at all.

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

The declarations have been in there [for quite a while now](https://github.com/pattern-lab/patternlab-node/commit/c56ef6e4ceb6f45f4efb7d01b1e084f4fd76ea48#diff-e268076a132d9c5a69fb4379ef3cbaa795cdfd9de6c700ffacc115c2585a6583R46) (partly moved again through code restructuring) and only [got enhanced once by the `allow-modals` config entry](https://github.com/pattern-lab/patternlab-node/commit/d32d912f62fdb1d9b30b833bc840dc8143d94e36#diff-2e714224370b9110c9c613bc0325800f83fb5469544124d68358d391771a20a7R7).
I can't identify a reason why we would need this declaration as we're mainly using the iframe to display same origin pages out of the same build.

@JosefBredereck: What do you think ?

**Comment by JosefBredereck** [comment]
@mfranzke, I think this is still related to the IE support we had in the past. From my point of view, there is nothing that speaks against changing that.

**Comment by eWert-Online** [comment]
Do the changes have to be made in both of the following files?

https://github.com/pattern-lab/styleguidekit-assets-default/blob/develop/src/html/partials/iframe.html#L7

https://github.com/pattern-lab/patternlab-node/blob/dev/packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.js#L416

If you can confirm that, I would make a PR later today.

**Comment by mfranzke** [comment]
> Do the changes have to be made in both of the following files?
> 
> https://github.com/pattern-lab/styleguidekit-assets-default/blob/develop/src/html/partials/iframe.html#L7
> 
> https://github.com/pattern-lab/patternlab-node/blob/dev/packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.js#L416
> 
> If you can confirm that, I would make a PR later today.

Sounds great, thanks a lot. And from my point of view, the following file would be enough, as the other repository (`styleguidekit-assets-default`) is a relict from the past (from my understanding) and we might want to archive it sooner than later (to even also avoid confusions), as its content has been moved to the `pattern-lab/patternlab-node` monorepo.
