### ISSUE TITLE
Some minor defects (Thumbs.db and .gitignore)

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#143]
First, this is excellent software and I am grateful for the work you've put into this.
Second, I don't think we need source/Thumbs.db so I am opening a pull request to delete it.
Third, I think line 11 of .gitignore should be config.json, not config.ini, a holdover from patternlab-php. My PR encompasses that as well.

**Comment by bmuenzenmeyer** [comment]
Merged to `dev`
