### ISSUE TITLE
HTML validation errors within pattern-lab UI parts

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1437]
I am using Pattern Lab Node `v5.16.2` on `Mac`, with Node `v14.19.3`, using a `Vanilla` Edition.

##### Expected Behavior
No HTML validation error is being reported by a W3C validator.

##### Actual Behavior
The w3.org validation service reports the following problem among others:
> Error: Element [div](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [button](https://html.spec.whatwg.org/multipage/#the-button-element) in this context.

##### Steps to Reproduce
Go to the URL https://validator.w3.org/nu/?doc=https%3A%2F%2Fpatternlab-handlebars-preview.netlify.app%2Fpatterns%2Fatoms-global%2Findex.html

**Comment by JosefBredereck** [comment]
Issue was released with v5.16.3
