### ISSUE TITLE
fix: code scanning alerts

### ISSUE THREAD

**Issue by mfranzke** [pattern-lab/patternlab-node#1441]
Tracking issue for:
- [x] https://github.com/pattern-lab/patternlab-node/security/code-scanning/20
- [x] https://github.com/pattern-lab/patternlab-node/security/code-scanning/16
- [x] https://github.com/pattern-lab/patternlab-node/security/code-scanning/19

**Comment by JosefBredereck** [comment]
Issue was released with v5.16.3
