### ISSUE TITLE
Support HTML entities within pattern parameters

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#145]
I tried putting some parentheses inside a pattern parameter string today and it did not work. We should be able to make these strings safer.  Would help with passing in things like `<strong>DANGER DANGER </strong>` too

**Comment by james-nash** [comment]
I think this will get fixed by PR #293. Doing something like `{{> pattern-name( foo: '<div class="bar">Look ma, HTML code!</div>' ) }}` should then work. The only requirement would be to wrap your HTML value in quotes.
@e2tha-e : Would you agree? I could add a test for this if you like.

**Comment by bmuenzenmeyer** [comment]
Great to hear!

**Comment by james-nash** [comment]
Ok, just added a test to show that this issue no longer exists in PR #307

**Comment by bmuenzenmeyer** [comment]
This is working like a dream - thanks you two!

**Comment by bmuenzenmeyer** [comment]
We've regressed on this in v3.

**Comment by JosefBredereck** [comment]
I was thinking if this is still an issue with the new feature of `{{> @partial-block }} `. 
Also if you add `{{{text}}}` to your pattern and call it with handlebars it should also work as expected `{{> pattern text="<strong>DANGER DANGER</strong>" }}`

**Comment by bmuenzenmeyer** [comment]
right - this is now a won't fix! if your pattern Engine of choice doesn't support this, use a more powerful one. We won't be propping up mustache any longer
