### ISSUE TITLE
Please allow more flexible Mustache partial syntax

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#146]
I have a Pattern Lab implementation I'm porting over from PHP. The PHP version allows the following syntax for partials:

* {{> templates-article }}
* {{> 03-templates/02-article }}
* {{> 03-templates/02-article.mustache }}

The Node version only allows the first. The greater flexibility of the PHP version is mandatory for my implementation. I'm submitting a pull request to allow for this. Please review, comment, and merge. Thanks!

**Comment by bmuenzenmeyer** [comment]
This would be a welcome addition @e2tha-e I was not aware the PHP version supported those. In my opinion they are not necessary because the "pattern key" in all instances is `templates-article` and the numerals are just a poorman's ordering device - but by all means PR away! 

:+1: :

**Comment by e2tha-e** [comment]
@bmuenzenmeyer I found the only advantage to the terse partials was terseness. As the project got bigger, knowing the exact paths of partials was a HUGE timesaver. And on top of that, I created a Mustache file browser which allowed you to recurse through many levels of partials, and this also required exact paths.

**Comment by bmuenzenmeyer** [comment]
Merged the PR associated to this as part of release [v0.12.0](https://github.com/pattern-lab/patternlab-node/releases/tag/v0.12.0)
