### ISSUE TITLE
engine-twig-php: include-function syntax not matched by findPartials 

### ISSUE THREAD

**Issue by hadl** [pattern-lab/patternlab-node#1471]
I am using Pattern Lab Node `v5.17.0` on ` Mac `, with Node `v16.18.1`, using a `Vanilla ` Edition.

##### Expected Behavior

> As of Twig 1.12, it is recommended to use the [include](https://twig.symfony.com/doc/2.x/functions/include.html) function instead as it provides the same features with a bit more flexibility.

Patternlab should find these includes too and show them in the linage information of a pattern.

##### Actual Behavior

Patternlab Engine Twig PHP findPartials regex does not match the include-function syntax. 
With that the linage is not found / shown and patterns are not updated correctly when using incremental builds.

**Comment by mfranzke** [comment]
@hadl thanks a lot for reporting this. Do you have the chance to provide a PR with necessary code changes as well ?

**Comment by hadl** [comment]
@mfranzke i have separated my fixes to two PRs cause of the bigger change in engine-twig.

I have recognized that the rendering of the "html" in engine-twig is not up-to-date with the twig template, but i could not find the issue causing that. 
Maybe you could quickly double-check that or give me a hint what the cause of that could be?
It does not affect my use of engine-twig-php but maybe it is for others.
