### ISSUE TITLE
Nothing compiling to patterns folder

### ISSUE THREAD

**Issue by chazchumley** [pattern-lab/patternlab-node#1479]
I am using Pattern Lab Node 6 on Mac with Node  v16.16.0 using a Vanilla Edition.

I am using the Twig engine with the demo and when running `npm run start` I would expect to see Pattern Lab rendering any atoms, molecules, etc.

Instead, I have an empty Pattern Lab instance and nothing is being output in the public/patterns folder.

Steps to reproduce:
1) npm create pattern-lab

Follow the prompts for a Twig version.

**Comment by JosefBredereck** [comment]
Closing duplicate of #1477
