### ISSUE TITLE
No way to view code in the single page?

### ISSUE THREAD

**Issue by davids701124** [pattern-lab/patternlab-node#148]
I tried to tweak the config and also reoder the hierachy of the files in _patterns. It seems there is no way to show html code in the signle element page. It only shows when I am viewing all elements.

**Comment by bmuenzenmeyer** [comment]
hmm - this seems like something we should be able to do. I will look into it.

**Comment by davids701124** [comment]
That would be great! Thank you in advanced :)

**Comment by bmuenzenmeyer** [comment]
@davids701124 what version are you running? I am able to view the HTML for the sample pattern `atoms-colors` on version v0.12.0

**Comment by bmuenzenmeyer** [comment]
![single-pattern-code-view](https://cloud.githubusercontent.com/assets/298435/9979488/6adf08be-5f35-11e5-8492-1d374016eaeb.png)

Uploaded what I think you mean. Please confirm.

**Comment by bmuenzenmeyer** [comment]
Closing this since it seems to be working for me with the latest build of pattern-lab
