### ISSUE TITLE
[Documentation] Engine configuration fileExtension vs extension

### ISSUE THREAD

**Issue by StfBauer** [pattern-lab/patternlab-node#1480]
I use Pattern Lab Node `v6.0.1` on `Windows | Mac | Linux`, with Node `v16.15.1`, using a `Vanilla` Edition with a little bit of gulp flavoured on top.

I recently upgrade to version 6.0.1 everything works as expected but I got an error message that the engine is not configured correctly. The engine configuration looked as follows:

```json
{
  "engines": {
    "handlebars": {
      "package": "@pattern-lab/engine-handlebars",
      "extensions": [
        "handlebars",
        "hbs"
      ],
      "extend": "helpers/hbs/*.js"
    }
  }
}
```

This is according to the documentation: [Engine](https://patternlab.io/docs/editing-the-configuration-options/#heading-engines)
However, I created a new project based on version 6.0.0.

The configuration in 6.0.0 looks as followed:

```json
{
  "engines": {
    "handlebars": {
      "package": "@pattern-lab/engine-handlebars",
      "fileExtensions": [
        "handlebars",
        "hbs"
      ],
      "extend": "helpers/hbs/*.js"
    }
  }
}
```

After I modified my configuration to "fileExtension" instead of "extension", the error message was not showing up anymore. So the question is now. Is the documentation outdated, which it seems to be, or an issue in pattern lab that got introduced in v6.0.1

**Comment by JosefBredereck** [comment]
I'm afraid none of the above is correct. 
I wonder that there is an error message popping up because we do absolutely nothing with the given settings at the moment.
For most engines we, we only use `extent`, noting more.

I think the initial intention of the creator of that code was to allow the user to override the default `fileExtensions`.
I will prepare a fix for the engines and also for the documentation.

Thank you very much for highlighting this discrepancy.

**Comment by JosefBredereck** [comment]
Have you updated the package `@pattern-lab/engine-handlebars` in the first project where you tried?
Would you mind reproducing it and hand me the error message you receive?

I tried it for myself with different options and none were giving me an error.

**Comment by StfBauer** [comment]
Where I started:

![Screenshot 2023-02-07 at 09 51 17](https://user-images.githubusercontent.com/5503835/217196919-d9a4a399-5411-46c7-b229-fda7edecea49.png)

I also had only `extend` in configuration:

```json
  "engines": {
    "handlebars": {
      "extend": "helpers/*.js"
    }
  }
```

Which I then update to:

```json
  "dependencies": {
    "@pattern-lab/cli": "^6.0.1",
    "@pattern-lab/core": "^6.0.1",
    "@pattern-lab/engine-handlebars": "^6.0.0",
    "@pattern-lab/uikit-bare": "^0.0.1",
    "@pattern-lab/uikit-workshop": "^6.0.1"
  }
```

After npm install and run pattern labs got the following message still with the `extend` in there:

![image](https://user-images.githubusercontent.com/5503835/217197800-d5f21da6-bf2f-4e70-b2a2-a0c2b055e6fb.png)

I headed over to the documentation, pasted the prescribed change, and got the same message. That's how I provisioned a new project and figured out the misleading configuration there.

If you like reproducing it, you can use [hTWOo](https://github.com/n8design/htwoo).
* Clone the repo
* navigate to [htwoo-core](https://github.com/n8design/htwoo/tree/main/htwoo-core) folder in there and try it for yourself

Thanks in advance.

**Comment by JosefBredereck** [comment]
The only required parameter is the following and it is the source of the issue.
`"package": "@pattern-lab/engine-handlebars",`

The `extend` property will be used by the handlebars engine if you have extensions installed.

**Comment by StfBauer** [comment]
Am I correct? The only thing needed is:

```json
  "engines": {
    "handlebars": {
      "package": "@pattern-lab/engine-handlebars",
      "extend": "helpers/hbs/*.js"
    }
  }
```

or could I remove even the "extend" and all the helpers will get recognised too?

**Comment by JosefBredereck** [comment]
If you do not need the files located in https://github.com/n8design/htwoo/tree/main/htwoo-core/helpers loaded by handlebars, this is also not required and you can just use 

```json
  "engines": {
    "handlebars": {
      "package": "@pattern-lab/engine-handlebars",
    }
  }
```
