### ISSUE TITLE
Twig does not reload template on changes (PHP and node)

### ISSUE THREAD

**Issue by JosefBredereck** [pattern-lab/patternlab-node#1487]
I am using Pattern Lab Node `v6.0.1` on `Windows | Mac | Linux`, with Node `v16.17.0`, using a `Twig` Edition.

##### Expected Behavior

When I change any twig template, pattern lab rebuilds and reloads the page.
The new template is applied and visible in the output view.

##### Actual Behavior

When I change any twig template, pattern lab rebuilds and reloads the page.
No changes are visible, and they are not present in the template.

##### Steps to Reproduce

1. `npm create pattern-lab`
2. follow the steps to install twig
3. `patternlab install --starterkits @pattern-lab/starterkit-twig-demo`
4. `npm run start`
5. Navigate to pages ⇾ homepage
6. change anything in templates ⇾ homepage or underlying components
7. Observe the output

**Comment by hadl** [comment]
I did a test with node `v16.19.0` and PHP `8.1.15` and `7.4.33` and cannot reproduce the issue.
When switching the PHP versions i have removed `node_modules` and ran `npm i` again.

**Comment by JosefBredereck** [comment]
Thanks for reverification. Maybe this was a local issue for me. Closing the issue then.

**Comment by hadl** [comment]
Sure, no problem.

Maybe this is related to #1310 and/or https://github.com/knapsack-cloud/twig-renderer/issues/78.
Although i did not run into this for a long time - fortunately.

Anyway i will keep an eye on that during my further use.
