### ISSUE TITLE
Want ordering of pattern variants to be like in patternlab-php

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#153]
Currently, in patternlab-node, in the toolbar menu, any pattern variants are listed before the primary pattern. (See how Homepage Emergency comes before Homepage.) I would like the primary pattern to be listed first, and the variants after as it is in patternlab-php. Am submitting pull request for this.

**Comment by bmuenzenmeyer** [comment]
Merged
