### ISSUE TITLE
Need recursive partial inclusion

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#156]
Bug: Since partial inclusion is currently iterative, if a Mustache file includes a partial that diveSync will iterate on later because it is sorted higher alphanumerically, Pattern Lab will fail.

To replicate:
* Create `source/_patterns/02-organisms/00-global/02-test.mustache`
* Enter some dummy content: `<h1>Foo</h1>`
* Include that partial anywhere in `source/_patterns/02-organisms/00-global/00-header.mustache`
* `{{> organisms-test }}`
* View the Pattern Lab in a browser - completely broken

Fix: need recursive inclusion of partials

**Comment by bmuenzenmeyer** [comment]
This will auto-close when it reaches `master`
