### ISSUE TITLE
styleGuideExcludes equivalent

### ISSUE THREAD

**Issue by illepic** [pattern-lab/patternlab-node#158]
In the PHP version of Pattern Lab, `config/config.ini` contains

````
// the pattern types that shouldn't be included in the style guide, useful if you nest pages/templates
styleGuideExcludes = ""
````

This prevents templates and pages from printing in the "all" styleguide page, if configured like so:

````
styleGuideExcludes = "templates,pages"
````

This is quite useful to make the landing "all" styleguide page much much more responsive and speedy. Does an equivalent to this exist already?

**Comment by bmuenzenmeyer** [comment]
Not yet, was not aware of this feature. Thanks for the heads up.

**Comment by bramsmulders** [comment]
@bmuenzenmeyer i've fixed this in my pull request, please review. Lets hope it is good! ;)
