### ISSUE TITLE
Optimize browsersync inject to avoid full-page refreshes

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#159]
@bmuenzenmeyer @oscar-g
I can't seem to get browsersync to inject without a complete page refresh. If I load the pattern outside the iframe, then injection works fine. But inside the iframe, it causes the entire page to refresh. Does anyone know how to avoid the page refresh while still working within the Pattern Lab iframe?

**Comment by bmuenzenmeyer** [comment]
Hey @e2tha-e browsersync is a bit clunky with patternlab due to the iframes. I've chalked this up as an acceptable quirk for now, citing the other big advantages it brings. I've mean to look more into this someday, unless a solution presents itself via PR.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer Do you think it would be ok to have Node listening on another port for the iframe? I don't know off-hand whether the same-origin policy will be fulfilled, and it seems like maybe too much overhead just for dom injection.

@geoffp mentioned he might have gotten injection working in #252. Eager to hear what it may be.

**Comment by geoffp** [comment]
Anyone who's interested, please check out https://github.com/pattern-lab/patternlab-node/pull/260 and let me know if it works for you.
