### ISSUE TITLE
allowing verbose partials for list items

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#164]
@bmuenzenmeyer Just making a reminder that I submitted pr #163 which is ready for review in spite of the failed CI. It tests ok when running grunt nodeunit (besides the complaint about gulp.task not being a function).

**Comment by bmuenzenmeyer** [comment]
@e2tha-e I haven't forgotten. The failure is all of PL not installing because of node 4.X

I plan to revert support considering https://github.com/pattern-lab/patternlab-node/issues/162 and merge this PR sooner rather than later. I've been ill the past couple days so sit tight!

:rocket:
