### ISSUE TITLE
Hiding patterns is not working

### ISSUE THREAD

**Issue by ivancamilov** [pattern-lab/patternlab-node#165]
According to [the docs](http://patternlab.io/docs/pattern-hiding.html), if you append an underscore (_) to the pattern name it should "no longer show up in the drop-down navigation, the media pattern sub-type "view all" page, nor the style guide".

However, if you do this in patternlab-node the pattern still shows up in the "view all" page. I fixed this in my local copy by editing `/builder/patternlab_assembler.js` and adding this check around line 107:
```
// ignore files prepended with _
if(filename[0] == '_'){
  return;
}
```
Should I do a PR with this change?

**Comment by bmuenzenmeyer** [comment]
Hi @ivancamilov I can investigate on my end too.

Can you tell me which version you are running?

**Comment by ivancamilov** [comment]
Hi @bmuenzenmeyer, I'm using the latest stable release, v0.13.0. I downloaded it [here](https://github.com/pattern-lab/patternlab-node/releases/tag/v0.13.0).

**Comment by bmuenzenmeyer** [comment]
@ivancamilov thanks for checking. This logic was changed recently and I could swear I tested it, but might have missed the view all use case. will take a look as time allows.

**Comment by bmuenzenmeyer** [comment]
@ivancamilov confirmed this is a regression on my part. apologies, but thanks for the catch. if you'd like to submit a PR, please do so. if you can get a unit test on this too that would be wonderful

**Comment by ivancamilov** [comment]
ok cool, I'll send you a PR this weekend with a test for it.

**Comment by bmuenzenmeyer** [comment]
@ivancamilov any progress on this?
