### ISSUE TITLE
pattern states not working as documented

### ISSUE THREAD

**Issue by ivancamilov** [pattern-lab/patternlab-node#166]
According to [the docs](http://patternlab.io/docs/pattern-states.html), you should be able to define a pattern's state by setting it in the filename, ie changing `00-media-block.mustache` to `00-media-block@inprogress.mustache`.

However, patternlab-node doesn't work as documented; instead, it has [a different way](https://github.com/pattern-lab/patternlab-node#pattern-states) to set states by changing the `config.json` file.

Shouldn't patternlab-node work as documented in patternlab.io?

**Comment by bmuenzenmeyer** [comment]
Not in every case. That documentation is officially for the PHP version. I know this is confusing. [There is actually a bunch of documentation](https://github.com/pattern-lab/website/tree/dev) in a different branch of the site, but it's unreleased. Brad and his brother are working on v2 of the site which will probably have the node documents. 

For now, we are in a sort of limbo between the README and some stuff here: https://github.com/pattern-lab/website/tree/dev/patternlabsite/docs/node

Also, on principle... PL node doesn't do everything exactly the same way as PHP. Like I said, I hope to make this more clear in the future. Please do reach out with specific questions here on on twitter. I try to be rather transparent about what work is going on: https://github.com/pattern-lab/patternlab-node/issues/134

**Comment by ivancamilov** [comment]
I understand, thanks for the clarification.
