### ISSUE TITLE
meta patterns missing?

### ISSUE THREAD

**Issue by ivancamilov** [pattern-lab/patternlab-node#169]
This might be more of a question than a bug report. In PL-PHP there are [two meta patterns](http://patternlab.io/docs/pattern-header-footer.html) for the header and the footer. These are very useful for adding libraries and external dependencies.

However, I do not see a way to do this in patternlab-node. There seem to be separate files for this, namely:
```
/pattern-header-footer/header.html
/pattern-header-footer/footer.html
/pattern-header-footer/index.mustache
/pattern-header-footer/styleguide.mustache
/pattern-header-footer/viewall.mustache
```
As far as I can see, you would need to modify all these files to include a dependency such as bootstrap. Is there something I'm missing here? Should pl-node support meta patterns like those on pl-php?

**Comment by bmuenzenmeyer** [comment]
In my opinion this is in scope as part of
https://github.com/pattern-lab/patternlab-node/issues/133

**Comment by ivancamilov** [comment]
that's right, I hadn't seen it on the roadmap. Thanks for adding it!

**Comment by AdamTew** [comment]
Would this be the only way to add different classes to the `<body>` dynamically? I tried adding using a mustache variable to `_patternlab-files/pattern-header-footer/header.html` but (probably because it's an `.html` file and not a `.mustache` file) it doesn't recognize the variable.

**Comment by bmuenzenmeyer** [comment]
@AdamTew I am pretty sure this is unsupported, at least for the next couple weeks. I plan to move toward a structure that allows for me to use [the mustache starterkit's header](https://github.com/pattern-lab/starterkit-mustache-default/blob/dev/dist/_meta/_00-head.mustache) as seen in PL PHP, but I am not there yet. 

Stay tuned!

**Comment by bramsmulders** [comment]
How do you guys add custom javascripts to you pages? Is it by adding them to `header.html` &/or `footer.html`? isnt this conflicting with patternlab itself?

**Comment by e2tha-e** [comment]
@Bram Smulders Yes, that's the only way for now, and yes, that's
conflicting with Pattern Lab core. Here's the issue where we're working on
a fix:
https://github.com/pattern-lab/patternlab-node/issues/133

Also, might want to comment directly in GitHub so the general public can
see the discussion.
