### ISSUE TITLE
Custom navigation

### ISSUE THREAD

**Issue by christophrumpel** [pattern-lab/patternlab-node#170]
Hey,

I need to use Pattern Lab with a custom navigation. Therefore I would like to call the nav levels separately. (e.g. showing a certain nav level inside a sidebar)

From what I have seen so far, it looks like I can only loop through all "nav levels" like in the "patternNav.mustache" right?

1.) Is there a way to call the "current" patternItems somewhere else?
2.) Is it possible to see which pattern are "active"? Like highlighting the current nav?

Thanks and cheers

**Comment by bmuenzenmeyer** [comment]
Hi @christophrumpel thanks for your interest in patternlab!

To my knowledge there is nothing that does this OOB with current editions of patternlab. The [node roadmap](https://github.com/pattern-lab/patternlab-node/issues/134) is tightening up, with a post 1.X.0 world looking to have more and clearer opportunities for extension, as well as a planned integration with https://github.com/pattern-lab/styleguidekit-assets-default. Your suggestions might be better served to be reported and discussed in that repository.

**Comment by christophrumpel** [comment]
Ok, thanks for the info.
