### ISSUE TITLE
Patternlab freaks out (loading page repeatedly) when index.html is used

### ISSUE THREAD

**Issue by mattsah** [pattern-lab/patternlab-node#176]
I'm trying to use patternlab alongside various PHP frameworks.  I tried the PHP version, but I switched to using node because I thought it would be better integrated with the rest of the front end dev sfuff and would work for front end devs that don't have php installed on their systems, but would have node/gulp.

However, since we're running it alongside there's an index.php and an index.html -- the index.php is the entry point to the framework while the index.html is pattern lab.  We can still address it directly as index.html which initially loads the "all" page, but if I select a specific pattern the browser starts trying to load a page nonstop.

For the record, the PHP version fairs only marginal better, replacing the index.php with a ?p=<path to pattern> (which this version does too if index.html isn't used in the original address), but then on reload since it will default to index.php not index.html the ?p=<path to pattern> just loads the framework homepage with that query string (which is meaningless).

I dug through the JS a bit, but I couldn't pinpoint exactly what was going on.  Obviously the link handling is replaced and it looks like there's some custom history methods in there, but I didn't see anything which should cause it to reload like that constantly.

**Comment by bmuenzenmeyer** [comment]
Hi @mattsah cannot say I've experienced that. I can run using the shipped webserver or by navigating to index.html and both behave. 

* Sounds like you are not using the shipped webserver at all. Have you tried that? 
* Are you doing any other file watching outside the normal scope of patternlab?
  * If so, grunt or gulp?
* What version of patternlab are you running?

**Comment by mattsah** [comment]
This is using gulp serve only as defined amongst the packages.gulp.json provided in repo and on the latest version tagged 0.13.1.

The default location for the server does not specify index.html and just drops you at '/' -- this works.as expected, if I go to Atoms -> Typography -> Headings, the iframe reloads and the URL is changed to http://localhost:3000/?p=atoms-headings

The problem only arises when I specify index.html in the address such that I begin on http://localhost:3000/index.html and then do the same thing, and the iframe reloads constantly, never getting to a point where the main window URL is rewritten.

**Comment by bmuenzenmeyer** [comment]
Recreated. Thanks for the additional info.

**Comment by bmuenzenmeyer** [comment]
Closed per comment in https://github.com/pattern-lab/patternlab-node/pull/309
