### ISSUE TITLE
Failed at the contextify@0.1.14 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by donavanmarais** [pattern-lab/patternlab-node#180]
Downloaded zip file to new directory
Ran npm install
Build fails:
                                                            
14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dmarais/Projects/patternlab-node-master/node_modules/contextify
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmarais/Projects/patternlab-node-master/npm-debug.log

Tried to manually install node-gyp and contextify:

npm install -g node-gyp

Result:

usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

sudo npm install contextify

Result:

14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dmarais/Projects/patternlab-node-master/node_modules/contextify
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "contextify"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

Any help would be appreciated please?

**Comment by bmuenzenmeyer** [comment]
What version of Node are you running? What platform are you on? This looks to me at first glance like an instance of https://github.com/pattern-lab/patternlab-node/issues/162. I haven't vetted 4.X+ versions of pl node yet, especially on Windows, and had to revert back to 0.12 myself.

**Comment by donavanmarais** [comment]
On OSX Yosemite, running node v5.0.0

**Comment by bmuenzenmeyer** [comment]
Looks like node 5.0, sorry I should have read more closely. The next free
night I have I'll be looking at revisiting the node upgrade as it's
inevitable to get this working.

Thanks for reporting!

**Comment by donavanmarais** [comment]
You're welcome. Looking forward to a fix. :)

**Comment by donavanmarais** [comment]
By the way, I just tried to install on Windows 7 and encountered the same issue. 
Fresh Windows 7 install with node v5.0.0 and npm version 3.3.6
Installed node first, then downloaded zip, in cmd went to that dir and ran npm install. 
Same error messages as above.

**Comment by bmuenzenmeyer** [comment]
Ok. I haven't tried 5 .0yet. Knew dependencies were failing at 4.0 about a
month ago, hence the note in readme and the linked issue. Thanks for more
info!

**Comment by bmuenzenmeyer** [comment]
I've confirmed this myself. Trying to ensure I followed the steps here: https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

I need to dig in and see what else can be done..

**Comment by bmuenzenmeyer** [comment]
@donavanmarais please try again against v0.15.0

**Comment by donavanmarais** [comment]
Successful build.  Great Success!!!

Much appreciated you jumping on this so quick Brian. You are a gentleman and a scholar!

**Comment by bmuenzenmeyer** [comment]
Great to hear. As I mentioned in the release notes too, https://github.com/tjunnone/npm-check-updates was a super big help in just updating everything once I'd exhausted a bunch of other things.

Happy patternlabbing :rocket:
