### ISSUE TITLE
styleModifier tag not working with spaces

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#183]
When using a styleModifier on a pattern using `{{ styleModifier }}` does not work, but `{{styleModifier}}` does. The only difference is the spaces.

This is not an issue with the message tag, both `{{ message }}` and `{{message}}` work.

**Comment by bmuenzenmeyer** [comment]
Hmm I must have goofed a regex. Will look into this. thanks for reporting.

**Comment by theorise** [comment]
It seems multiple classes are also not supported. I saw a mirror issue in the PHP version that has been resolved: https://github.com/pattern-lab/patternlab-php/issues/172

**Comment by bmuenzenmeyer** [comment]
Opened a separate issue for what you reported.

**Comment by theorise** [comment]
Thanks. I have also come across a strange occurrence using particular classes on the styleModifier.

```
{{> atoms-header:a_a-0(message: "Hi" ) }}
```

> Warning: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials) Use --force to continue.

**Comment by bmuenzenmeyer** [comment]
This will close automatically when it hits `master` branch. No further action needed.
