### ISSUE TITLE
Annotation HTML output

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#187]
I want to be able to include HTML inside my annotions.js comments. 

In this case I want to add an itemprop attribute to a h1 tag. I do not want this data inside my pattern file, however I want to notify the PL users that this element should be using this attribute.

I can do this, however PL outputs the HTML tags directly, rather than stringifying them. 

I can do it manually, however it is not ideal.

In annotations.js

```
"comment" : "The header tag should be <h2 itemprop=\"brand\">. 
```

The manual work around:
```
"comment" : "The header tag should be &lt;h2 itemprop=\"brand\"&gt;. 
```

I cannot think of any examples of when a user would want the comment section to be rendered differently using custom markup - so it feels like the default behaviour should stringifying the HTML inside the annotations.js comments:

**Comment by bmuenzenmeyer** [comment]
Similar to https://github.com/pattern-lab/patternlab-node/issues/145

**Comment by bmuenzenmeyer** [comment]
This is now handled best using annotations markdown.
http://patternlab.io/docs/pattern-adding-annotations.html
