### ISSUE TITLE
Only able to use top level elements in data.json for pattern parameter keys

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#189]
If I try to use any nested element inside the data.json for a pattern include, I get `[SyntaxError: Unexpected token .]` and `Warning: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials) Use --force to continue.` 

The build does not fail, but the offending patterns are broken.

**data.json:**

```
"toplevel" : "300,00",
"price": {
    "old": "250,00",
    "new": "75,00"
}
```

**pattern.mustache:**

```
<span class="price {{styleModifier}}">
    {{price.old}}
</span>
```

**pattern include call examples that throw the error:**

```
{{> atoms-price:new(price.old: "75,00" ) }}
{{> atoms-price:new(price.old: "{{price.new}}" ) }}
```

If I use the `toplevel` value, the above works as expected.

**Comment by bmuenzenmeyer** [comment]
I have some research to do - but I don't think this syntax is supported. Specifically, having `price.old` as the key for a pattern parameter. I suspect doing so is causing a lot of the issues you've reported.  I understand why one would do this, however, as it's directly related to using deeper data objects inside mustache syntax, as you mention here https://github.com/pattern-lab/patternlab-node/issues/189.

I might try to consolidate all of these issues into one, as I think these are all symptoms of the same issue.

**Comment by bmuenzenmeyer** [comment]
Hey @dmolsen 

If you happen to have an up-to-date copy of PL PHP that you could test this on, I'd appreciate it. I am fairly certain it would be an enhancement to PL NODE in that patternParameter keys were not built to support mustache:

```
{{> atoms-price(price.old: "$100" ) }}
```

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

PL PHP doesn't support mustache in patternParameter keys either. That said, it is just a simple find and replace so I can get the example working with a small tweak to the initial example. Mustache tends to fall on its face using mustache tags in a pattern parameter. This is because Mustache is just looking for the closing bracket. It doesn't understand nesting. Instead we need to define a different delimiter for the pattern partial. So the example should look like:

```
{{> atoms-price:new(price.old: "75,00" ) }}
{{=<% %>=}}
<%> atoms-price:new(price.old: "{{ price.new }}" ) %>
<%={{ }}=%>
```

That produces the expected results for me in the dev version of PL2.

**Comment by bmuenzenmeyer** [comment]
Sorry Dave but I don't understand this syntax 

`{{=<% %>=}}`

`<%={{ }}=%>`

Are these working in isolation? In tandem? The first looks inverted, the second just empty `{{ }}` inside a different delimiter. My mind is soupy from asp.net perhaps.

**Comment by dmolsen** [comment]
The = sets a delimiter. Eg what the mustache parser will see as a valid mustache tag. The first call changes the delimiter from {{ }} to <% %>. That way the mustache var in the pattern parameter doesn't get parsed and is instead seen just as a string. The second call switches the delimiter back.

More info:
https://mustache.github.io/mustache.5.html

**Comment by bmuenzenmeyer** [comment]
Oh!!!! Cool :dancer: :dancers:
