### ISSUE TITLE
Next Pattern Button

### ISSUE THREAD

**Issue by adamtew** [pattern-lab/patternlab-node#193]
Sometimes I'm looking at a pattern, usually an atom in a group of atoms, and I want to look at the next atom in the series (Say there's an inputs folder and I want to look through all the types). Instead of having to click on the atoms tab, find the inputs folder, and then select the next input type, it would be nice to have a button (or better yet, a keyboard shortcut) to just flip through the atoms.

Just a thought :)

**Comment by bmuenzenmeyer** [comment]
This could likely be accomplished with a plugin.
Closing.
