### ISSUE TITLE
ctrl+shift+0 does not set viewport to 320px per documentation

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#201]
Instead, it sets to the first MQ as `ctrl+shift+1` is supposed to do.
reference: http://patternlab.io/docs/advanced-keyboard-shortcuts.html

**Comment by bmuenzenmeyer** [comment]
Scratch that initial report. I debugged this and the command's don't even reach the handlers. Confirmed this is an issue in Chrome, Firefox, Edge and Opera, with local code and demo.patternlab.io

Chrome does map this command too: https://support.google.com/chromebook/answer/183101?hl=en
Other commands look masked in Firefox too https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

Going to document this is known issue and move on for now.

**Comment by bmuenzenmeyer** [comment]
Documented https://github.com/pattern-lab/patternlab-node/wiki/Known-Issues-&-Deviations-from-Pattern-Lab-PHP

**Comment by bmuenzenmeyer** [comment]
@dmolsen have you experienced this? I couldn't find an issue on any of your repos.

**Comment by dmolsen** [comment]
`ctrl+shift+0` on demo.patternlab.io works for me on Safari/Mac and Chrome/Mac. Haven't had any issues. Double-check focus. So try making the iframe a little smaller, click in the grey and try the key combo. Then click inside the iframe and try the key combo. Might help you track down the issue.

**Comment by bmuenzenmeyer** [comment]
Interesting, but still the same on my end. 

I am certain focus is in the right place, as `ctrl+shift+1` works no sweat, but `ctrl+shift+0` does nothing. I'll do some more digging. I will try on some other Windows machines when I get a chance too.
