### ISSUE TITLE
Better error logging with a mustache templates

### ISSUE THREAD

**Issue by iansoper** [pattern-lab/patternlab-node#209]
I was converting a patternlab php version site to the node version and I got errors with my pattern mustache files. I got errors like this:

``` bash
[16:56:36] 'patternlab' errored after 611 ms
[16:56:36] TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (/Users/iansoper/code/wisertogether/patternlab-node/node_modules/mustache/mustache.js:598:13)
    at renderPattern (/Users/iansoper/code/wisertogether/patternlab-node/builder/pattern_assembler.js:82:25)
    at Object.renderPattern (/Users/iansoper/code/wisertogether/patternlab-node/builder/pattern_assembler.js:369:16)
    at /Users/iansoper/code/wisertogether/patternlab-node/builder/patternlab.js:130:50
    at Array.forEach (native)
    at buildPatterns (/Users/iansoper/code/wisertogether/patternlab-node/builder/patternlab.js:124:25)
    at Object.build (/Users/iansoper/code/wisertogether/patternlab-node/builder/patternlab.js:420:7)
    at Gulp.<anonymous> (/Users/iansoper/code/wisertogether/patternlab-node/builder/patternlab_gulp.js:15:16)
    at module.exports (/Users/iansoper/code/wisertogether/patternlab-node/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/iansoper/code/wisertogether/patternlab-node/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

However, this is not verbose enough for me to see which mustache files or which parts of the files are causing the errors. I had to comb through and look at where the build files ended to figure out where the issues were. I would be nice to have more verbose errors.

**Comment by bmuenzenmeyer** [comment]
This is a good idea, apologies for having to troubleshoot so long. I am pretty sure PL PHP has this functionality.
I'll make sure to get this into an upcoming release.

**Comment by iansoper** [comment]
Thanks! It would be a great improvement.

A lot of the issues I was having didn't seem to be a problem when using the php version, so I'm not sure the differences between the two if it is the mustache engine or something else that is causing the errors I was having.

**Comment by dmolsen** [comment]
@iansoper -

Did you happen to document any of the issues you found? I'm curious what they are so we can get them addressed. Brian and I were talking about developing a stronger spec. Even if you don't have exact examples just a general idea would be really helpful. Thanks.

**Comment by bmuenzenmeyer** [comment]
:+1: 

Put them here, or preferably, each in separate issues.

**Comment by iansoper** [comment]
I'll put them here for now:

## Pattern parameters
this worked in php version: `pattern-name(parameter: value)`
Had to add quotes for the value for the node version: `pattern-name(parameter: 'value')`

## Section values
Error:
```
[SyntaxError: Unexpected token -]
[SyntaxError: Unexpected token -]
```
I think this is related to having a value that has a `-` separating, but I'm not sure.
```
{{# this-value }}
{{/ this-value }}
```

Again, both of these issues worked fine in the PHP version, but don't work in the node version.

**Comment by bmuenzenmeyer** [comment]
Thanks for reporting. Not everything is exactly the same across versions, but every effort to achieve feature parity should be made to support people migrating from version to version.

**Comment by iansoper** [comment]
I totally understand, just wanted to highlight the differences.

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

The section values issue is probably just a difference between PHP & Node mustache implementations. Spec says that they key for a section has to be a string without whitespaces. Not seeing any tests in the node version that would blow up on a dash in the key though. Just noting this so you don't spin your wheels on something we probably can't fix ;)

**Comment by bmuenzenmeyer** [comment]
Yeah it sounds like that. I'll take a look.

**Comment by bmuenzenmeyer** [comment]
> I think this is related to having a value that has a - separating, but I'm not sure.

I have this working with the following `00-homepage.mustache` template code 

```
{{# emergency-section }}
	{{> molecules-alert }}
{{/ emergency-section }}
```

and subsequent json

```
{
  "emergency-section": {
    "alertClass" : "error",
    "excerpt" : {
      "short" : "Emergency! This is a variation of the core homepage template."
    }
  }
}
```

@iansoper If you still have the actual files laying around, could you include them here as a a gist?

> this worked in php version: pattern-name(parameter: value)
Had to add quotes for the value for the node version: pattern-name(parameter: 'value')

I am going to keep this behavior unless I get major protests. It feels more aligned with HTML syntax (at least in my opinion) to have an key value relationship that accepts a string when expecting a string. I've updated the [wiki](https://github.com/pattern-lab/patternlab-node/wiki/Known-Issues-&-Deviations-from-Pattern-Lab-PHP) to attempt to document this difference.

------

The original contents of this issue remain open, and important to me to address. Thanks Ian!

**Comment by bmuenzenmeyer** [comment]
On hold until https://github.com/pattern-lab/patternlab-node/tree/pattern-engines work solidifies
