### ISSUE TITLE
Hiding patterns with an underscore, but still being able to access the pattern with includes

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#210]
According to the [docs](http://patternlab.io/docs/pattern-hiding.html), if you append an underscore (_) to the pattern name it should "no longer show up in the drop-down navigation, the media pattern sub-type "view all" page, nor the style guide".

---

I want to hide a pattern from the drop-down and the 'view all', however I still want to use the pattern as an include, and for the patterns using it to be displayed (as they have no underscore in their file name/parent folder name). 

If I try this, the builder will just tell me that the pattern is missing 'Could not find pattern with key atoms-$'.

**Comment by bmuenzenmeyer** [comment]
I've seen use cases for this too. It should definitely be considered. 
@dmolsen does PL PHP handle this as theorise suggests?

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

Yes. It's borked in PL2 but @theorise is correct in his interpretation. PL2 also supports a dash at the beginning of a file name to denote "show in the pattern drop down but _don't_ show in the 'view all' views."

**Comment by bmuenzenmeyer** [comment]
Nice - thanks for additional information.

**Comment by geoffp** [comment]
Oh wow -- I didn't even know I wanted this feature, but I do. Our "view
all" is horrifyingly broken by multiple patterns that use fixed positioning.

**Comment by bmuenzenmeyer** [comment]
Yeah the more I think about this the more it makes a ton of sense. I do this on an internal instance of Pattern Lab with some base patterns that get parameterized downstream. The bases are pretty useless when used like this..

I'll get this in asap, per strong feedback!

**Comment by bradfrost** [comment]
Hey @geoffp,
> Our "view all" is horrifyingly broken by multiple patterns that use fixed positioning.

The way I deal with that stuff is to override the styles in `styleguide-specific.scss`. From the comments at the top of the file: 

> This stylesheet is for styles you want to include only when the interface is being viewed within Pattern Lab.
>  This is helpful for displaying demo styles for grids, animations, color swatches, etc
> It's also helpful for overriding context-specific styles like fixed or absolutely positioned elements
> These styles will not be your production CSS.

**Comment by bmuenzenmeyer** [comment]
**Internal Note**

Odd that [this code](https://github.com/pattern-lab/patternlab-node/blob/master/builder/patternlab.js#L189-L192) does not appear to be functioning?  There are no unit tests on the front-end menu generation, it's years old and :hankey:

**Comment by bmuenzenmeyer** [comment]
@dmolsen I assume it should however be accessible via lineage links?

**Comment by bmuenzenmeyer** [comment]
This is live in `dev` branch and will close automatically when it reaches master.

**Comment by geoffp** [comment]
@bradfrost just now took your advice on `styleguide-specific.css`. Works like a charm!

**Comment by bradfrost** [comment]
Great to hear! Happy new year!

__________________________________
Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by EvanLovely** [comment]
Would love this feature too! Very useful for when the base partial being imported doesn't need to be shown alone.

**Comment by simonknittel** [comment]
@bmuenzenmeyer This does not seem to be working. I just updated my PatternLab-Node to the dev-branch version.

My name is called `_icon.mustache` and located in the directory `00-atoms`. I'm trying to include it with `{{> atoms-icon}}`.

The atom does not show up in the navigation or 'all' view, but also not in the template where I want to include the atom.

I don't get any errors.

**Comment by simonknittel** [comment]
I have done a little bit further research and found some weird issues:

I have an other pattern which is called `05-icons.mustache`. There different issues on different naming cases:

**#1** (desired state)  
`05-icons.mustache` and `_icon.mustache` => as described in my previous post

**#2** (renamed _`icon.mustache` to `_import.mustache`)  
`05-icons.mustache` and `_import.mustache` => gulp dies with `TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)`

**#3**  
`05-icons.mustache` and `icon.mustache` => The pattern gets show and included everywhere

**Comment by bmuenzenmeyer** [comment]
I got this working in a copy of `dev` with `{{> atoms-_icon}}` Let me know if that works for you.

Not ideal but may work for now if you are in a pinch. I assume the preference by everybody would be to not include the underscore, but it might also signify that you are including an excluded pattern?

Feedback appreciated

**Comment by simonknittel** [comment]
That works. Thanks! I tried everything, but not this ...
