### ISSUE TITLE
Multiple styleModifiers break when using numerical characters

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#211]
When using a number (0-9) with more than one styleModifier, the builder breaks. For example:
`{{> atoms-test:modifierOne|modifier1}}`

> Could not find pattern with key {{> atoms-test:modifierOne|modifier1}}
> Warning: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials) Use --force to continue.

**Comment by bmuenzenmeyer** [comment]
**Internal FYI only:** I shoved this example into a  [regexr](http://www.regexr.com/3ce0m) of half the code in question, and it succeeded, so the core mechanism of finding styleModifiers is not broken. 

I had a similar problem during initial implementation where some pattern find logic was not accounting for these. My guess is that the same logic is not accounting for numerous (|) style modifiers.

**Comment by bmuenzenmeyer** [comment]
This is live in `dev` branch and will close automatically when it reaches master.

**Comment by theorise** [comment]
@bmuenzenmeyer I just patched my install and ran the test case - it is working as expected. Thanks!
