### ISSUE TITLE
UI/UX : add access to pages with "all atoms" / "all molecules" and "all subfolder".

### ISSUE THREAD

**Issue by gael-boyenval** [pattern-lab/patternlab-node#217]
It should be a nice feature to give the user access to a view with "all" items in a top level and sub level folder. 

this should be accessible : 
- by displaying the sub nav at mouseover, and access to all items in a category by clicking on it. 
- or by keeping the click event and adding a small button next to the title of the folder/subfolder name.

**Comment by bradfrost** [comment]
I'm not sure if this exists on the node version, but PL PHP has "view all" for each category and subcategory:
 ![pattern lab](https://cloud.githubusercontent.com/assets/383701/12068551/82b2800c-afde-11e5-9467-40ded646ae3d.png)

**Comment by bradfrost** [comment]
![pattern lab](https://cloud.githubusercontent.com/assets/383701/12068558/ab5ea968-afde-11e5-985e-5ea56e054c9f.png)

**Comment by bmuenzenmeyer** [comment]
FWIW, node does as screenshotted, but I think he's requesting one for all
of a certain pattern type... "All Atoms" for example.

This is a good plugin like other UI improvements mentioned, unless it makes
it to PHP core, which would make me prioritize it higher.

**Comment by bmuenzenmeyer** [comment]
Oh I should look more closely! This is actually a complete omission on my
part!

**Comment by gael-boyenval** [comment]
Sorry i'm late. 
@bradfrost : It could be nice to hilight this feature in a more distinctive way. Has a small button maybe, or with a different color. I think this elements should benefit from a different hierarchy, and graphic design. 
<img width="794" alt="capture d ecran 2016-02-01 a 14 29 11" src="https://cloud.githubusercontent.com/assets/14542464/12718722/b4a1e302-c8f0-11e5-83fd-df27146702a4.png">

I'm sorry, my comment should maybe be posted elsewhere…

**Comment by bmuenzenmeyer** [comment]
@gael-boyenval In my opinion that's a much more attractive solution than the current one.
I will likely just monkey-patch this to what Brad describes (or attempt to directly incorporate [the standard styleguide](https://github.com/pattern-lab/styleguidekit-assets-default). Your enhancement could perhaps be suggested there too.

**Comment by bradfrost** [comment]
@gael-boyenval Thanks for the design suggestion. As @bmuenzenmeyer mentioned, we're working on a revised PL header so we'll keep the spirit of this suggestion in mind.
