### ISSUE TITLE
dev branch: Config Paths only work with `./` prefix

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-node#222]
I'm seeing an issue when using paths in config that do not start with `./`: you can't do absolute paths or relative paths that start with `../`.

It appears to be from the use of `file.substring(2)` as an argument used in [`builder/patternlab.js:93`](https://github.com/pattern-lab/patternlab-node/blob/d01383a35e252423c46f890a744944aa26fd164a/builder/patternlab.js#L93) like this:

```js
pattern_assembler.process_pattern_iterative(file.substring(2), patternlab);
```

**Comment by EvanLovely** [comment]
Absolute paths that would start with `/Users/Evan/` end up being processed with this at beginning: `sers/Evan/`

**Comment by EvanLovely** [comment]
This affected my testing and hopeful use of https://github.com/pattern-lab/patternlab-node/pull/216

**Comment by bmuenzenmeyer** [comment]
Thanks Evan. 

Hmm I thought I tested this with source being a directory up - but clearly this needs a closer look before it lands. 
Will add this to : https://github.com/pattern-lab/patternlab-node/issues/220

**Comment by bmuenzenmeyer** [comment]
Now that https://github.com/pattern-lab/patternlab-node/pull/230 is in `dev`, it's time to test. Will do so tonight I hope

**Comment by bmuenzenmeyer** [comment]
Tested this. Looks great!
