### ISSUE TITLE
listItems with partials don't get data

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-node#224]
If I have something like this:

```html
{{# listItems.five }}
  {{> comment }}
{{/ listItems.five }}
```

And my `comment.mustache` has this:

```html
<div>
  <h3>{{title}}</h3>
  <p>{{description}}</p>
</div>
```

It then only displays "undefined" – the data isn't getting passed into the partial.

**Comment by bmuenzenmeyer** [comment]
I believe I have unit tests covering this.... will look into it.
Thanks for reporting!

**Comment by EvanLovely** [comment]
Turned out to be a weird bug on my side; apologizes for the bunk bug report!

**Comment by vogelinho** [comment]
@EvanLovely could you please describe how you solved the issue? we are experiencing the same problem on a windows host while it works on a debian system.
