### ISSUE TITLE
No ability to add `bodyClass`

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-node#225]
In the PHP PL, we could have JSON with a `bodyClass` that would... well: put a class on the body :smile:   I looked at `header.html`, but that's HTML and not Mustache, so I'm not sure what the best solution is. Changing `header.html` and `footer.html` to mustache files would solve this, and could potentially give us the ability to include an asset partial (i.e. `{{> assets }}` with all of our `<link>`s and `<script>`s from one place – just a thought.

**Comment by bmuenzenmeyer** [comment]
Duplicate of https://github.com/pattern-lab/patternlab-node/issues/169

**Comment by EvanLovely** [comment]
Got it - thanks! :+1:
