### ISSUE TITLE
Expose a Get Pattern By Key API Method

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#247]
Born out of conversation with Target folks, having a method exposed on `patternlab.js` like the below would open the door for interesting consumption scenarios beyond what export and configurable paths allow for.

``` javascript
var pattern = patternlab.getPattern('organisms-footer');
```

where pattern contains:

``` javascript
{
 'pattern' : ...,
 'template' : 'AbsolutePathToTemplate',
 'css' : 'AbsolutePathToCSS', //or preprocessor file
 'js' : 'AbsolutePathToJavascript',
 'json' : 'AbsolutePathToDataFile',
 ...
}
```
### Questions
1. What, if anything, should be within the pattern key? Anything tracked within the `patternlab.patterns[]` array could be useful.
2. What else should be contained in this call?
3. Does this call require `build()` to run first, or do use cases exist to only build a certain pattern (plus any partials it requires). Perhaps that'd be a `buildPatternByKey()` instead of a getter.

**Comment by bmuenzenmeyer** [comment]
@geoffp does this capture what we discussed?

**Comment by geoffp** [comment]
Yeah, I think it does! What strikes me about this is that this is (more or less) a public subset of what an oPattern probably ought to be.

All good questions which I can't answer yet. Should become more clear as we build out a site using a pattern library included as an NPM module. Any CSS dependencies of the requested pattern could be an issue. On #3, I hope we can avoid a build step, or maybe do kind of a half-build. We don't need to build out a static site to do this, but we do need to do a pass over all patterns to see what patterns we have to offer, I suppose.
