### ISSUE TITLE
Use bower for managing dependencies?

### ISSUE THREAD

**Issue by jfitzsimmons2** [pattern-lab/patternlab-node#27]
Enhancement Idea: Just throwing it out there, what do you think about using bower to manage dependencies like jquery, modernizr, and anything else that is in bower? Since it's a node project it seems to make sense. If not I might just do it for my own personal use :smile:

**Comment by bmuenzenmeyer** [comment]
For now, I will forgo bower integration to prevent another dependency. I should however update some of the example pattern code. Created https://github.com/pattern-lab/patternlab-node/issues/85 to handle this
