### ISSUE TITLE
BrowserSync still happens on the outer frame after full refresh on pattern

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/patternlab-node#273]
I am using Pattern Lab Node `v1.1.3` on `Mac|Linux`, using the `grunt|gulp` configuration.

##### Expected Behavior
You should be able to go to a pattern, or other non-`/` URL, such as those documented in http://patternlab.io/docs/pattern-linking.html, and BrowserSync should not inject itself into the UI chrome, or "outer frame".

##### Actual Behavior
It totally still does in that case.

##### Steps to Reproduce
 1. Select a pattern from the menu.
 1. Refresh the entire page.
 1. Witness two overlapping BS badges on the lower right. :cry:

**Comment by geoffp** [comment]
cc @vlrprbttst

**Comment by vlrprbttst** [comment]
+1!

**Comment by bmuenzenmeyer** [comment]
This is in dev. 

**Internal Note:**
There is not a "Closes #273" statement in any commit so it will likely not auto close when it reaches master.
