### ISSUE TITLE
Split up patternlab-node for better inclusion in existing projects and add a cli.

### ISSUE THREAD

**Issue by dopry** [pattern-lab/patternlab-node#281]
I've been starting to experiment with patternlab, but it seems to assume I am going to work out of a clone of a patternlab repo. In most of my uses cases I'm going to be adding patternlab to an existing project.  For me it would be nice to have a couple different packages to work with. I wanted to float my ideas here to see if @bmuenzenmeyer would be on board with these types of changes because it's a big departure from the current packaging.

* patternlab-node - The pattern lib builder library.

  This is essentially the contents of ./builder as it's own project and package. It shouldn't look for a config by default, instead config should be injected from a caller.

* patternlab-node-cli - a cli interface to the library 
   
  with commands like init, build, clean that setup a pattern lab project. should look for config file.
  maybe rename the default config file to patternlab.json (it's not well named to play nice 
  with other tools). could be quickly built with commander. 

  It would be nice to be able to type 
  ```bash
  npm install -g patternlab-node
  cd existing/project
  patternlab init ./src/patternlab  ./dist/styleguide
  ```

  Then end up with 
  * /existing/project/src/pattenlab/patterns
  * /existing/project/src/pattenlab/styleguide
  * /existing/project/patternlab.json

   ```json
   {
      "paths": { 
         "source": { 
            "root": "./src/patternlab"
         },
         "public": {
            "root": "./dist/styleguide"
         }
   }
   ```

  then follow up with 
  ```bash
  patternlab build
  patternlab serve
  patternlab clean
  ```

  to populate, serve, or clean
  * /existing/project/dist/styleguide

  and a 
  ```bash
  patternlab watch
  ```
  to watch for changes in 
  * ./existing/projects/src/patternlab
  and rebuild
  * ./existing/projects/dist/styleguide

* gulp-patternlab-node

  A wrapper for easily integrating pattern lab into gulp following the same configuration conventions as patternlab-node-cli

**Comment by bmuenzenmeyer** [comment]
Hi @dopry 

Thanks for the thoughtful proposal - there is a lot to like about it! I am glad that other people are just as interested as I in making the project more modular, (https://github.com/pattern-lab/patternlab-node/issues/272, https://github.com/pattern-lab/patternlab-node/pull/245#issuecomment-185963879).

I am taking a [step-wise approach](https://github.com/pattern-lab/patternlab-node/pull/280) to get the project there, with some prework to better align with the shared assets PL Node could consume in the future. I owe interested parties a better plan to do this, so we can gather feedback and arrive at a place that works for best consumption, upgrades, and integration with shared/generic PL repos.

Stay tuned

**Comment by bmuenzenmeyer** [comment]
This will likely become the mothership ticket for this large effort. Future work

**Comment by bmuenzenmeyer** [comment]
Most of this work is being done in https://github.com/pattern-lab/edition-node-gulp/issues/2
