### ISSUE TITLE
Browsersync reload task doesn't work

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#288]
I am using Pattern Lab Node `v1.3.0` on `Mac`, using the `grunt` configuration.
##### Expected Behavior

BrowserSync reloads my browser when the watch task calls it.
##### Actual Behavior

Browsersync reload doesn't appear to be doing anything. It is not possible to only reload styles, or javascript. Instead I have to run the `default` grunt task, which rebuilds the entire pattern repository and reloads the page.
##### Steps to Reproduce

Remove the `bsReload:css` task from the grunt watch task list (line 93 in https://github.com/pattern-lab/patternlab-node/blob/dev/Gruntfile.js).

The browser is reloaded anyway because of the `default`.

If you take a look at my [pull request](https://github.com/pattern-lab/patternlab-node/pull/289), you can see that the `bsReload` grunt task is not working.

**Comment by bmuenzenmeyer** [comment]
already tracked elsewhere
