### ISSUE TITLE
Pattern Lab has no useful error messages for missing meta patterns

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/patternlab-node#310]
I am using Pattern Lab Node `v1.2.2` on `Linux`, using the `gulp` configuration.

The setup: I set up a fresh Pattern Lab, and deleted all the default patterns and subgroups but left the top-level atomic buckets.

##### Expected Behavior
Since PL has a hard dependency on the `00-atoms/00-meta` patterns, it should have told me that I needed those files and how to put them back with Git -- maybe even done that *for me* after a prompt.

##### Actual Behavior
It just barfed a stack trace on me.

##### Steps to Reproduce
See above.

**Comment by bmuenzenmeyer** [comment]
Great idea Geoff. Taking other priorities into account and a target of 2.0-alpha in June, do you see this as 1.X or 2.X ? It wouldn't be difficult, but anything 1.X would need to be ported forward of course.

**Comment by geoffp** [comment]
Thanks! I mostly just wanted to capture this experience so I wouldn't forget it, but I'd say 2.0. Not super urgent.

**Comment by bmuenzenmeyer** [comment]
@geoffp this is actually covered in PL/Node 2.X now per https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/patternlab.js#L231-L248
