### ISSUE TITLE
Replacing Listitems for patterns doesn't work

### ISSUE THREAD

**Issue by DaSchTour** [pattern-lab/patternlab-node#311]
I am using Pattern Lab Node `v1.2.2` on `Windows`, using the `grunt` configuration.

##### Expected Behavior
Patternspecific listitems are used

##### Actual Behavior
Global listitems are used

##### Steps to Reproduce
Create pattern specific listitems

**Comment by bmuenzenmeyer** [comment]
Thanks for the report. 
We have a couple passing unit tests covering this expected behavior, but they no longer align fully with our testing approach. Can you provide reduced examples of the template file, the template.listitems.json file, and listitems.json file to further diagnose ?

**Comment by e2tha-e** [comment]
@DaSchTour This is working fine for me in the `dev` branch.
Can you follow these steps and see if it works?:
* create a local listitem file with path `02-organisms/02-comments/00-comment-thread.listitems.json`
* change the description property values
* visit `Pages -> Article` or `Organisms -> Comments -> Comment Thread`

**Comment by DaSchTour** [comment]
The error was my fault. I had a missing bracket. Build went through without any warning about the semantic error in the JSON and simply didn't use it because of the missing bracket :(
