### ISSUE TITLE
Thoughts on iframy

### ISSUE THREAD

**Issue by Ryuno-Ki** [pattern-lab/patternlab-node#312]
Let me draw your attention to iframy:
http://dev.edenspiekermann.com/2016/04/05/introducing-iframify/

It tries to emulate element queries by replacing each node with an iFrame containing it and drawing in of most CSS needed.

I can imagine there are shared problems so I wanted to put the link in here.
Found via CSS-Tricks.

**Comment by bmuenzenmeyer** [comment]
Hi @Ryuno-Ki 

I saw iframify mentioned around the time of Clarity Conf. I like the library and think it has a lot of neat applications beyond design systems.

1. At this time, the PL node front end, and therefore, all official front ends, utilize an iframe on the viewer, loading the users css, and therefore accomplish the same goal of using the ish controls on the top to mimic a viewport.

2. In the near future, the PL Node front end will be consume https://github.com/pattern-lab/styleguidekit-mustache-default and https://github.com/pattern-lab/styleguidekit-assets-default as dependencies, officially unifying our front end experience. Any changes or discussion would be best put there.
