### ISSUE TITLE
Can not render nested patterns.

### ISSUE THREAD

**Issue by failpunk** [pattern-lab/patternlab-node#320]
I am using Pattern Lab Node `v0.1.0` on `Mac`, using the `grunt` configuration.

##### Expected Behavior
I would expect to be able to render a required molecule in an organism and to also have that rendered molecule render any atoms it may require.

##### Actual Behavior
An organism renders a card
{{> molecules-card}}

the card requires that it render a label atom
{{> atoms-label}}

The static text of the card is rendered but the label atom is not.

##### Steps to Reproduce
Make an organism that renders a molecule that renders an atom.

**Comment by bmuenzenmeyer** [comment]
I am not seeing this in later version of PL/Node. Can you upgrade to 1.3.X and try again?

**Comment by bmuenzenmeyer** [comment]
closing due to lack of response

pattern rendering is working on 2.X
