### ISSUE TITLE
View all pages are not completely rendered

### ISSUE THREAD

**Issue by hinok** [pattern-lab/patternlab-node#322]
I am using Pattern Lab Node `v1.3.0` on `Mac`, using the `gulp` configuration.

##### Expected Behavior
Generated files inside `/public/patterns` are completely rendered.

##### Actual Behavior
```
/public/patterns/00-atoms/index.html
/public/patterns/01-molecules/index.html
/public/patterns/02-organisms/index.html
```

Templates are partially rendered. You can find there a lot of mustache in index.html {{you_know_what_i_mean}}

##### Steps to Reproduce

1. Clone repository
2. Configure to use gulp
3. Run in terminal
```
gulp patternlab
```

Look that `View all` pages inside iframe have mustache, see screenshot below

![probably-bug](https://cloud.githubusercontent.com/assets/1313605/14745562/2a89567c-08ac-11e6-9456-8dd9d4ed6066.png)

**Comment by bmuenzenmeyer** [comment]
Merged into `dev` thanks @hinok
