### ISSUE TITLE
What is the likelihood of ES2015 support and/or a Webpack build alternative in the near future?

### ISSUE THREAD

**Issue by elisechant** [pattern-lab/patternlab-node#325]

**Comment by bmuenzenmeyer** [comment]
Hi @elisechant .

To be straight to the point, this isn't even on my radar, and I have zero experience with webpack, though I am a bit familiar with Browserify. Our main-line development is going on in `dev-2.0-core` right now, with an emphasis on building a modular infrastructure in regards to core vs styleguide vs source and the like. This will hopefully make consumption, upgrades, and derivation much easier. But as far as "near-future hopes," no. (Near future to me is, for reference, through summer)

That said, could you elaborate on what would be required to adapt the project to your use case? Perhaps you, or someone else would want to take up the fight.

**Comment by bmuenzenmeyer** [comment]
Closed due to lack of response

**Comment by acariou** [comment]
Hi friend! 

I've got  a really good idea about how to spend my  next weekend, read more here  <http://ruzindufo.groundedcomic.com/e4rmxdm>

My best to you, arnaud
