### ISSUE TITLE
Refactor codebase to utilize lodash

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#328]
I've included lodash as a dependency in the `dev-2.0-core` branch and would like to utilize it more.

Also review https://github.com/alanjames1987/Node.js-Best-Practices

**Comment by geoffp** [comment]
Yes! I love Lodash.

**Comment by bmuenzenmeyer** [comment]
Ha - I don't have a hit-list of items yet, but I want to evaluate if it helps out more than the dependency adds in weight. Since PL is already rather mature feature-wise, it might be a silly time to add it, but we'll see. Add any specific placed here by all means.

**Comment by geoffp** [comment]
I think there are probably some nice opportunities to grow in kind of a functional direction. There's really good stuff for data structures and iteration. Once I finish the pattern object refactor merge, I'll look at some stuff!

**Comment by bmuenzenmeyer** [comment]
http://colintoh.com/blog/lodash-10-javascript-utility-functions-stop-rewriting#4)_deep-cloning_javascript_object

**Comment by e2tha-e** [comment]
@bmuenzenmeyer @geoffp Lodash is pretty badass. However, Extendify goes a step further for deep merging objects. And it bootstraps lodash.merge
https://github.com/bigShai/extendify

Curious to know if anyone knows of something even better for that purpose. Alternatives do the same thing, but are poorly documented, and have Rube Goldberg implementations.

**Comment by bmuenzenmeyer** [comment]
I am using lodash all over now - removing this issue as too vague.
