### ISSUE TITLE
Mustache link variables not working

### ISSUE THREAD

**Issue by danielemanca1983** [pattern-lab/patternlab-node#329]
I am using Pattern Lab Node on `Windows`, using the `grunt|gulp` configuration, although the issue I am about to mention occurs on 'Mac' too.

I am linking templates through the mustache variables like the following: {{ link.templates-templatename }}

Now the mustache variables work just fine, but when I export the project, the links do not work at all.

Has anyone come across this issue before?

**Comment by bmuenzenmeyer** [comment]
Can you retest this against Pattern Lab 2.0.0 and an edition?

**Comment by bmuenzenmeyer** [comment]
closing due to lack of response
