### ISSUE TITLE
Refactor PL code to reflect pseudo pattern changes in 0.7

### ISSUE THREAD

**Issue by joemcgill** [pattern-lab/patternlab-node#33]
Hey Brian,

I hope to try my hand at this if I can find some time in the next couple of days, but feel free move it along without me if need be.

Dave's explanation here:
https://github.com/pattern-lab/patternlab-php/issues/31#issuecomment-31946981

Gist of the patternPaths array
https://gist.github.com/dmolsen/8336146

Gist of the navItems array
https://gist.github.com/dmolsen/8335963

**Comment by bmuenzenmeyer** [comment]
This is quite an old issue and I dont see it having much relevance any more
