### ISSUE TITLE
Path is hard-coded in patternlab.js, not referencing config file

### ISSUE THREAD

**Issue by gobrendan** [pattern-lab/patternlab-node#336]
I am using Pattern Lab Node `v1.3` on `Mac`, using the `grunt` configuration.

##### Expected Behavior
Running 'grunt' or 'grunt patternlab' should run patternlab task with no errors.

##### Actual Behavior
I was receiving the following error in Terminal.

```
Running "patternlab" task
Warning: Path must be a string. Received undefined Use --force to continue.
```

##### Steps to Reproduce
Download version 1.3
In the 'source' directory, move the following directories into an 'assets' directory: css, images, js, fonts
In Terminal, run 'grunt patternlab'

I think I narrowed down the issue. Check line 269 of core/lib/patternlab.js

`media_hunter.find_media_queries('./source/css', patternlab);`

When I change the path to '/source/assets/css,' I don't receive errors. I tried changing the path to the following, but I still received the error noted above. For now, I'll keep the path '/source/assets/css'.

`path.resolve(paths().source.css)`

**Comment by bmuenzenmeyer** [comment]
Hi @gobrendan - good catch, I am a bit surprised there are still relative paths hanging around- and it looks like this persists into the [2.X branch](https://github.com/pattern-lab/patternlab-node/blob/dev-2.0-core/core/lib/ui_builder.js#L368) we are working on.
