### ISSUE TITLE
Implement Support for "Pattern Info Toggle Persistence / Default"

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#343]
Implement configuration for [Pattern Info Toggle Persistence / Default](https://github.com/pattern-lab/the-spec/issues/15) per passing vote from [PL-PIG](https://github.com/pattern-lab/the-spec/blob/draft/PL-PIG.md).

Relies on [styleguidekit-assets-default](https://github.com/pattern-lab/styleguidekit-assets-default/issues/23) companion issue.

**Comment by bmuenzenmeyer** [comment]
Done and release as part of an alpha.

**Comment by acariou** [comment]
Hi,

I've noticed a great improvement in your work, and I need your opinion about an issue, please take a look <http://jatroquisto.cphillips.us/xywtpuoc>

My Best, arnaud@neolame.com
