### ISSUE TITLE
Icomoon font is overriding my Icomoon font

### ISSUE THREAD

**Issue by gobrendan** [pattern-lab/patternlab-node#366]
I am using Pattern Lab Node `v1.3.0` on `Mac`, using the `grunt` configuration.

##### Expected Behavior

My custom Icomoon font should display as it does in the Icomoon app. 

##### Actual Behavior

I'm seeing Pattern Lab's icons in place of some of mine. For example, I have a Google Plus icon (I know, I know, lol) in my Icomoon font that's displaying in PL as a search icon (magnifying glass), which seems to match PL's search icon.

##### Steps to Reproduce

I'm not sure the best way for you to reproduce without having my Icomoon font. My debugging process was like this:

I manually deleted my Icomoon font files from the 'public' directory, refreshed the Icons 'Atom', and I see all but 5 icons showing up as little squares (as expected) -- the remaining 5 still show up. 

![image](https://cloud.githubusercontent.com/assets/835284/16118569/af921998-33a5-11e6-8791-13c531d32fe1.png)

I tried adding PL's Icomoon font to the Icomoon app to see what's in the file. This is what I see, which confirms what I think is happening. Given PL's CSS is being applied in each component, the PL icons are showing up. 

![image](https://cloud.githubusercontent.com/assets/835284/16118844/d5ef7f9e-33a6-11e6-9281-51b2e20765de.png)

For now, I'll try renaming my Icomoon font to "custom-icomoon" or something like that. I wonder if a good approach would be to rename Pattern Lab's Icomoon in the core directory. 

Thanks! This project rocks.

**Comment by bradfrost** [comment]
Hey @gobrendan, thanks for bringing this up. We've moved away from icon fonts altogether for Pattern Lab 2 (opting for inline SVG instead), so soon this shouldn't be a problem. In the meantime, yep renaming to "custom-icomoon" or something would fix things.

Thanks!

**Comment by bmuenzenmeyer** [comment]
Yup, as Brad mentions, PL/Node 2.0.0-alpha uses frontend assets that shouldn't interfere with your code far as we know.
