### ISSUE TITLE
Support foo.json files inside _data/ that are not listitems.json to be added to the global data object

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#375]
Dave informed me during WebDesignDay that a user should be able to structure files inside `_data/` as follows:

```
_data/
 - data.json
 - foo.json
 - listitems.json
 - zed.json
```

And expect `data.json`, `foo.json`, and `zed.json` to be merged together as global data.

**Comment by bramsmulders** [comment]
This is totally what i want, currently i'm fixing this issue by merging seperate data files into data.json before patternlab runs. But it would be awesome to have this included. :)

**Comment by bmuenzenmeyer** [comment]
Good to hear there is interest, I didn't even know the feature in PL/PHP existed until Dave Brad and I got together a couple weeks ago. I will try to prioritize this, but cannot promise anything concrete yet besides "soon"
