### ISSUE TITLE
Strange issue while nesting inside an a-Element

### ISSUE THREAD

**Issue by sergejr** [pattern-lab/patternlab-node#381]
Hi,

I've got a strange issue while nesting an a-elment inside a div inside an a.

This is the code inside the .mustache file.
```
<a href="#" class="firstLevel-a">
      <div class="div">
           <a href="#" class="secondLevel-a">test content</a>
      </div>
</a>
```
After rendering in the DOM I get following code:
```
<a href="#" class="firstLevel-a"></a>
<div class="div">
    <a href="#" class="firstLevel-a">
    </a>
    <a href="#" class="secondLevel-a">test content</a>
</div>
```

Any Ideas? There are no included Patterns.

Thanks and best regards.

**Comment by bmuenzenmeyer** [comment]
Morning!

This actually has nothing to do with Pattern Lab. What you wrote is invalid markup and the browser is attempting to correct it for you (cannot have nested anchor tags)

See this codepen for proof: http://codepen.io/bmuenzenmeyer/pen/11d012e19f55a966fc8678d1c1ed66b6

**Comment by sergejr** [comment]
Hey,

okay, but this markup is also rendered in a working project, that's live. So how Chrome can render it in this two ways?

**Comment by bmuenzenmeyer** [comment]
It might depend on doctype. Codepen uses HTML5 doctype as does Pattern Lab
