### ISSUE TITLE
Investigate merging usages of glob and diveSync

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#389]
Remove diveSync in favor of glob, both are dependencies.

**Comment by bmuenzenmeyer** [comment]
I dont see this as critical critical at this time Geoff unless you wish to take it on... it was just a captured thought.

**Comment by geoffp** [comment]
That's cool. I may, at a leisurely pace -- it would be a nice little piece of beer-drinking work.

**Comment by benhalverson** [comment]
@bmuenzenmeyer is this for v2.9 or v3.0?

**Comment by benhalverson** [comment]
Hi @geoffp are you actively working on this issue? Do you mind if I do it?

**Comment by bmuenzenmeyer** [comment]
@benhalverson sorry i missed your previous comment. i would target 3.0

**Comment by geoffp** [comment]
@benhalverson, nope, go for it!

**Comment by benhalverson** [comment]
@bmuenzenmeyer @geoffp 
This appears to work when I tested it with the pattern-lab-cli. I'm not sure how to write a proper test for it. 
``` 'use strict';
 const path = require('path');
-const diveSync = require('diveSync');
+const glob = require('glob');
 const chalk = require('chalk');
 const engineMatcher = /^patternengine-node-(.*)$/;
 const enginesDirectories = [
@@ -27,18 +27,20 @@ function isEngineModule(filePath) {

 function findEngineModulesInDirectory(dir) {
   const foundEngines = [];
+  glob(dir, function (err, filePath) {
+    if (err) {
+      console.log(`Error: ${chalk.red(err)}`);

-  diveSync(dir, {
-    recursive: false,
-    directories: true
-  }, function (err, filePath) {
-    if (err) { throw err; }
+    }
+    console.log('files', filePath);
     const foundEngineName = isEngineModule(filePath);
     if (foundEngineName) {
       foundEngines.push({
         name: foundEngineName,
         modulePath: filePath
       });
+    } else {
+      console.log(chalk.red("No engines found"));
     }
   });```

**Comment by bmuenzenmeyer** [comment]
@benhalverson one way might be to write a test that patternlab.js `getSupportedTemplateExtensions()` still works as expected, which internally loads the available engines and returns their extensions

note, that with travis, we install a number of engines pre-build https://github.com/pattern-lab/patternlab-node/blob/master/.travis.yml#L11

**Comment by benhalverson** [comment]
@bmuenzenmeyer I haven't forgot about this. Just busy with work 😄

**Comment by bmuenzenmeyer** [comment]
@benhalverson we all get busy. looking forward to it!
