### ISSUE TITLE
Document how to add other PatternEngines

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#392]

**Comment by tburny** [comment]
@bmuenzenmeyer Can we simply publish an artifact to NPM that contains the interface of a pattern engine?
This way:

- we can ensure via package.json that the interface matches the patternlab version. If we change the reqired interface, we simply exclude the PL version from using the newer one
- implementors know what to do via a unified JSDoc without digging to deep into PL

**Comment by bmuenzenmeyer** [comment]
I am in favor of this approach. @geoffp is the brain-child behind most of what Pattern Engines have become, and I strongly suggest we consult with him too.
Heck, it may help with our ongoing React PatternEngine.

**Comment by bmuenzenmeyer** [comment]
@geoffp could one argue that the functions and properties contained within https://github.com/pattern-lab/patternengine-node-handlebars/blob/master/lib/engine_handlebars.js construct most if not all of the expected API?

**Comment by geoffp** [comment]
Yeah, Handlebars has excellent coverage, except for the quirks that exist only for our extended dialect of mustache, like `expandPartials`. 

I think if I were implementing a new engine, my first move would be to clone an existing one and hope it's well documented in comments. I tend to think that some kind of barebones or stub engine would do a worse job than a real one at explaining itself. They're really very simple, they probably just need a thick coat of jsdoc.

**Comment by geoffp** [comment]
That said, it would be nice to have a wiki page or README that explains some of the setup process involving npm link and whatnot would be great, and any principles that don't feel quite at home in comments.

**Comment by bmuenzenmeyer** [comment]
This is done inside https://github.com/pattern-lab/patternlab-node/wiki/Working-with-PatternEngines
