### ISSUE TITLE
styleguideExcludes excludes pattern folders from navigation

### ISSUE THREAD

**Issue by bramsmulders** [pattern-lab/patternlab-node#393]
I am using Pattern Lab Node `v2.2.0` on `Mac`, with Node `v4.4.1`, using the `Gulp` Edition.

I've added the `templates` & `pages` to the `styleguideExcludes` setting.

##### Expected Behavior
This used to not render the templates & pages in de styleguide(view-all) view, but not exclude them from the navigation. 

##### Actual Behavior
Since pl-node `v2.2.0` the templates & pages are also removed from the navigation.

**Comment by bmuenzenmeyer** [comment]
confirmed bug

**Comment by geoffp** [comment]
Looks like patternlab.patterns (which I think is supposed to be the canonical data structure for patterns) is being overwritten by the sorted styleguidePatterns data structure in ui_builder.js, in buildFrontEnd().  I'll take a crack at it!

**Comment by geoffp** [comment]
Got a PR in.

**Comment by bmuenzenmeyer** [comment]
Pushed to 2.2.1 on github and npm

**Comment by bmuenzenmeyer** [comment]
Regressed on this in `2.4.0` - reopening
