### ISSUE TITLE
Add 'hooks' for configurability

### ISSUE THREAD

**Issue by ChrisBAshton** [pattern-lab/patternlab-node#394]
I discovered Pattern Lab through the excellent [Smashing Magazine article](https://www.smashingmagazine.com/2016/07/building-maintaining-atomic-design-systems-pattern-lab/) - love the tool, it's come at just the right time for me and my team!

I am using Pattern Lab Node `v2.0.0` on Mac, with Node `v4.4.6`, using the `Grunt` Edition. I installed Pattern Lab by cloning [Pattern Lab Node - Grunt Edition](https://github.com/pattern-lab/edition-node-grunt) and making proprietary commits from there.

Apologies in advance for the lengthy post, this is to get a discussion going rather than to log a specific issue.

## Pattern Lab installation

My first thoughts are to do with installation - have I gone about this the right way? Cloning the Grunt edition and then making commits from there feels a bit wrong, as it will be hard to benefit from future improvements to Pattern Lab. Is there not a way to 'pull in' a version of Pattern Lab that's a bit more decoupled from my pattern definitions?

## Asset automation

Unfortunately, I think one area Pattern Lab really falls down on (for our use case) is the lack of automation for assets. If I create a pattern which has HTML and CSS, I have to manually edit the header:

> Static assets like Javascript and CSS are not added automagically to your patterns. You need to add them manually to the shared pattern header and footer. ~ http://patternlab.io/docs/pattern-managing-assets.html

I appreciate that Pattern Lab is trying to maintain a layer of abstraction, and it starts getting quite complicated to automate this sort of thing, e.g. What if I need to compile SASS into CSS before I copy it across?

(In our case, we use SASS and I was able to add a `grunt-contrib-sass` dependency with this config:)

<details>
<summary>SASS configuration</summary>
```
    sass: {
      main: {
        options: {
          sourcemap: 'none'
        },
        files: [{
          expand: true,
          flatten: true,
          cwd: '.',
          src: [paths().source.patterns + '**/*.scss'],
          dest: './public/css',
          ext: '.css'
        }]
      }
    }
```
</details>

...but I appreciate that not everybody would want/need this, and pulling it in by default adds unnecessary bloat.

So how about some sort of 'hook' infrastructure?

Default projects could be shipped with some skeleton code:

```javascript
grunt.registerTask('beforeGrunt', function () {
  // 
});

grunt.registerTask('afterGrunt', function () {

});
```

...which would make it easy to hook in some SASS compilation behaviour.

Another difficult thing for us to work around is the lack of transparency in the head.mustache and footer.mustache files.

<details>
<summary>`<html class="{{ htmlClass }}">`</summary>
```mustache
<!DOCTYPE html>
<html class="{{ htmlClass }}">
  <head>
    <title>{{ title }}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />

    <!--STYLESHEETS_PLACEHOLDER-->

    <!-- Begin Pattern Lab (Required for Pattern Lab to run properly) -->
    {{{ patternLabHead }}}
    <!-- End Pattern Lab -->

  </head>
  <body class="{{ bodyClass }}">
```
</details>

There is currently no way of hooking into this, e.g. changing the value of `{{title}}` and, more fundamentally, no way of templating out the stylesheet logic. At the moment I'm resorting to writing a `<!--STYLESHEETS_PLACEHOLDER-->` comment, and writing a custom Grunt task to find and replace this comment in every compiled `.html` file, replacing it with my own array of `<link href=""` statements.

Are there any plans to enable more customisation of these files in future?

Thanks in advance!

**Comment by bradfrost** [comment]
Hey @ChrisBAshton,
Thanks for taking the time to write up these thoughts.

I can't really speak to the specifics as I'm not the one building the logic/programmatic stuff, but at first glance most of what you're talking about is achievable.

> Is there not a way to 'pull in' a version of Pattern Lab that's a bit more decoupled from my pattern definitions?

Yes, Pattern Lab is totally decoupled meaning that there's a Pattern Lab core that's separate than your generated code. You can read more about that [here](http://patternlab.io/docs/advanced-ecosystem-overview.html), but @bmuenzenmeyer or somebody might have to elaborate on how it all works.

> What if I need to compile SASS into CSS before I copy it across?

This is [how I work with Grunt](http://patternlab.io/docs/advanced-integration-with-grunt.html). I define tasks in a sequence which means that my Sass gets compiled before Pattern Lab gets generated before my JavaScript compiles before. Again, not sure of your specific set up, but I can attest that Pattern Lab works very well with build tools like Gulp or Grunt.

>  changing the value of {{title}}

Changing `title` can be done by changing the value in `data.json` and [page-specific json files](http://patternlab.io/docs/data-pattern-specific.html).

> no way of templating out the stylesheet logic. At the moment I'm resorting to writing a  comment, and writing a custom Grunt task to find and replace this comment in every compiled .html file, replacing it with my own array of <link href="" statements.

@bmuenzenmeyer @dmolsen would have to address this as I'm not quite clear on what you're looking to do, but I can tell you that Pattern Lab is get out of the way of users' frontend code. 

> Are there any plans to enable more customisation of these files in future?

I think these customizations are here. The [docs](http://patternlab.io/docs/) for the new version are still coming along, but I hope you'll find what you need there.

Thanks,
Brad

**Comment by bmuenzenmeyer** [comment]
> Is there not a way to 'pull in' a version of Pattern Lab that's a bit more decoupled from my pattern definitions?

This is the exact intention. `patternlab-node` which your grunt edition includes as a dependency, is the workhorse that should receive all the benefits. The edition code is really a sample we intend to people to make their own. You are right if there are bugs in the grunt tasks that need to get pushed out, some manual syncing or decisions will need to be made whether or not they apply to your situation.


> So how about some sort of 'hook' infrastructure?

and

> This is how I work with Grunt. I define tasks in a sequence which means that my Sass gets compiled before Pattern Lab gets generated before my JavaScript compiles before. Again, not sure of your specific set up, but I can attest that Pattern Lab works very well with build tools like Gulp or Grunt.

I don't plan to ship empty tasks. While that might save someone a bit of boilerplate code they would have to write themselves, it's really not toooooo bad IMO. I wrote up http://www.brianmuenzenmeyer.com/adding-common-gulp-tasks-to-pattern-lab-node as an example of what could be done within existing toolchains, and it seems helpful to include here too!

> There is currently no way of hooking into this, e.g. changing the value of {{title}} and, more fundamentally, no way of templating out the stylesheet logic.

I don't follow you here.... Pattern Lab header and footer are [designed to be edited by you](http://patternlab.io/docs/pattern-header-footer.html). Let us know if this isn't adequate?

Thanks for the interest in Pattern Lab Node. I hope the grunt version finds you well, but if you find something concrete amiss, please don't hesitate to open a specific issue!

**Comment by bmuenzenmeyer** [comment]
Two updates of sort:

Since [2.5.0](https://github.com/pattern-lab/patternlab-node/wiki/ChangeLog#v250) PL Node has supported data parsing and pattern inclusion inside head and foot. This should make them more flexible for teams.

Also, we (mainly @raphaelokon) are hard at work on a true CLI, which will make integration with existing toolchains even easier. 

Closing this issue for now.
