### ISSUE TITLE
Pattern markdown files with no description text render raw text into description field

### ISSUE THREAD

**Issue by ixley** [pattern-lab/patternlab-node#396]
I am using Pattern Lab Node `v2.1.1` on `Mac`, with Node `v6.3.0`, using the `Gulp` Edition.

##### Expected Behavior
If there is a title but no description in the pattern markdown file, PL should not show a description.

##### Actual Behavior
When there is a title in the markdown file, but no description, and no additional line breaks after the `---` delimiter, PL pulls the full text of the file and renders it in the description field.

##### Steps to Reproduce
Edit pattern markdown file to include
```
---
Title: Sample Title
---
```
with no following line breaks.

**Comment by bmuenzenmeyer** [comment]
Fixed with https://github.com/pattern-lab/patternlab-node/commit/9c4484482c1b7f53885d1055939d854353f337e6 - currently in `dev`

will close when this reaches master

**Comment by bmuenzenmeyer** [comment]
should make https://github.com/pattern-lab/patternlab-node/issues/349 quite easy too
