### ISSUE TITLE
Upgrading instructions (1.X to 2.X) in wiki is missing some information

### ISSUE THREAD

**Issue by josketres** [pattern-lab/patternlab-node#405]
Please add the following to the upgrading instructions in the wiki page in the section `Upgrading from Pattern Lab 1.X to 2.X`:

* in the file `00-meta/_00-head.mustache` replace `{% pattern-lab-head %}` with `{{{ patternLabHead }}}`
* in the file `00-meta/_01-foot.mustache` replace `{% pattern-lab-foot %}` with `{{{ patternLabFoot }}}`

It took me almost 1 hour reading the source-code to find out that this change was needed for the upgrade.

**Comment by bradfrost** [comment]
@josketres Thanks very much for this info! I've [updated the docs](http://patternlab.io/docs/upgrading.html#node) to include these changes. @bmuenzenmeyer, feel free to adjust milestone accordingly or whatever you need to do.

**Comment by josketres** [comment]
Cool!  
Are you also planning to add this info to the wiki (https://github.com/pattern-lab/patternlab-node/wiki/Upgrading)?
This is the documentation that I used for upgrading!

**Comment by bmuenzenmeyer** [comment]
I intend to update this too - since it contains information not present on the io site and people may find their way to it like you did.

**Comment by josketres** [comment]
👍

**Comment by bmuenzenmeyer** [comment]
I've updated the wiki to cover this, in addition to removing some confusing code
