### ISSUE TITLE
Want to consolidate redundant loops in pattern_assembler.getPartial()

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#406]
Writing this as a todo and reminder.

This function iterates through the same loop 3 times. I think we should consolidate this into just one loop:

https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/pattern_assembler.js#L23-L47

**Comment by bmuenzenmeyer** [comment]
I disagree with this change - as in most circumstances we want this method to exhaustively find patterns using the preferred syntax first. I can imagine scenarios where a pattern misses the first patternPartial syntax only to be erroneously picked up by a fuzzy syntax, yes?

**Comment by e2tha-e** [comment]
@bmuenzenmeyer Right. What you say makes sense. Closing this issue.
