### ISSUE TITLE
Maybe namechange pattern_assembler.findPartial to pattern_assembler.getPartial

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#407]
The public `pattern_assembler` function is named `findPartial` while the private function is named `getPartial`. This results in a couple points of confusion. The first is trying to figure out the rationale for this difference. The second is that `findPartial` is an `engine_mustache` public function, which performs a completely different operation. I think in `pattern_assembler`, it should be named `getPartial`.

**Comment by bmuenzenmeyer** [comment]
I have had the same thought a couple times - especially as the codebase has evolved and engines have a similar method.

:+1:

**Comment by bmuenzenmeyer** [comment]
@e2tha-e just so you know my crazy methods, i typically leave issues open until they reach master

**Comment by e2tha-e** [comment]
@bmuenzenmeyer Oops. Sorry. Will keep mind next time!
