### ISSUE TITLE
Conditional Statement from meta/foot.mustache isn't loaded

### ISSUE THREAD

**Issue by sergejr** [pattern-lab/patternlab-node#410]
I am using Pattern Lab Node `v1.2.3` on `Mac`, with Node `v4.4.7`, using the `Gulp ` Edition.

I've got a problem with showing special content on a special page with a type of conditional statement.

For example:

My `data.json` looks like this:
<img width="275" alt="bildschirmfoto 2016-07-28 um 10 21 03" src="https://cloud.githubusercontent.com/assets/5619563/17213833/696300b6-54d6-11e6-84b7-840a8e109754.png">

My `_meta/_01-foot.mustache` - which is loaded on every page - looks like this:
<img width="354" alt="bildschirmfoto 2016-07-28 um 10 19 52" src="https://cloud.githubusercontent.com/assets/5619563/17213844/7a4bb1de-54d6-11e6-882d-b14255766490.png">

Then I've got a Page Pattern called` 02-index-scroll.mustache` and a `02-index-scroll.json` that looks like:
<img width="177" alt="bildschirmfoto 2016-07-28 um 10 19 58" src="https://cloud.githubusercontent.com/assets/5619563/17213862/89ca36c6-54d6-11e6-9c68-d93aef47b8e4.png">

In this demo case the `<span class="test">foo 1</span>` should be visible on one specific Page, where the json key is set to true.

My rendered DOM looks like this:
![bildschirmfoto 2016-07-28 um 10 26 26](https://cloud.githubusercontent.com/assets/5619563/17213871/94fcc004-54d6-11e6-9c6b-4427e07b2e7a.png)

The span inside of the "if-statement" is not rendered on the page.

EDIT: I see, it's working if I create a new foot.mustache inside of the _patterns folder and include it to the page . But this way it's not dynamically anymore and the JS is loaded in a incorrect way. Or I have to load the JS-Files twice.

EDIT(2): the same conditional statements works inside the `_meta/_00-head.mustache`.
Tried to include a css-file only on the specific page. Works fine. So whats the problem with the `_meta/_01-foot.mustache`? In real I want to include specific JS.

Thank you.

**Comment by bmuenzenmeyer** [comment]
I believe this is related to https://github.com/pattern-lab/the-spec/issues/24 which is not yet implemented in Node

i will bump it in priority

**Comment by sergejr** [comment]
It's not about including pattern but including conditional statements to load specific libraries on specific pages for example. But including patterns in these files would also be great.

Thanks.
