### ISSUE TITLE
StyleModifer, loading patterns inside of patterns , and parsing of pseudo patterns.

### ISSUE THREAD

**Issue by mbulfair** [pattern-lab/patternlab-node#422]
I am using Pattern Lab Node `v2.3.0` on `Windows `, with Node `v4.4.7`, using the `Gulp` Edition.

##### Expected Behavior
Pseudo Patterns to render as in prior 1.x version

##### Actual Behavior
Mustache templates that contain other patterns with the {{styleModifer}} on the parent do not render at all. When {{styleModifier}} is off and using a .json the original mustache template will render and show the referenced pattern. However if trying from a pseudo pattern, the entire pseudo pattern will not render if that referenced pattern is in the parent's mustache template. Testing many scenarios, it does seem that some patterns will come up, but none of the values get passed on to them. I tried a simpler pattern and while the html showed up, none of the values were getting into the secondary pattern. It didn't even default to it's own .json file.

##### Steps to Reproduce
Create: 

- template.mustache
- template.json
- template~alt.json
- secondary.mustache
- secondary.json

Load the secondary into the first with a styleModifier and have the secondary also use a styleModifer.

**Comment by bmuenzenmeyer** [comment]
[_patterns.zip](https://github.com/pattern-lab/patternlab-node/files/416001/_patterns.zip)

@mbulfair does this set of patterns match your use case?

**Comment by mbulfair** [comment]
I've done a test with the patterns above. I've modified only 1 setting.

In the package.json

-   "patternlab-node": "^2.0.0" = **fails**
-   "patternlab-node": "pattern-lab/patternlab-node#dev" = **passes**

Both output version 2.3.0 if run gulp patternlab:version

**Comment by bmuenzenmeyer** [comment]
@mbulfair please let me know if `2.4.0` addresses this

**Comment by mbulfair** [comment]
@bmuenzenmeyer Changing back to ^2.0.0, version 2.4.0 installed, and everything builds as expected.
