### ISSUE TITLE
Use patternlab-node without grunt/gulp

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node#425]
Hi there.

Are there any plans to support patternlab-node without grunt/gulp (if not already possible)? 
My deploy is purely based on `npm scripts` and I would like to integrate `patternlab-node` to it, but I couldn't find anything in wiki section about for `patternlab-node cli`. 

Cheers.

**Comment by bmuenzenmeyer** [comment]
I have some dreams to do this but it's not on my current roadmap.

It really wouldn't be that hard if core assumed that what was in `source/` was good to go and only processed it or copied it.  

Doing this would have some other benefits too, like making editions simpler and more inline with how PL/PHP works.

**Comment by bmuenzenmeyer** [comment]
Consider this bumped in priority. Curious how many others would like to see it?

**Comment by raphaelokon** [comment]
Thanks for your honest response. 

I need it for a current project :> So likely that I may just give it a dash when I find time. Grunt/Gulp are mainly (platform harmonising) wrappers around core (bash) functionality – and another config nightmare for me. 

Having a unified core would make the other editions simpler in theory.

**Comment by Loque-** [comment]
Yes please! I am spending a lot of time simplifying tricky gulp/grunt tooling with lovely semantic npm scripts.

Thank you for the amazing work on this fantastic project. I appreciate the ticket too, as I was about to try and implement this without gulp!

**Comment by raphaelokon** [comment]
@Loque- Thanks. I was looking into the core and figuring out how this is working. I did some fiddling locally on it – making it a true standalone CLI tool.

**Comment by bmuenzenmeyer** [comment]
Cross-linking https://github.com/pattern-lab/patternlab-node/issues/281 this issue for those who may have missed it. I am going to start thinking about how this would work.

**Comment by renestalder** [comment]
A big +1 on this. Would love to see direct CLI access which makes it easy to use it with the build tool of your choice.
