### ISSUE TITLE
Pattern Links in "view all" ignore configured outputFilePaths

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/patternlab-node#437]
I am using Pattern Lab Node `v2.4.2` on `Mac`, with Node `v4.4.7`, using the `Gulp` Edition.

##### Expected Behavior
When using the following config, which supports the use of Underscore templates:
```json
"outputFileSuffixes": {
    "rendered": "-rendered",
    "rawTemplate": "",
    "markupOnly": "-markupOnly"
}
```
The pattern links in "View All" should end in "-rendered.html".

##### Actual Behavior
They end in ".html", and in this configuration, that gets you the rawTemplate version and breaks navigation due to the absence of essential scripts on the page in the iframe.

This appears to be due to widespread use of the precomputed patternLink value on Pattern objects. I propose to eliminate this field and replace it with a getPatternLink() method that takes the patternlab object as an argument so it can calculate the correct value on the fly based on the user's config.

**Comment by mbulfair** [comment]
I am now seeing this only under each folder, individual view all are working. So for example

- atoms
  - color
     - colorpattern1
     - colorpattern 2
     - view all (works)
-viewall (broke)

**Comment by geoffp** [comment]
@mbulfair, that's actually a different issue. Mine is that these links don't work:
![screen-shot-2016-08-17-at-2 57 39-pm](https://cloud.githubusercontent.com/assets/76232/17751107/2f71e9ca-648b-11e6-8010-4253c4366ff1.png)

**Comment by bmuenzenmeyer** [comment]
@geoffp I think what you propose is a good way to address this issue going forward, versus what I've been attempting to do (monkey-patch replace when issues crop up)

**Comment by bmuenzenmeyer** [comment]
@geoffp FWIW this is all working for me right now on `dev` (probably why I thought this was ready for the big time in general...) I wonder if it's a platform issue, not working on Macs? if so, perhaps the solution is easier that we thnk

![viewall](https://cloud.githubusercontent.com/assets/298435/17799524/f5310892-65a0-11e6-98f5-3900a92912b3.gif)

**Comment by bmuenzenmeyer** [comment]
Or, is this only an issue when you deviate from the default `outputFileSuffixes.rendered` of `''` ? That would make more sense, says my rubber ducky.

**Comment by bmuenzenmeyer** [comment]
Oh, I see what you are experiencing now after I configure an outputFileSuffix. 

I tried monkey-patching `ui_builder.js` at line 353 with

`pattern.patternLink = pattern.patternLink.replace('.html', patternlab.config.outputFileSuffixes.rendered + '.html');` but it did not resolve this issue. I see that patternLink is used in lineage too so doing your more global fix is a better long-term solution anyways

**Comment by geoffp** [comment]
Yep, you've got it :)
