### ISSUE TITLE
Tests for Underscore, Handlebars, and Twig fail

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/patternlab-node#438]
I am using Pattern Lab Node `v2.4.2` on `Mac`, with Node `v4.4.7`, using the `Gulp` Edition.

##### Expected Behavior
Unit tests for all engines should run.

##### Actual Behavior
Tests for Underscore, Handlebars, and Twig fail due to missing outputFileSuffix blob in the included patternlab-config.json.

I'll do a PR to get the config that we provide by default in the gulp edition into this, as well as make that the default.

**Comment by bmuenzenmeyer** [comment]
Travis can now load engines during test (at least what has been `npm publish`ed) 

https://travis-ci.org/pattern-lab/patternlab-node/builds/153287099

**Comment by geoffp** [comment]
Excellent!
