### ISSUE TITLE
Watching pattern updates seems to get locked

### ISSUE THREAD

**Issue by mbulfair** [pattern-lab/patternlab-node#439]
I am using Pattern Lab Node `v2.4.2` on `Windows`, with Node `v4.4.7`, using the `Gulp ` Edition.

##### Expected Behavior
Change to a mustache file happens, hit save, patterns runs the build task, then reload page.

##### Actual Behavior
Change happens, it builds, then reloads, and builds a second time. On occasion when "cleanPublic" is set to true in the config, this step will fail with unable to write to the public/patterns/ folder.

In the screenshot, first arrow is when a change was triggered, the second arrow is where it starts to hang up.
![0unjwul](https://cloud.githubusercontent.com/assets/5325543/17751549/942762fa-6495-11e6-855c-631789b7fab1.png)

##### Steps to Reproduce
`gulp patternlab:serve` 
Make a change to a pattern
Observe console

**Comment by bmuenzenmeyer** [comment]
possibly related

![image](https://cloud.githubusercontent.com/assets/298435/17775678/edd615a6-651e-11e6-9045-9df6acd3cf88.png)

**Comment by bmuenzenmeyer** [comment]
@mbulfair can you try switching your `patternlab-node` entry in the dependencies object of your `package.json` to `pattern-lab/patternlab-node#dev` and run `npm update` to see if this issue is resolved?

**Comment by mbulfair** [comment]
This bug seems to be resolved. I managed to make several mustache changes, it reloaded after the build, the navigation bar didn't duplicate, nor did I see a error for a nonemptydir for patterns.

**Comment by bmuenzenmeyer** [comment]
yay - good to hear!
