### ISSUE TITLE
The styleModifier variabile keeps previous values

### ISSUE THREAD

**Issue by dharmastyle** [pattern-lab/patternlab-node#444]
I am using Pattern Lab Node `v2.3.0` on `Mac`, with Node `v6.2.2`, using the `Gulp` Edition.

##### Expected Behavior

When looking at a single pattern, the `styleModifier` should be empty (or ignored).

##### Actual Behavior

When `styleModifier` is used in a page to modify an included pattern, the single pattern inherits that styleModifier instead of being clean.

##### Steps to Reproduce

1. create a pattern `#1` with a `styleModifier`
2. include it in a new pattern `#2` and set a styleModifier for the `#1` pattern
3. compile
4. browse to the single pattern `#1`
5. it will have the `styleModifier` set in `#2` instead of being clean

**Comment by bmuenzenmeyer** [comment]
I've uploaded my test case which shows this functionality working as designed.
Please tell me if I have you reproduction wrong, or (better) supply your own.
[_patterns.zip](https://github.com/pattern-lab/patternlab-node/files/444061/_patterns.zip)

![image](https://cloud.githubusercontent.com/assets/298435/18076997/ef8ecd02-6e47-11e6-929c-52158f74251d.png)

**Comment by gfnool** [comment]
Hi,

@bmuenzenmeyer, to see the bug in action you should put the modified pattern as the last of the patterns that use that particular include.

I'm having the same problem and to see the bug in action I created these patterns:

**01-button.mustache**
`<div class="button {{styleModifier}}">Button</div>`

**02-include-mod.mustache**
`<p>This is a pattern with a modified pattern included</p>
{{> atoms-button:button--mod}}`

But then, if you add a third pattern without modification the bug disappears

**03-include.mustache**
`<p>This is a pattern with a pattern included</p>
{{> atoms-button}}`


In your example you should put the modified button in "Zzanother" to see the bug.

**Comment by maddesigns** [comment]
I can confirm this bug - mods going down to atoms.

**Comment by bmuenzenmeyer** [comment]
@gfnool thanks for the additional steps - I've reproduced now. Should be easy enough to catch with a unit test and then fix.

**Comment by bmuenzenmeyer** [comment]
I've pushed this to `dev` with a unit test, a fix, and confirmed fix against our test patterns.

You can update your `package.json` to `patternlab-node#dev` and run `npm update` to confirm the fix.

If I get some positive vibes from you all, I will start version build.

**Comment by gfnool** [comment]
I confirm the fix, using #dev 2.5.0.
Thanks!
