### ISSUE TITLE
Support patternengine name rather than file extension in the template tab

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/patternlab-node#446]
This is to support display of the pattern engine name in the template tab, should there be a positive response from Dave and Brad to https://github.com/pattern-lab/styleguidekit-assets-default/issues/43.

This is one of the issues we touched on in https://github.com/pattern-lab/the-spec/issues/26.

**Comment by bmuenzenmeyer** [comment]
Released in PL Node 2.4.4
