### ISSUE TITLE
possibility to hide the "ALL"-button in main menu 

### ISSUE THREAD

**Issue by mremergo** [pattern-lab/patternlab-node#453]
For projects that include some styling with absolute and even fixed positioning, the section "ALL" with a combined view on all of your elements gives a rather, let's say chaotic impression. The styling for the individual elements is actually correct but they are not intended to be mixed. 
You wouldn't want that section to be visible on a customer-showcase, so it would be of use to include a possibility (maybe in the config-file) to hide the "ALL"-button in the menu.

**Comment by bmuenzenmeyer** [comment]
FWIW, you can tackle the absolute and fixed positioning problem by adding additional statements inside the `pattern-scaffolding.css` file. This is one of it's primary use-cases. 

Removing the `ALL` button would be a spec enhancement which needs to be brought up across both platforms.

**Comment by bmuenzenmeyer** [comment]
`Pattern Lab 2.6.0-alpha` should now allow motivated individuals  to create plugins. The behavior you describe could be done with such a plugin.

Read more: https://github.com/pattern-lab/patternlab-node/wiki/Creating-Plugins
