### ISSUE TITLE
Pattern Subtype View All should be at the end of each menu / submenu

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#456]
I introduced this behavior with `2.4.0` but it's a low priority for me. If anyone wants to through their hat in the ring, please do.

**Comment by timhartmann** [comment]
It would be great to show patternSubtype in the menu of pattern lab. Does it possible soon?

**Comment by bmuenzenmeyer** [comment]
can you elaborate on what it is you are looking for?

![image](https://user-images.githubusercontent.com/298435/36269076-dd07ed6c-123d-11e8-8430-cc092f780c1f.png)

In this context above "Global" is a subtype and it is displayed. This issue was to fix a small "bug" that dealt with the order in which the "View All" link showed up in the navigation.

**Comment by timhartmann** [comment]
I want a subfolder like in your screenshot for templates. If I add a subfolder to templates I can not see it in the navigation under templates.

**Comment by bmuenzenmeyer** [comment]
this is by design and a duplicate of https://github.com/pattern-lab/patternlab-node/issues/660 - to be resolved via changing [the spec](https://github.com/pattern-lab/the-spec)
