### ISSUE TITLE
ListItems are not compiled when included using a pattern parameter

### ISSUE THREAD

**Issue by gfnool** [pattern-lab/patternlab-node#457]
I am using Pattern Lab Node `v2.4.0` on `Mac`, with Node `v6.2.2`, using the `Gulp` Edition.
##### Expected Behavior

When a pattern containing a `listItems` loop is included in another pattern, the list loop should be printed out, even if some data are overwrite from the parent pattern 
##### Actual Behavior

The included pattern do not show the list
##### Steps to Reproduce

create a child pattern like this:

```
{{ title }}
<ul>
{{# listItems.four }}
   <li>{{ headline.short }}</li>
{{/ listItems.four }}
</ul>
```

import the child pattern in a parent like this:

```
{{> atoms-list(title: "title") }}
```

the parent pattern it will not contain the list

Here's a screenshot
![schermata 2016-08-31 alle 14 22 10](https://cloud.githubusercontent.com/assets/5812801/18128499/597de254-6f86-11e6-9aac-66df0653fc1a.png)

**Comment by dennisfrank** [comment]
Yep. Having the same issue issue (Pattern Lab Node `v2.5.1` on `Mac`, with Node `v5.3.0`, using a custom `Grunt ` Edition). :confused:

**Comment by gael-boyenval** [comment]
+1 same here.

**Comment by st3phan** [comment]
Too bad this is still an issue. Any chance you can fix this?

Patternlab version: `"patternlab-node": "2.9.1"`

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Is this something I can help with? Had some people asking me this …

**Comment by bmuenzenmeyer** [comment]
hey @raphaelokon 

I think these are two separate use cases here - so it's a bit much to unpack.

* The most recent by @st3phan looks very similar if not identical to https://github.com/pattern-lab/starterkit-mustache-acidtest/issues/1 
* the OP's has more to do with listitem parsing

Either way, more careful processing of these nuances is needed... 

What I've tried to do is isolate test cases into their own files in a starterkit when PL PHP parity is a concern, and also of course have some unit test coverage.  

Which use case would  you like to help with, or what are you most comfortable with.

**Comment by raphaelokon** [comment]
@bmuenzenmeyer I'd pickup the list item parsing one
/cc @dennisfrank

**Comment by bmuenzenmeyer** [comment]
👍 feel free to ask any questions along with way here or on gitter

**Comment by bmuenzenmeyer** [comment]
@st3phan can you upgrade and retest? I think fixing https://github.com/pattern-lab/patternlab-node/issues/539 fixed your issue - though likely the OP use case is still a problem.

**Comment by st3phan** [comment]
Upgraded from `2.9.2` to `2.9.3` and it's now working. #539 looks identical indeed. Thanks!

**Comment by bmuenzenmeyer** [comment]
![](https://media.giphy.com/media/102VfCWF40oAuI/giphy.gif?response_id=591f03ccde8c4be4cec96c8e)

**Comment by st3phan** [comment]
ROFL 💯

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Can we have a proper test case for this?

**Comment by bmuenzenmeyer** [comment]
Hey @raphaelokon 

Not sure if you are asking me for steps to reproduce, the process I would undergo, or for a rundown of what I think the problem is from the OP, so I will give you my braindump approach.

My first steps would be to attempt to recreate the OP's issue using the supplied patterns and circumstances, asking him directly for more information as needed. (It happened so long ago I cannot remember if I recreated it myself.) If I can recreate the issue in an instance of Pattern Lab, I then create a branch off of core with as reduced a test case as possible as fixtures, and attempt to create a failing unit test off of it.  This is roughly what I did for https://github.com/pattern-lab/patternlab-node/pull/663

Let me know here or on gitter if that makes sense.

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Yeah, sorry. I was asking myself if any of the list items tests already reflect the OPs issue.

**Comment by bmuenzenmeyer** [comment]
@raphaelokon np - I think that this issue exists it proof that the existing tests are not adequate. you will see some unit test coverage however inside `list_item_hunter_tests.js`

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Aye. I pinged you on Gitter

**Comment by bmuenzenmeyer** [comment]
I've manually recreated this issue too

![image](https://cloud.githubusercontent.com/assets/298435/26403391/b1463dc6-4053-11e7-873a-85ac2a325da8.png)

Now to look into getting that failing unit test in place... will check out what you have Raphael

**Comment by raphaelokon** [comment]
Cheers Brian. If you could amend the test case – I'd take it from there :-)

**Comment by bmuenzenmeyer** [comment]
@raphaelokon I will annotate that commit quick.

**Comment by raphaelokon** [comment]
Hmm … those tests are passing fine for me. I'll look into it

**Comment by raphaelokon** [comment]
Seems like we are excluding the `public` folder but trying to re-add the `testDependencyGraph.json`
https://github.com/pattern-lab/patternlab-node/blob/master/.gitignore#L10-L12

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Can we have a look into this one as well?
