### ISSUE TITLE
View pseudo-pattern leads to 404

### ISSUE THREAD

**Issue by thenickname** [pattern-lab/patternlab-node#458]
I am using Pattern Lab Node `v2.5.0` on `Mac`, with Node `v5.5.0`, using the `Gulp` Edition.

##### Expected Behavior
When defining a pseudo pattern, e.g. `button~--primary.json` to describe a variation of a button, another instance of the component should be displayed and correctly linked to a sub-page showing only the variation

##### Actual Behavior
Clicking on the title of a generated pseudo pattern leads to `404` `Cannot GET /patterns/`, instead of linking to the "Button Primary" page

##### Steps to Reproduce
1. Create a simple pattern like `atoms/buttons/button.mustache`
2. Create a pseudo pattern for the previously created pattern, e.g. `atoms/buttons/button~--primary.json`
3. Go to Atoms --> Buttons --> View All
4. Verify that the default button and the pseudo pattern "Button Primary" are both displayed correctly
5. Click on the linked headline "Button Primary"
6. `Cannot GET /patterns/` occurs

**Comment by bmuenzenmeyer** [comment]
Confirmed this bug.

**Comment by bmuenzenmeyer** [comment]
Confirmed this bug

**Comment by bmuenzenmeyer** [comment]
@thenickname this is in `dev` now.

**Comment by thenickname** [comment]
@bmuenzenmeyer thanks a lot! Switched to dev for now.

**Comment by bmuenzenmeyer** [comment]
@thenickname FYI this has already made it to master, when the issue was auto-closed.  

so switching back to `patternlab-node: '^2.0.0' and running an `npm update` will put you back on a more stable channel
