### ISSUE TITLE
blank page display with deep included patterns (with 2.5#dev)

### ISSUE THREAD

**Issue by gael-boyenval** [pattern-lab/patternlab-node#461]
I am using Pattern Lab Node `2.5.0` on `Mac`, with Node `v6`, using the `Gulp` Edition.

## Expected Behavior

for a given pattern :
```mustache
{{> atom-btn }}
```
in a template `template-x` we call the btn :
```mustache
{{> atom-btn }}
```
then call the template in `page-y`
```mustache
{{> template-x }}
```
the page should display the btn

## Actual Behavior

display a blank page (no error, nothing at screen appart for the patternlab UI )

##### Steps to Reproduce

create :
 
atoms/btn
```mustache
<a class="a-btn">text</a>
```

templates/x
```mustache
{{> atoms-btn }}
```

pages/y
```mustache
{{> templates-x }}
```

**Comment by bmuenzenmeyer** [comment]
[source.zip](https://github.com/pattern-lab/patternlab-node/files/449749/source.zip)

Reproduction files
