### ISSUE TITLE
Rewrite tests to use a node friendly test suite 

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node#466]
The current implementation utilizes `grunt-contrib-nodeunit`. 
I suggest to use a more node-friendly test suite like `tap`. There are many benefits to use a simple and concise test suite:
- https://remysharp.com/2016/02/08/testing-tape-vs-tap by @remy
- https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.rt4fnsr8r by @ericelliott

**Comment by bmuenzenmeyer** [comment]
As we discussed, the unit tests are in need of a level up. I love this idea.

**Comment by raphaelokon** [comment]
Cheers … I already utilizing `tap` (node-tap) for the CLI test. Also: the current tests `npm test` run (or try to run) Travis locally. This should probably be changed for better dev experience.

**Comment by dbradf** [comment]
Hi,

I've added tap support to the project and converted over the of the test files to get started with this issue. I've opened the above pull request.

**Comment by raphaelokon** [comment]
That's great @dbradf  I use `tap` on the patternlab-node-cli as well.
