### ISSUE TITLE
Investigate and Standardize Pattern Export with PL PHP

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#470]
Confirm or standardize the behavior of pattern export with that of PHP.

Node: https://github.com/pattern-lab/patternlab-node/wiki/Configuration#pattern-export 

vs

PHP http://patternlab.io/docs/advanced-exporting-patterns.html

**Comment by raphaelokon** [comment]
Is the pattern export feature just exporting the `source` without `css/`, `js/` and `favicon.ico`?

How does the `patternExportPatternPartials ` influence the export?

**Comment by bmuenzenmeyer** [comment]
> Is the pattern export feature just exporting the source without css/, js/ and favicon.ico?

I have yet to confirm, but I think it might actually export `public/patterns/`


> How does the patternExportPatternPartials influence the export?

That will likely be deprecated.

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Okay … I made the `exportDir`  configurable – and did not implement `patternExportPatternPartials`.

**Comment by ringods** [comment]
PL moved on to be mainly a Node project. Is this issue still applicable then?

**Comment by bmuenzenmeyer** [comment]
no this can be closed
