### ISSUE TITLE
Rendering of nested patterns in mustache lists not working

### ISSUE THREAD

**Issue by thenickname** [pattern-lab/patternlab-node#472]
I am using Pattern Lab Node `v3.10.7` on `Mac`, with Node `v5.5.0`, using the `Gulp` Edition.

##### Expected Behavior
Nested patterns render in mustache lists.

##### Actual Behavior
When using a mustache list to repeatedly render e.g. an organism pattern, that includes nested patterns (some molecules), the molecules do not show up. More accurately, they did show up once but then never agian.
What *does* show up though are variables directly included in the organism, for example {{someStuff}}.

There is one way to make the nested patterns show up (some kind of workaround, I guess): Pseudo Patterns (variations) do render correctly.

##### Steps to Reproduce
1. Create a pattern that includes nested patterns (an organism with molecules for example)
2. Create a data array to fill the organism with data and render pattern repeatedly using the mustache list feature
3. See how nested patterns don't render. The generated HTML shows no sign of the nested patterns.

**Comment by bmuenzenmeyer** [comment]
I am on Pattern Lab Node `v2.5.1` and nested rendering is fine. Reading a different update of yours, you might be on an old version. Please update and let me know if it's still an issue. If it is, please zip up your test files.

I am using `starterkit-mustache-demo` to confirm this is working.

![image](https://cloud.githubusercontent.com/assets/298435/18348666/4ec1b874-7592-11e6-889f-423d009ec577.png)

**Comment by thenickname** [comment]
thanks a lot!! I will check it out.

**Comment by thenickname** [comment]
oh thanks a lot it actually *is* working. Seems there was something wrong with my patternlab version.

Thanks for taking your time and checking it out.
