### ISSUE TITLE
If defaultPattern is the only pattern of its type, that pattern gets eliminated entirely

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#477]
I am using Pattern Lab Node `v2.5.1` on `Mac`, with Node `v4.3.0`, using the `Gulp ` Edition.

##### Expected Behavior
* Given that the `defaultPattern` in `patternlab-config.json` is set to "pages-homepage"
* And that `source/_patterns/04-pages/00-homepage.mustache` is a valid Pattern Lab pattern
* And that it is the only pattern in `source/_patterns/04-pages`
* It is expected that this pattern is rendered on the Pattern Lab index page (http://localhost:3000), and that the Pages type appears in the navbar.

##### Actual Behavior
No pattern is rendered on the Pattern Lab index page, and the Pages type does not appear in the navbar.

##### Steps to Reproduce
Create `source/_patterns/00-atoms/paragraph.mustache`:
```
<p>paragraph</p>
```
Create `source/_patterns/04-pages/00-homepage.mustache`:
```
{{> atoms-paragraph }}
```
* When `defaultPattern` in `patternlab-config.json` is set to "all", pages-homepage renders correctly.
* When `defaultPattern` in `patternlab-config.json` is set to "pages-homepage", pages-homepage disappears entirely.
* If you copy `source/_patterns/04-pages/00-homepage.mustache` to `source/_patterns/04-pages/01-newpage.mustache`, the Pages menu appears in the navbar, but the `homepage` link does not appear within it.
* If you set `defaultPattern` in `patternlab-config.json` to "all", everything works correctly.

**Comment by bmuenzenmeyer** [comment]
I think you are encountering expected behavior, to an extent. Please check out https://github.com/pattern-lab/the-spec/issues/13 and https://github.com/pattern-lab/patternlab-node/wiki/Configuration#defaultpatttern for mroe info.

I think there is also a `2.5.1` bug with defaultPattern staged for release here: https://github.com/pattern-lab/patternlab-node/issues/467

**Comment by e2tha-e** [comment]
Ok. I read the Wiki and see that the defaultPattern is not supposed to show in the navbar. So if the defaultPattern shows on the index page in the next release, please close this issue.

**Comment by e2tha-e** [comment]
This has been fixed on release `v2.6.0-alpha`. Closing this issue.
