### ISSUE TITLE
Add proper jsdoc comments to core/lib/patternlab.js

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#488]
> Code is read more than it is written.

Akin to work already done in `core/lib/ui_builder.js`

Read the code, and describe each function and parameters accordingly.

https://en.wikipedia.org/wiki/JSDoc

**Comment by yarwest** [comment]
@bmuenzenmeyer Hey! I'd love to document this file for you :) I have experience working with JS and JSDoc.

**Comment by tburny** [comment]
@yarwest If you are still interested it would be amazing if you could help :)

**Comment by yarwest** [comment]
@tburny I'll take a look later today :)

**Comment by rouzbeh84** [comment]
Hey @bmuenzenmeyer it looks like this one may be pretty well documented? Might want to take another look and see if it's already done :)
