### ISSUE TITLE
Add proper javadoc comments to core/lib/utilities.js

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#492]
> Code is read more than it is written.

Akin to work already done in `core/lib/ui_builder.js`

Read the code, and describe each function and parameters accordingly.

https://en.wikipedia.org/wiki/JSDoc

**Comment by istx25** [comment]
@bmuenzenmeyer: Hey there! I'd be interested in contributing. I'm new to JavaScript but I'm trying to get into the community more. I think starting with docs would be a good place to begin. :)

**Comment by yarwest** [comment]
@istx25 just beat me to it, but if there is more documentation work to be done, I'd love to help. I have experience with JS and documentation

**Comment by istx25** [comment]
If you wouldn't mind providing me with some help, that'd be great. There's a bunch of other issues tagged with Hacktoberfest on this repository though. Lots of doc stuff!

**Comment by yarwest** [comment]
@istx25 yeah, I noticed that too :) I'm sure the two of us can tackle them all and divide up the work

**Comment by istx25** [comment]
Can I have an email address for you? @yarwest

**Comment by bmuenzenmeyer** [comment]
@istx25 @yarwest welcome! 

Yes I am trying to load up the repository with things that can introduce people to the code base and help out. no contribution is too small.

For these javadocs, the thing I usually do is let my IDE/editor help auto-generate them. I use webstorm, so I follow these instructions: https://www.jetbrains.com/help/idea/2016.2/creating-documentation-comments.html 

Your IDE of choice will likely be different. I don't suggest writing them by hand, but I suppose you could!

If you follow that wikipedia link you should find a decent overview of what javadoc is. You can also see that the sample file already has lots of these: https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/ui_builder.js#L71-L76

So the task would be to succinctly add these to each function. 

Thanks for the interest!

**Comment by yarwest** [comment]
@istx25 surely, my email is yarnoboelens@gmail.com

@bmuenzenmeyer great :)
