### ISSUE TITLE
View All is not working on some patterns

### ISSUE THREAD

**Issue by vpanugaling** [pattern-lab/patternlab-node#549]
I am using Pattern Lab Node `v2.5.1` on `Windows`, with Node `v6.9.1`, using the `Gulp` Edition.

##### Expected Behavior
Click "view all" in the menu should display all patterns for a given category.
e.g.  css-utilities > view all (display all css utilities patterns)

##### Actual Behavior
Click "view all" in the menu is displaying an error =>
ex: css-utilities > view all => Cannot GET /patterns/06-css-utilities/index.html?1477998955055

Most of my patterns does have patternSubtypes or 2nd level menu and I have patterns that are in 1st level menu.
<pre>
Atoms
  - Buttons
     - Primary
     - Disabled
  - Icons
     - Action Close
Molecules
  - Cards
     - Card Group Header
     - Card Summary
  - Filters
     - Off Positive
Templates
  - Default
  - Nav Active
CSS Utilities
  - Layout Depth
     - Depth
  - Layout Flex
     - Flexbox
</pre>
If I will try to remove *Templates* the `View All` link in `CSS Utilities`, or if I will have `Templates` pattern subtypes/ 2nd level menu it will work just fine.

**Comment by eliland** [comment]
I had a very similar problem on `Gulp` edition 1.3.2 and 1.3.3. Seems to have resolved itself with 1.3.4, so you might want to give that a go.

**Comment by bmuenzenmeyer** [comment]
I have found and fixed this issue. I want to cover it with unit tests and then push out a release.
