### ISSUE TITLE
listItems keys (`one` through `twelve`) can only be used once per pattern

### ISSUE THREAD

**Issue by dennisfrank** [pattern-lab/patternlab-node#553]
I am using Pattern Lab Node `v2.6.1` on `Mac`, with Node `v5.3.0`, using a custom edition as well as `Gulp` and `Grunt ` Editions. 

I have some problems with Pattern Lab’s [listItems Variable](http://patternlab.io/docs/data-listitems.html):

```
{{# listItems.three }}A{{/ listItems.three }}
{{# listItems.three }}B{{/ listItems.three }}
```

##### Expected Behavior

> AAABBB

##### Actual Behavior

> AAAAAA

##### This works

```
{{# listItems.three }}A{{/ listItems.three }}
{{# listItems.two }}B{{/ listItems.two }}
```

Result:

>AAABB

##### Issue

It seems that every key (`one` through `twelve`) can only be used once per pattern.

**Comment by dennisfrank** [comment]
Hi. This seems to be still in an issue with the current Pattern Lab Node version 2.12.0. Any chance for a fix? (@raphaelokon maybe? :wink:)

**Comment by bmuenzenmeyer** [comment]
PRs welcome! It's Hacktoberfest, after all.
https://hacktoberfest.digitalocean.com

**Comment by raphaelokon** [comment]
@bmuenzenmeyer I had a branch open for this … and got it working but then other tests were failing and I honestly struggled to debug it.

**Comment by bmuenzenmeyer** [comment]
@raphaelokon have you spent any more time understanding what's going on with your fix and how it relates to the failing tests? do you need help?

**Comment by raphaelokon** [comment]
I understand why it is fixing it, but it seems some odd side-effect trips on my fix. Any help would be aces.

**Comment by bmuenzenmeyer** [comment]
@raphaelokon which branch?

**Comment by raphaelokon** [comment]
https://github.com/pattern-lab/patternlab-node/tree/issue/457-nested-items
