### ISSUE TITLE
Add benchmarks to cope with regressions

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node#561]
This is a dev feature request to handle regressions when developing the PaternLab core.

In my opinion we should have at least micro benchmarks to have a confidence layer before pushing new stuff. Something like https://benchmarkjs.com would be a good start.

**Comment by bmuenzenmeyer** [comment]
Would this be incorporated into Travis?

Catching performance regressions is important to me, but is always a bit of a challenge because we don't ship with large pattern trees.

**Comment by raphaelokon** [comment]
Neither does v8 … but they have micro benchmarks and some static `projects` they run through their perf pipeline. And yes: This includes work :D

**Comment by bmuenzenmeyer** [comment]
It'd be neat if, via webhook, additional checks could occur in a Travis-like fashion that pull down everything, install a large starterkit, and run perf metrics against a baseline. Am I aligned with your thinking?

**Comment by raphaelokon** [comment]
> Am I aligned with your thinking?

To be fair: It is just something some folks I know are concerned about … and we could make sure that we do not slow down the core.

**Comment by raphaelokon** [comment]
And yes … we are aligned :)

**Comment by bmuenzenmeyer** [comment]
Agreed - performance has become more and more important!

:+1: x :100:

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Cheers – we are on the same side! Let's make `patternlab-node` 🚀

**Comment by geoffp** [comment]
@raphaelokon and @bmuenzenmeyer -- I think this has now become important as we pursue async building. My own super informal performance tests run against the demo set of mustache patterns seems inadequate now.

We may not have a huge patten tree to test with yet, but it's something. It would be nice to have a more detailed set of performance counters than just the overall build time.

**Comment by raphaelokon** [comment]
Nice one @geoffp 
I think both, micro benchmarks and static tests with a big pattern tree, are important. Additionally we could even fork *popular* open source patterns and test against those. This is how V8 team does some of its testings: micro bench - static tests - real world pages

**Comment by tburny** [comment]
Please bear in mind that the benchmarks are partly engine-specific. We should compare a few engines altogether, so we don't miss something.
For my company's patternlab, the previous release spent < 1 second on `processPatternsIterative`, ~6-10 seconds on `processPatternsRecursive` and 83 seconds on building the patterns.
For the latter I found that especially larger pages which transiently include lots of partial patterns take a lot of time.

I'd like to suggest to add a performance log for some core operations which users could attach to their tickets so we can see what is taking so long.

**Comment by geoffp** [comment]
@tburny this is super true.

Handlebars, for example, has a much higher template compile cost than mustache, but may have much longer `processPatternsRecursive()` time due to the syntax extensions. I'd love to know how how this all stacks up.

Any volunteers to build tooling? :smile:

**Comment by raphaelokon** [comment]
Good catch @tburny I couldn't agree more.
I think identifying the perf bottlenecks is really an iterative process as well … kind of hunting down mea leaks.

> I'd like to suggest to add a performance log for some core operations which users could attach to their tickets so we can see what is taking so long.

This is a good call as well.
