### ISSUE TITLE
Refactor all logs

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#566]
**prework**
- [x] Finish https://github.com/pattern-lab/patternlab-node/pull/565 by replacing our lo-tech solution found within https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/utilities.js

**remaining**
- [x] Replace all console.logs per https://github.com/pattern-lab/patternlab-node/pull/565#issuecomment-262827227
- [x] use string templates instead of concatenation
- [x] pass verbose flag or log levels from CLI into `patternlab.js` - successor to #254 (patternlab-config.json)

**Comment by bmuenzenmeyer** [comment]
these aren't working yet...

**Comment by bmuenzenmeyer** [comment]
I think the bulk of remaining work on this should wait until we have the CLI pass in the verbose flag, so we can finally take out `patternlab.config.debug`

**Comment by geoffp** [comment]
I agree. We've wanted that forever.
