### ISSUE TITLE
Gulp support

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#57]
Remaining todo to ship this:

- [x] Update gulpfile to omit scss where possible as a default
- [x] Revert project back to grunt-first
- [x] Update readme with browsersync
- [x] Update readme installation instructions to help users wanting to init with gulp. Mention Windows caveat
- [x] Update readme to help users switch to gulp
- [x] Create upgrade instructions
- [x] Create known issue section in readme for the other device page follow problems using the menu.
- [x] Changelog
- [x] Make sure gulp files are properly cited as deriving form  oscar-g's work
- [x] Create ticket for small optimization to better target grunt watches more efficiently
- [x] Remove sass from package jsons, instead include directions to include and turn on

**Comment by bmuenzenmeyer** [comment]
Remaining todo to ship this:

- [ ] Update gulpfile to omit scss where possible as a default
- [ ] Revert project back to grunt-first
- [ ] Update readme with browsersync
- [ ] Update readme installation instructions to help users wanting to init with gulp. Mention Windows caveat
- [ ] Update readme to help users switch to gulp
- [ ] Create upgrade instructions
- [ ] Create known issue section in readme for the other device page follow problems using the menu.
- [ ] Changelog
- [ ] Make sure gulp files are properly cited as deriving form  oscar-g's work
- [ ] Create ticket for small optimization to better target grunt watches more efficiently

**Comment by oscar-g** [comment]
@bmuenzenmeyer, sorry for the lack of communication...I've been terribly busy on my end.

I'm willing to put some more work into the gulpfile and the docs.

Are we still thinking about supporting all grunt, gulp, and vanilla versions?

Also, what is the reasoning behind the first point in your list, above ("Update gulpfile to omit scss where possible as a default")?

Thanks

**Comment by bmuenzenmeyer** [comment]
I should have been more clear- this list is for me. The work is done but I
need to document it. I am not a Gulp expert, if I pushed it to a branch
would you please review it?

**Comment by bmuenzenmeyer** [comment]
At a computer, so I can answer more fully.

> Are we still thinking about supporting all grunt, gulp, and vanilla versions?

Yes. My current plan is to keep this all in the same repository, and just document the (in my eyes) simple means to switch out the node_modules and package.json file.  

> Also, what is the reasoning behind the first point in your list, above ("Update gulpfile to omit scss where possible as a default")?

The reasoning here is that scss or any css preprocessor was never a project dependency in pattern lab. This is almost a trivial point in a node environment as its so simple to integrate whichever you like, but what matters is that the core files still ship with scss. I think this might change in a post v1.0.0 world, but for now it's going to be this way. Therefore, the files are there if you want them but I don't want to assume someone starts with scss. I need to determine which configuration causes less confusion in the long run and is most approachable to newbies.

**Comment by bmuenzenmeyer** [comment]
@oscar-g @yuvilio @ivanmayes can anyone take a gander at the `dev` branch and attempt to upgrade / install the gulp version? I am pretty confident I've got everything but want some other eyes on it first!

cheers

**Comment by oscar-g** [comment]
I'll take a look at this today.

**Comment by oscar-g** [comment]
@bmuenzenmeyer, this looks good so far. It builds, serves, and the tests pass.  I haven't tested editing patterns and live reload, yet.

One thing: I would add `gulp-sass` to the package.json...the other option would be to remove `sass = require('gulp-sass')` from the gulpfile, but then the user would have to add that in, if they want to use scss.  On that note, we could add a section in the readme on exactly what comments to remove, in order to use scss (in gulpfile.js, for example, it would be lines 89-90, 109-126, and 135).

**Comment by bmuenzenmeyer** [comment]
@oscar-g ah, I missed the require statement - great catch. The readme does ake some mention of CSS Preprocessor support - please check that out and let me know if it makes sense - it's a bit blunt. I like the idea of either just commenting it out or providing further instruction.

I did test the pattern editing and live reload, but yes hammer away a bit more.

Thanks for your help testing!
