### ISSUE TITLE
Incremental Builds: Updating an individual pattern breaks viewall page rendering

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#586]
I am using Pattern Lab Node `v2.7.1-alpha` on `Windows`, with Node `v5.5.0`, using the `Gulp` Edition.

##### Expected Behavior

_With `cleanPublic` set to false, incremental build functionality should be enabled._

Altering one file, `pattern1.mustache` within `_patterns/test/group1` should cause it to incrementall rebuild.
However, this update should be visible on any viewall page alongside its sibling patterns. (All other patterns should remain untouched, effectively)

##### Actual Behavior

Only the changed pattern is displayed on the view all page

##### Steps to Reproduce

1. Download zip and place as only thing under `source/_patterns/`

[test.zip](https://github.com/pattern-lab/patternlab-node/files/687663/test.zip)

![image](https://cloud.githubusercontent.com/assets/298435/21687059/61036ef8-d32d-11e6-9bbe-ce1596b646ed.png)

2. `gulp patternlab:serve`

3 Witness `all` output or `viewall-test-all` output

![image](https://cloud.githubusercontent.com/assets/298435/21687115/a205b406-d32d-11e6-82cd-8ca50b098f0d.png)

4. Change `pattern2.mustache`

5. Witness bug

![image](https://cloud.githubusercontent.com/assets/298435/21687153/c7b8e39e-d32d-11e6-95e8-2c1b62f33daa.png)

##### Workaround

When you want to view viewall pages again, delete the `dependenyGraph.json` file and `public/patterns`

**Comment by georgiee** [comment]
Just to raise awareness:
I am using Pattern Lab `Node v2.7.1-alpha` on `OSX 10.12.2` with Node v7.0.0, using the Gulp Edition, `cleanPublic = true` and I get the very same error. 

Reproducible by running `patternlab:patternsonly` which excludes any other source of error.
Unpredictable output. Sometimes compiles latest changed mustache file sometimes nothing.

Mentioned workaround works for me too.

**Comment by bmuenzenmeyer** [comment]
@georgiee thanks for the report - a set of changes on the `dev` branch should have fixed the `cleanPublic` = `true` side of things, if you are clamoring for that fix

**Comment by georgiee** [comment]
Thanks for that quick response. I'm fine with the stable 2.6.2 for now. But I gave the dev branch a quick test anyway and it worked like promised. I love to see incremental builds finally coming to pattern lab. Thanks all your efforts.

**Comment by tburny** [comment]
@georgiee `patternlab:patternsonly` should not rebuild the `View all` pages, but the patterns only. That said, you probably won't see any effect unless you view a single pattern in the browser only.

**Comment by tburny** [comment]
The UI uses a plain mustache template (i.e. not a Pattern) via `buildViewAllHtml() -> `pattern_assembler.renderPattern()`. In the `else` branch there it creates a new empty pattern with all patterns in a group (i.e. `atoms`) as partials. However `patternPartialCode` is undefined for each pattern in `data.partials`, thus there is no output.

**Comment by bmuenzenmeyer** [comment]
Confirmed this is working now. 

Will be doing one final run of some of this functionality and then releasing!
