### ISSUE TITLE
Pattern Lab Reports Missing Patterns in Console

### ISSUE THREAD

**Issue by NickToye** [pattern-lab/patternlab-node#587]
I am using Pattern Lab Node `v2.6.2` on `Windows | Mac | Linux`, with Node `v7.4.0`, using the `Gulp ` Edition.

##### Expected Behavior

Although on the frontend there is no issues, I am getting this message in my gulp output:

> Could not find pattern referenced with partial syntax molecules-cta. This can occur when a pattern was renamed, moved, or no longer exists but it still called within a different template somewhere.

Now I call molecules-cta in this file **source/_patterns/molecules/00-banners/banner.mustache**

   <div class="c-banner">

    <div class="c-banner__wrapper">

      {{# text }}

        <div class="c-banner__text">

          <div class="c-banner__text--inner">

            // content

            <div class="o-actions">
            
              <div class="o-actions__inner">
                {{# cta }}
                  {{> molecules-cta }}
                {{/ cta }}
              </div>

            </div>

          </div>

        </div>

      {{/ text }}

    </div>

  </div>
    
    
I have a similar call in another file **source/_patterns/molecules/00-banners/banner-image.mustache**

When I remove this from the 1st file:

`{{# cta }}
                  {{> molecules-cta }}
                {{/ cta }}`

I no longer see an error looking for that file, so I copied the code exactly from the banner-image.mustache file into the banner.mustache file, but it made no difference, I got the error again.

This has stumped me.  Let me know if anymore information is required.

**Comment by bmuenzenmeyer** [comment]
Thanks for the report @NickToye 

Can you also please provide the code for molecules-cta and banner.json, if it exists.

**Comment by NickToye** [comment]
molecules-cta

`{{> atoms-button:c-btn--ghost(button: "Call to action") }}`

banner.json

`
    {
    "cta": true
  }
`

**Comment by bmuenzenmeyer** [comment]
and for completion's sake, atoms-button

helps complete the complete render tree.

I take it `text` is then defined globally?

**Comment by NickToye** [comment]
`<button class="c-btn {{ styleModifier }}">{{# transactional }}<i class="fa fa-fw fa-payment-basket"></i>{{/ transactional }}{{ button }}</button>
`

I did have text as an option in the banner.json, thought that may have been the issue, but it wasn;t as I took it out.

**Comment by tburny** [comment]
I can confirm the problem of "there is a warning although the pattern exists"

**Comment by tburny** [comment]
@NickToye I took the time to do some research on the topic. The warning is emitted whenever there is a `data link` to a pattern that does not exist anymore. Such links can be defined in either the pattern JSON or globally in the `_data` folder (`_data/data.json`).

**Comment by bmuenzenmeyer** [comment]
@tburny thanks for the attempt at issue reproduction - I have no doubt that pointing people in the direction of their data is helpful, and the warning should probably say as such.

To fill you in, I've been chatting with @NickToye on gitter and he asserted that no such data links exist - therefore I asked him to create this issue.

That you cannot recreate the problem with the sample patterns supplied means something else is going on.

**Comment by NickToye** [comment]
I don't know what else to do here.  I'd be happy to privately share my repo so can verify I've not missed anything.

**Comment by bmuenzenmeyer** [comment]
@NickToye that'd be helpful at this point, if you are comfortable

**Comment by NickToye** [comment]
https://github.com/NickToye/pl-private

**Comment by NickToye** [comment]
I\ve added you Brian and tburny too.

**Comment by tburny** [comment]
Thanks

**Comment by jabas** [comment]
Working on upgrading up from 2.6.0-alpha now, and I'm finding that the error is triggered if the partial file is in a position _after_ the file asking it to be included when going through your patterns in order.

In my case, I have a **02-patterns/00-header/00-header.mustache** file that includes a **02-patterns/00-header/01-location-overlay.mustache** within it. That triggers the "Could not find pattern..." warning, though the templates compile and display fine.

Switch the **00** and **01** between the two mustache files, and the warning no longer displays.

**Comment by bmuenzenmeyer** [comment]
Interesting analysis - one that I would not have guessed. IIRC, we walk all patterns before attempting to evaluate them, but something is amiss if what you say is true.

**Comment by bmuenzenmeyer** [comment]
@NickToye that repo no longer works for me

**Comment by simonknittel** [comment]
Can confirm that @jabas analysis seems to be correct. We have the same issue with our PatternLab and resorting the patterns fixes the warnings.

**Comment by acarnwath** [comment]
I also had this issue, and resorting helped, however, my goal was for the included file to be a hidden one (starting with `_` per http://patternlab.io/docs/pattern-hiding.html), which always sorts it after any numbered patterns (i.e. *00-header.mustache* comes before *_00-hidden-thing.mustache*).  So unless I either make everything dependent on the hidden pattern also hidden, or un-hide that pattern, I'm not sure how to get rid of this warning.

**Comment by bmuenzenmeyer** [comment]
duplicate of #687

**Comment by absolutholz** [comment]
I have this problem and ignored it for a long time because everything was generated correctly in spite of the errors and warnings (). I upgraded to patternlab-node v2.10.0 (after taking the advice from #687) today and still had the same problem but noticed then when I remove the whitespace between the pattern name and the parameters, the errors and warnings disappear.

My structure is as follows:

- _patterns/
    - 00-atoms/
        - button.mustache
    - 01-molecules/
        - button-list.mustache

With the files as follows:

button.mustache
`<button>{{ buttonContent }}{{^ buttonContent }}button{{/ buttonContent }}</button>`

button-list.mustache
`<ul><li>{{> atoms-button ("buttonContent": "foo") }}</li></ul>`

This code generates the following errors:

> Could not find pattern referenced with partial syntax atoms-button . This can occur when a pattern was renamed, moved, or no longer exists but it still called within a different template somewhere.
> 
> JSON provided by partial pattern atoms-button  is invalid and cannot be copied
> 
> Could not find pattern referenced with partial syntax atoms-button . This can occur when a pattern was renamed, moved, or no longer exists but it still called within a different template somewhere.

When I change `button-list.mustache` by eliminating the whitespace between `atoms-button` and `("buttonContent"` the errors and warnings disappear.

Errorless button-list.mustache
`<ul><li>{{> atoms-button("buttonContent": "foo") }}</li></ul>`

These two files are the only changes I made to a fresh clone of [Pattern Lab Node - Gulp Edition (Tag: 1.4.0)](https://github.com/pattern-lab/edition-node-gulp/tree/v1.4.0), besides the fact that I am running it in a debian virtual box with node v8.6.0 installed.

**Comment by bmuenzenmeyer** [comment]
@absolutholz that's an interesting find

the space before the pattern parameter is not "correct syntax," as far as unofficial extensions to mustache go. I suppose we could be more lenient about spaces, but either way, you analysis may help others.

**Comment by absolutholz** [comment]
@bmuenzenmeyer Good to know. Sadly it never occurred to me that the space would be invalid, but it makes sense. I thought the paramaters themselves may have been the issue because I initially wrote the property names without quotations. I thought this may be registering as invalid JSON, but I have now tested with quotations, with simple apostrophes and without either and they have no effect on the rendering output.

Also, I am really happy with Pattern Lab and you're fast response about the correct syntax just adds to that feeling. Thanks!

**Comment by Josh68** [comment]
FWIW, I am seeing this in a test environment using v3 alpha 8 with the webpack edition and using handlebars includes. It does look like the issue crops up in reference to all asset files (md, js, scss) related to a pattern (hbs) that pulls in an include of any kind. This includes a few files that pass params to the include, but many that don't, and handlebars provides a native way to do that, so am not using the special pattern-lab syntax provided for mustache includes. Also, in my case, as with others, everything actually does compile, even with the many warnings.

**Comment by bmuenzenmeyer** [comment]
This is fixed via https://github.com/pattern-lab/patternlab-node/issues/786
