### ISSUE TITLE
Add tests/ to npmignore file

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#588]
Raphael clued me in on https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package which we should most definintely be doing for `tests/` as normal consumers have no reason to get these files during distribution.

**Comment by raphaelokon** [comment]
Or use `files: ['core/']` to package.json to exclude all explicitly and only include `/core` into the package :)

**Comment by raphaelokon** [comment]
Reference here: https://docs.npmjs.com/files/package.json#files
