### ISSUE TITLE
How to use with angular2.0

### ISSUE THREAD

**Issue by Anshdesire** [pattern-lab/patternlab-node#589]
How to use with angular2.0

**Comment by tburny** [comment]
Can you clarify your problem a bit?

**Comment by bmuenzenmeyer** [comment]
As someone asked on stackoverflow, [Does Pattern Lab “not mix well” with Angular?](http://stackoverflow.com/questions/39515130/does-pattern-lab-not-mix-well-with-angular/39543032#39543032), Angular and Pattern Lab are compitable in that they don't have much to do with another.

PL can run arbitrary javascript within the confines of a pattern.

![](https://github.com/bmuenzenmeyer/patternlab-node-angular-example/raw/master/patternlab-angular.gif)

I created this reductive sample repository illustrating Angular within Pattern Lab.

* Repository https://github.com/bmuenzenmeyer/patternlab-node-angular-example
* Live Demo http://www.brianmuenzenmeyer.com/patternlab-node-angular-example/public/index.html

**Comment by Anshdesire** [comment]
@tburny - Tried to add my files in patternlab-config but failed to do so. I think there should be better explanation of patternlab-config file.

**Comment by bmuenzenmeyer** [comment]
@Anshdesire 
I suggest you acquaint yourself with how [editions lilke edition-node-gulp](https://github.com/pattern-lab/edition-node-gulp) work with this core repository. After that, you could use  the examples I provided above to see how Angular works with Pattern Lab. The above is a complete, although simple, example.

* Configuration is documented here: https://github.com/pattern-lab/patternlab-node/wiki/Configuration
* General Pattern Lab documentation is here: http://patternlab.io/docs/ 

If you are still stuck, please provide more detail as to what you are doing within the `patternlab-config.json` file.

**Comment by bmuenzenmeyer** [comment]
Closing this
