### ISSUE TITLE
Implement dynamic listItems.Number

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#595]
crosspost from https://github.com/pattern-lab/patternlab-php/issues/167

thanks to @emilz0r for finding and bringing this to my attention

**Comment by machal** [comment]
I really would like to see this in the Node edition. Any chance in the near future?

**Comment by karelknop** [comment]
+1

**Comment by simonerlandsen** [comment]
+1

**Comment by engelfrost** [comment]
Cool feature, but this is something every pattern engine will have to support.

Should all official engines be required to support this, or should this be moved out of PL domain?

**Comment by JosefBredereck** [comment]
Closing in favor of  #1178 and #1179
