### ISSUE TITLE
Using underscore to hide pattern folder cause critical error in Windows environment

### ISSUE THREAD

**Issue by carlosliu** [pattern-lab/patternlab-node#596]
I am using Pattern Lab Node `v2.7.2` on `Windows | Mac | Linux`, with Node `v4.7.2`, using the `Gulp` Edition.

##### Expected Behavior
Putting underscore as the first character of a pattern directory name, such as `00-atoms\_00-blah`, should exclude `_00-blah` from the library.

##### Actual Behavior
It throw following critical error
` Could not find patternType 00-atoms-00-atoms. This is a critical error.`

**Comment by bmuenzenmeyer** [comment]
this is released with 2.8.0
