### ISSUE TITLE
Replace all var with let/const

### ISSUE THREAD

**Issue by tburny** [pattern-lab/patternlab-node#598]
I am using Pattern Lab Node `v2.7.2` on `Linux`, with Node `v4.6.2`.

For consistency and code quality we should replace all existing `var` keywords with `let` or `const` for safer variable scoping.

**Comment by tburny** [comment]
Great :)

**Comment by bmuenzenmeyer** [comment]
Thanks for offering your help @benhalverson.

I am a bit worried that submitting this PR against `dev` would lead to many conflicts with the async work going on. I suggest working against a version of that. 

@geoffp to reduce all of this confusion, but leave `dev` open for 2.X work, are you alright with moving your async work into a `dev3.0` branch?

**Comment by bmuenzenmeyer** [comment]
@benhalverson @tburny @geoffp @raphaelokon I have branched the latest async stuff I could was reported stable to `dev-3.0`

**Comment by benhalverson** [comment]
🙄

**Comment by bmuenzenmeyer** [comment]
@benhalverson stalebot tries so hard - it was supposed to ignore "staged for next release issues"

**Comment by benhalverson** [comment]
@bmuenzenmeyer I think it needs to go back to parsing hot dog or not hot dog images 🤣
