### ISSUE TITLE
Faster pattern preprocessing

### ISSUE THREAD

**Issue by tburny** [pattern-lab/patternlab-node#604]
I am using Pattern Lab Node `v4.7.2` on `Linux`, with Node `v4.7.0`, using the `Grunt` Edition.
In Spirit of #316 

Currently the `processPatternsIterative` and `processPatternsRecursive` methods in `patternlab.js` take a long time (in terms of magnitudes 10 seconds), especially for large pattern trees with lots of data.

We should therefor collect ideas how to improve this step.

- Extend incremental builds to skip processing unchanged patterns?
- Cache pattern lookups and use ES6 `Map` for this. This potentially prevents falling back to the file system every time a pattern is looked up. 
- your suggestion here

**Comment by bmuenzenmeyer** [comment]
Anything we do needs to incorporate all of the async work @geoffp is doing. I suggest we merge `dev` into his branches asap. This will be a priority of mine. I know there are some PRs out there to this effect.

**Comment by geoffp** [comment]
@bmuenzenmeyer, @tburny, see https://github.com/pattern-lab/patternlab-node/pull/562#issuecomment-276290055

**Comment by bmuenzenmeyer** [comment]
unassigning myself - i only like to assign issues to things i plan to work on imminently

**Comment by bmuenzenmeyer** [comment]
Curious if https://github.com/pattern-lab/patternlab-node/releases/tag/v2.9.0 handled the majority of concerns. this issue is a bit to vague right now, but is good in an aspirational sense. 

for clarity's sake, i am removing from the 3.0 milestone
