### ISSUE TITLE
Alter each engine to spawn its head and foot pattern into _meta/ if not found

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#611]
part of https://github.com/pattern-lab/patternlab-node/issues/603

- [x] mustache
- [x] handlebars
- [x] twig
- [x] underscore
- [ ] ~react~ https://github.com/pattern-lab/patternengine-node-react/issues

**Comment by bmuenzenmeyer** [comment]
would be great if anyone else could help me understand what Underscore or React expect for these patterns

**Comment by bmuenzenmeyer** [comment]
paging @geoffp - we discussed this what feels like ages ago, but can you ping me where I can find the underscore meta patterns?

**Comment by geoffp** [comment]
@bmuenzenmeyer actually, I don't think we ever made any. It looks like in our underscore project, we're still using the default-ish mustache meta patterns, even though underscore is the main engine in use.

**Comment by bmuenzenmeyer** [comment]
Calling this done. future react work will need to account for this.
