### ISSUE TITLE
Remove the deprecated patternStates object on patternlab-config.json

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#619]
The [frontmatter/markdown state solution](http://patternlab.io/docs/pattern-states.html#node ) has been in place for a while now, with deprecation warnings emitted by the library.

It's time to remove the old functionality.

- [ ] Remove `patternStates` from all `patternlab-config.json` files across repos
- [ ] Remove all signs of `setState()` within `pattern_assembler.js` as `parsePatternMarkdown()` does all the work now.
- [ ] Resolve any unit tests

**Comment by benhalverson** [comment]
I can give this a shot tonight

**Comment by benhalverson** [comment]
@bmuenzenmeyer Does patternStateCascade also need to be removed from patternlab-config.json

**Comment by bmuenzenmeyer** [comment]
the cascade is still used.
relevant code: https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/lineage_hunter.js#L117

**Comment by benhalverson** [comment]
@bmuenzenmeyer Are there any other projects I need to update?
I've made pull requests to the below projects
- patternlab-node
- patternlab-node-cli
- edition-node-grunt
- edition-node-gulp

**Comment by raphaelokon** [comment]
@benhalverson I have a couple of stuff in limbo before I merge the PR into cli but it lgtm. Thanks.

**Comment by bmuenzenmeyer** [comment]
to my knowledge, all PRs are addressed.
