### ISSUE TITLE
Allow engines to support multple extensions

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#623]
I am using Pattern Lab Node `v2` and `v3` on `Windows`, with Node `v6.9.5`, using the `Gulp` Edition.

##### Expected Behavior

PatternEngines that support more than one common file extension for their template type should be forgiving and accomodate user preference. Examples

- [x] Handlebars: `.handlebars` vs `.hbs` - https://github.com/pattern-lab/patternengine-node-handlebars/commit/8c48eb453f3836ea64c641f26527250bf3cab911
- [X] React: `.jsx` vs `.js` - https://github.com/pattern-lab/patternengine-node-react/commit/d945e2b45a5ae5512247c7000eb77e722300aa9e
- [X] Underscore: `.html` vs `.underscore` - https://github.com/pattern-lab/patternengine-node-underscore/commit/de327f95ea9e7f0ab70137a6b0d24e6b2f279964

##### Actual Behavior

- Only one type is hard-coded into the engine. This causes problems with watches and the pattern code viewer and is detrimental to user adoption.

**Comment by raphaelokon** [comment]
Modules and scripts in JS
- `.mjs` and `.js`

**Comment by bmuenzenmeyer** [comment]
For which engine would that be?

**Comment by raphaelokon** [comment]
Each engine that is using a Javascript module (ES6 module syntax) in Node ecosystem?

**Comment by geoffp** [comment]
With the engines that we currently have, .js would be reserved for React, but we should also think of what kinds of files an Ember or Polymer / Web Components component engine might look for. I don't know those well enough to be able to say. I think Ember does Handlebars, or at least it used to.

**Comment by bmuenzenmeyer** [comment]
Maybe I am missing something, but my intent for this issue was to alter https://github.com/pattern-lab/patternengine-node-handlebars/blob/master/lib/engine_handlebars.js#L40 to be an array of exentions that make sense for the engine.  Not sure how we would handle mixed trees with overlapping capabilities, however.

**Comment by geoffp** [comment]
I agree, that's what we're doing. It would get pretty complicated to have a file extension claimed by more than one engine; I don't want to do that unless we really have to.

**Comment by geoffp** [comment]
Well, maybe not if mixed trees really are rare. Sorry, I think I'm too much in that mentality. We don't even have a mixed tree anymore.

**Comment by raphaelokon** [comment]
@bmuenzenmeyer I think I got it wrong. 
From a user perspective: Would it be possible to use an engine (I am actually working on something) that uses plain ES6 template literals and is essentially pure JS?

**Comment by geoffp** [comment]
I think it would, so long as you don't also have the React engine installed, which would introduce that conflict for `.js` files.

**Comment by raphaelokon** [comment]
@geoffp Cheers. Makes sense.

**Comment by bmuenzenmeyer** [comment]
Okay.  Perhaps we officially de-scope support mixed trees.

@raphaelokon that sounds killer

**Comment by geoffp** [comment]
@bmuenzenmeyer mixed trees were a useful way for us to incrementally migrate our technology stack. I'd hate to see us prohibit it, but it does seem very reasonable for us not to go way out our way to support it.

@raphaelokon are you doing some pure-functional JS templates or something? Tell us more! Is there editor support for markup in ES6 template literals?

**Comment by bmuenzenmeyer** [comment]
@geoffp agreed.  Or tree is a mix right now, but transitionary...  more and
more moving to handlebars every day

**Comment by geoffp** [comment]
@bmuenzenmeyer I've got serious love for Handlebars. Such a great authoring experience.

**Comment by raphaelokon** [comment]
@geoffp Yes. Basically it is a super simple template engine. PHPStorm highlights the html inside template literals and tagged literals. Also agree on handlebars.

**Comment by bmuenzenmeyer** [comment]
@geoffp @raphaelokon  🔥 🔥 🔥 

![image](https://user-images.githubusercontent.com/298435/31001923-dfecbfde-a4ac-11e7-94d7-e494eb794048.png)
