### ISSUE TITLE
Expose getSupportedTemplateExtensions

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#625]

**Comment by bmuenzenmeyer** [comment]
@raphaelokon did this work?
i think you may have said yes but a confirmation here would be great!

**Comment by raphaelokon** [comment]
It works. Cheers.

**Comment by raphaelokon** [comment]
Can this land in `2.8.0`? It breaks the current CLI :D

**Comment by bmuenzenmeyer** [comment]
check dev, I cherry-picked it

**Comment by raphaelokon** [comment]
Nice one @bmuenzenmeyer
