### ISSUE TITLE
Remove excessive logs when bootstrapping core

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node#636]
Can we please move the verbose logs under a flag in patternlab core or remove them completely? Everytime the cli inits the core it logs out the following.

```
Loading engines from the core...


Loading engines from the edition or test directory...

  mustache: good to go

Done loading engines.


====[ Pattern Lab / Node - v2.8.0 ]====
```

**Comment by tburny** [comment]
We should hide it under the debug flag and only report when engines really fail.
