### ISSUE TITLE
Incremental Builds: Updating global data.json does not appear to rebuild all patterns

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#638]
I am using Pattern Lab Node `v2.8.0` on `Windows`, with Node `v4.6.2`, using the `Gulp` Edition.

##### Expected Behavior

* Updating `_data/data.json` causes any patterns using data within to hae changes reflected

##### Actual Behavior

* No changes are observed when data changes, despite PL performing a build. It appears as if the dependencyGraph is still reporting patterns as clean under this scenario.

##### Steps to Reproduce

* Have a pattern that takes a basic piece of data from the global object defined in `_data/data.json`

```
<p>
  {{blurb}}
</p>

```

* Build with following data in `_data/data.json`:

```
{
  "blurb": "Foobar"
}
```

See `Foobar` added within paragraph.

* Trigger another build.

```
{
  "blurb": "Foobarbaz"
}
```

##### Workaround

Save the file with an arbitrary change, causing it to be dirty and pick up the new data.

**Comment by tburny** [comment]
> Changing a data.json file does not rebuild the whole patternlab. Temporarily use cleanPublic=true as a workaround.
https://github.com/pattern-lab/patternlab-node/wiki/Incremental-Builds

**Comment by bmuenzenmeyer** [comment]
Oh, I missed that point - thanks for clarifying. For my purposes, saving the file arbitrarily works great too.

**Comment by bjornwang** [comment]
I have the same error for _meta/00-head.mustache. Changing that file does not rebuild patterns correctly. Actually, if I delete the whole public/ folder and rebuild it, it is still rendered with the old _meta/00-head.mustache file content, so that seems to be cached somewhere.

Developing on two laptops working on the same project repo, I can reproduce this on both Windows and Mac.

Only fix is setting cleanPublic=true.

**Comment by SteffiB** [comment]
Any update on this? We run in a similar issue. When changing somethings in a JSON file, the pattern will not be rebuild. But changing something in a JSON file of a variant (e.g. example~variant1.json) the pattern will be rebuild.

**Comment by bmuenzenmeyer** [comment]
@SteffiB this hasn't made it into my immediate roadmap, but I appreciate you letting me know it's a problem. I'll fit it into the priorities somewhere. PRs always welcome too!

**Comment by tburny** [comment]
Also linked to #695. The problem is the same: There is no pattern for these files, so their changes are not picked up.
When detecting a change in _meta or data.json, all patterns need to be rebuilt.

**Comment by bmuenzenmeyer** [comment]
The simplest thing would be to watch these files and have a mechanism to
rebuild all patterns on the public API we expose to gulp/grunt, etc.
