### ISSUE TITLE
pattern links resolve to absolute paths instead of relative paths

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#647]
I am using Pattern Lab Node `v2.9.1` on `Windows`, with Node `v6.9.5`, using the `Gulp` Edition.

##### Expected Behavior
pattern links `{{link.pages-foo}}` should resolve to a relative URL

**Example**: 
In PL PHP, for example: the [demo login](http://demo.patternlab.io/?p=pages-login) form action link [code found here](https://github.com/pattern-lab/starterkit-mustache-demo/blob/master/dist/_patterns/02-organisms/forms/stacked-form.mustache) should resolve 

```
<form class="c-form c-form--stacked" method="post" action="{{ link.pages-dashboard }}">
```

to 

```
<form class="c-form c-form--stacked" method="post" action="../../patterns/04-pages-02-dashboard/04-pages-02-dashboard.html">
```

##### Actual Behavior

In PL Node, however, this resolves to

```
<form class="c-form c-form--stacked" method="post" action="/patterns/04-pages-02-dashboard\04-pages-02-dashboard.rendered.html">
```

Leads to a broken page.

##### Steps to Reproduce

1.  Download and use the https://github.com/pattern-lab/starterkit-mustache-demo starterkit 
2. Inspect/test the login form

**Comment by bradfrost** [comment]
Thanks @bmuenzenmeyer. This would be a super great thing to resolve as it provides a lot of value to teams doing a lot of user testing and prototype work. We've done this kind of thing of several projects and it works quite well.

**Comment by bmuenzenmeyer** [comment]
I agree @bradfrost.  I need to dive into this closer. 

Would you agree that the demo login is the perfect test case? I will work from that if you think so. I did review @pcvonz's PR but something seemed amiss. 

I will prioritize this, thanks for your feedback!

**Comment by bradfrost** [comment]
Yeah I think that's right. Either that or a basic search form that clicks through to another page on submit. They're more or less the same!

**Comment by bmuenzenmeyer** [comment]
@bradfrost is this an acceptable workaround for you?

inside https://github.com/pattern-lab/starterkit-mustache-demo/blob/master/dist/_patterns/02-organisms/forms/stacked-form.mustache

```diff
- <form class="c-form c-form--stacked" method="post" action="{{ link.pages-dashboard }}">
+ <form class="c-form c-form--stacked" method="get" action="{{ link.pages-dashboard }}">
```


changing the `post` to a `get` allows the form to submit

**Comment by bradfrost** [comment]
@bmuenzenmeyer Yeah this is great! We'll likely want to document that somewhere, but so long as we're able to navigate around with form submission that should work. Thanks!

**Comment by bmuenzenmeyer** [comment]
Closing
