### ISSUE TITLE
listitems using patternengine-node-handlebars

### ISSUE THREAD

**Issue by gileses** [pattern-lab/patternlab-node#648]
I am using Pattern Lab Node `v2.9.1` on `Windows`, with Node `v7.2.0`, using the `Gulp` Edition and `patternengine-hode-handlebars`

[pattern].hbs contains:
+
`{{#listitems.three}}`
item
`{{/listitems.three}}`
+
##### Expected output
+itemitemitem+

##### Actual output
++

If I rename to [pattern].mustache then the code above works as expected.

**Comment by dennisfrank** [comment]
I have the same issue. Any idea if listItems will be added to Handlebars? ListItems are very useful to output _random_ data from `listItems.json`.

**Comment by engelfrost** [comment]
I did not know of this feature until now. Handlebars needs a Helper to achieve this. PR https://github.com/pattern-lab/patternlab-node/pull/959 (for PL 3) would allow you to add this yourself.

**Comment by SuneRadich** [comment]
Just curious, looking at the code for the handlebars engine:

https://github.com/pattern-lab/patternengine-node-handlebars/blob/0d96ce05f768202e3d1b7b576d17bf9d307d59e0/lib/engine_handlebars.js#L86

It seems like the engine does in fact have some notion of listitems - why would it need a custom helper for this?

**Comment by engelfrost** [comment]
Good question... I don't get the `findListItemsRE` though, it doesn't identify a closing handlebars tag, and I wonder why this isn't implemented as a Handlebars helper.

**Comment by JosefBredereck** [comment]
Closing in favor of #1178 and #1179
