### ISSUE TITLE
Add middleware/preprocessing hook for data.json files. (Faker request)

### ISSUE THREAD

**Issue by cloudsociety** [pattern-lab/patternlab-node#651]
Is there a hook or place where we can process data files before passing them on to the (moustache/twig/handlebars) renderer?

If not, is it tricky to add?

I think this would allow for the inclusion of things like Faker (and possibly, custom functions) in patternlab-node. I imagine it working similar to the php faker plugin, where you add your call to the data file and it gets processed at render time. (I might be wrong there. That's what it appears to do in my eyes.)

Mustache allows for "lambdas", but it seems like that would get verbose in a hurry.

I'd prefer a method that works across template engines, but if it needed to be in the engine itself, that would be a good start too.

Thoughts? Is anyone doing something similar or different already?

**Comment by bmuenzenmeyer** [comment]
hi @cloudsociety 

did you give plugins a shot? I tried to architect them in such a way that would allow for a hook at the proper place.

https://github.com/pattern-lab/patternlab-node/wiki/Creating-Plugins

**Comment by cloudsociety** [comment]
Doh! How did I miss the wiki? I'll take a look see what I can do.

Thanks, Brian!

-Dave

**Comment by cloudsociety** [comment]
Okay… Here's an early test that seems to work. Would really appreciate advice and feedback on how to improve it. I'm still learning, so I welcome any critique you have time for.

I haven't pushed to NPM yet. It works as a linked module, but I'd like to review (or get peer-reviewed) over the next couple days.

https://github.com/cloudsociety/plugin-node-faker

**Comment by bmuenzenmeyer** [comment]
Great! - I will check it out. A quick glance looks promising 💃

**Comment by cloudsociety** [comment]
Thanks, Brian.

I think this issue can be safely closed. I'll review my code a little more after a short break and then push it to NPM.
