### ISSUE TITLE
Question: How much task processing do you want to include?

### ISSUE THREAD

**Issue by ivanmayes** [pattern-lab/patternlab-node#66]
Hey Brian,  love that we are getting the grunt and gulp versions up and running!

Shoptology was previously running patternlab-php and we built out some great workflow items for building out the style guide as the "true source" of the design templates for an app.  We build out all our styles for components before exporting the finished css and image assets to our app for real world usage.

My question is to what degree would you like to include any of the following in the grunt or gulp projects?  Happy to pull request for any of these elements if you think they would be beneficial for the project.

https://github.com/shoptology/patternlab-php/blob/master/Gruntfile.js

We have BrowserSync, which lets you open the styleguide in unlimited number of devices and keeps them all in sync with navigation and source changes, great for building out responsive components in the style guide.
https://github.com/shakyShane/grunt-browser-sync

For testing the condition of your styles:
https://github.com/peterkeating/grunt-csscss
https://github.com/phamann/grunt-css-metrics

Visual regression tests (lets you visually test differences between versions of your style guide as your team makes changes)
https://github.com/BBC-News/wraith

UnCSS works perfectly with Patternlab, can scan all the pages and remove any css that wasn't used on the pages.  We've seen 30-40% file size savings on Bootstrap projects, as has Addy Osmani who started the grunt plugin.
https://github.com/addyosmani/grunt-uncss

We also have some scripts that help with optimizing images as they come in and building sprite sheets.

**Comment by bmuenzenmeyer** [comment]
@ivanmayes any update on this?

**Comment by bmuenzenmeyer** [comment]
Closing.

See: https://github.com/pattern-lab/patternlab-node/pull/86 for more info.

At some point this could be picked back up.
