### ISSUE TITLE
Unable to generate "View All" pages on flat patterns

### ISSUE THREAD

**Issue by ThePeach** [pattern-lab/patternlab-node#660]
I am using Pattern Lab Node `v2.9.2` on `Mac`, with Node `v7.9.0`, using the `Gulp` Edition.
I have a category directory with a flat list of mustache files in it, i.e. without sub-category folders.

##### Expected Behavior
I'm expecting the "View All" page to be generated for that directory

##### Actual Behavior
No "View All" page is being generated

##### Analysis
Apparently (after chatting with @bmuenzenmeyer) this is _by design_.

It would be indeed nice if it was possible to control the generation of "View All" pages programatically and granularly on a per-directory way, e.g. with something as simple as a dot-file in the directory to enable its generation, and/or with a global "default" option that won't break backward compatibility.

**Comment by JosefBredereck** [comment]
Fixed with #1143 in [V5.12.0](https://www.npmjs.com/package/@pattern-lab/core)
