### ISSUE TITLE
Update Known Issues Page

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#662]
https://github.com/pattern-lab/patternlab-node/wiki/Known-Issues-&-Deviations-from-Pattern-Lab-PHP

**Comment by bmuenzenmeyer** [comment]
I cannot recall if I created this for a specific reason.
Bucket issues like this are rarely useful, it turns out.

**Comment by bmuenzenmeyer** [comment]
I read the wiki - it is out of date.

This has been a github play in three acts

**Comment by tburny** [comment]
Can you tell what exactly needs to be changed?
