### ISSUE TITLE
Feature Request: Link Resolution in data.json

### ISSUE THREAD

**Issue by acarnwath** [pattern-lab/patternlab-node#667]
I am aware that you already have link resolution in the mustache files: http://patternlab.io/docs/data-link-variable.html

But almost invariably, I need my links to be populated via the data.json, which does not have the same link resolution ability, so I end up hardcoding the links, which becomes problematic when I rename the folder containing the pattern or reorder them.

**Comment by bmuenzenmeyer** [comment]
Hey @acarnwath - last I checked this was in fact working! Let me see what I can russle up.

**Comment by bmuenzenmeyer** [comment]
![link](https://user-images.githubusercontent.com/298435/27695457-89e00032-5cb4-11e7-903a-eeaac8be18c1.gif)


`data.json`
``` javascript
{
  "fromDataLink" : "link.main-parent"
}

```

contents of `_patterns` folder
[_patterns.zip](https://github.com/pattern-lab/patternlab-node/files/1112534/_patterns.zip)

**Comment by acarnwath** [comment]
You're totally right - I just assumed that since it wasn't in the documentation, it didn't exist.  Maybe consider adding it there :)
