### ISSUE TITLE
Parsing silently fails with errors in template parameters

### ISSUE THREAD

**Issue by DaSchTour** [pattern-lab/patternlab-node#671]
I am using Pattern Lab Node `v2.9.3` on `Mac`, with Node `v6.9.1`, using the `Grunt ` Edition.

##### Expected Behavior
This templates
```
<input type="{{ inputType }}" pattern="{{ validationPattern }}">
<label>{{ label }}</label>
```

Included this way
```
{{> atom-input(inputType: "text", label: "Name" , validationPattern="[a-zA-Z]+") }}
```

Should generate an error message because of wrong not working syntax

##### Actual Behavior

Is currently silently failing without any notice.

##### Steps to Reproduce

Add an atom called input with the template. Include the atom into another pattern.

**Comment by DaSchTour** [comment]
further activity

**Comment by JosefBredereck** [comment]
Closing in favor of  #1180, #1181 and #1177
