### ISSUE TITLE
Add an nvmrc file

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#682]
It'd be smart to tell users what Node version we officially support

**Comment by tburny** [comment]
I would suggest using the latest currently available LTS version here, _including the minor version_.

**Comment by bmuenzenmeyer** [comment]
What are you suggesting?

Current LTS is....

https://nodejs.org/download/release/latest-v6.x/
https://github.com/pattern-lab/patternlab-node/commit/ab99d50e0f5ffbc117f0a9b8cb5d602e7232dc49#diff-ae9eba3500703eaba1d5b8e13832d955

at least until https://github.com/nodejs/Release switches it to 8 sometime in October....
