### ISSUE TITLE
Pin our dependencies

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#684]
We should attempt to avoid problems like what happened at  js-beautify/issues/1247 in the future.

https://github.com/pattern-lab/patternlab-node/blob/master/package.json#L11

**Comment by ms10398** [comment]
I want to work on this can i know what I have to do in this

**Comment by bmuenzenmeyer** [comment]
@ms10398 basically we need to remove the carets "^" from our dependencies defined within `package.json` so that they don't update without our knowledge

**Comment by ms10398** [comment]
Okay I will make a relevant PR soon. 
Thanks @bmuenzenmeyer

**Comment by scarabcoder** [comment]
Is this still open?

**Comment by bmuenzenmeyer** [comment]
No but plenty other items to choose from.  I have plans to add more next
week too
☆☆☆☆
