### ISSUE TITLE
Data from listItems are not passed through in the loop 

### ISSUE THREAD

**Issue by bramsmulders** [pattern-lab/patternlab-node#685]
I am using Pattern Lab Node `v2.11.0` on `Mac`, with Node `v6.11.3`, using the `Gulp` Edition.

##### Expected Behavior
Should render three different `title`s harvested from `_data/listitems.json`.

##### Actual Behavior
Renders three times the same `title` attribute which is defined in `_data/data.json`

##### Steps to Reproduce

Consider this template code:
```
{{#listItems.three}}
{{title}}
{{/listItems.three}}
```

**Note:** it is working in PL-node v2.9.3 so it has to be a problem with the refactoring of data in the latest release.

**Comment by bmuenzenmeyer** [comment]
@bramsmulders I'll need to do some more testing, but my unit test coverage is passing for this so far....

**Comment by bmuenzenmeyer** [comment]
found it. fix incoming

**Comment by bramsmulders** [comment]
Whoop! thnx @bmuenzenmeyer!
