### ISSUE TITLE
Warning on build for patterns that occur after pattern

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/patternlab-node#687]
Using Pattern Lab Gulp Edition, I'm getting warnings when including files that are defined later in the tree structure. I'm assuming it's due to the way Pattern Lab crawls through the file structure and stitches things together.

I have a directory structure as follows:

```
- organisms
  - global
    -  00-header.mustache
    -  profile-block.mustache
```

I'm including `profile-block.mustache` inside of `00-header.mustache` like so:

```
{{> organisms-profile-block }}
```

##### Expected Behavior
This setup should build without any errors or warnings.

##### Actual Behavior

I get the following warming message on build: "Could not find pattern referenced with partial syntax organisms-profile-block. This can occur when a pattern was renamed, moved, or no longer exists but it still called within a different template somewhere." 

If I rename the files so that the `header` organism appears _after_ the `profile-block` pattern, everything builds without errors or warnings. So this structure works:

```
- organisms
  - global
    -  00-profile-block.mustache
    -  01-header.mustache
```

##### Steps to Reproduce
1. Add two component files, `component-1.mustache` and `component-2.mustache`. 
2. Include `component-2` inside of `component-1`. 
3. Build the project to see the warning.

**Comment by bmuenzenmeyer** [comment]
@bradfrost I cannot reproduce with the patterns you provided. I've zipped up the entire `source/` directory.

Can you try again?

Also, what version of Pattern Lab Node are you running? `gulp patternlab:version` can tell you.


[source.zip](https://github.com/pattern-lab/patternlab-node/files/1343111/source.zip)

**Comment by bmuenzenmeyer** [comment]
some additional context- this message seems to most often provide a false positive when you are defining pattern links inside JSON `link.pages-foo`.

Do you happen to also have those in your json somewhere? If so, that's the likely manifestation of the error.

**Comment by bradfrost** [comment]
I'm running version `v2.9.1`. I just copied my project and stripped out everything except the relevant patterns. And it all seems to render just fine, so it doesn't appear to be a pattern order thing. I'll do some testing on my end to see if it's the `link` stuff (there's plenty of that!) that could be causing issues. Thanks!

**Comment by bmuenzenmeyer** [comment]
> I'm running version v2.9.1

Ahh - can you try upgrading when you get a chance? [Version 2.9.2](https://github.com/pattern-lab/patternlab-node/wiki/ChangeLog#v292) fixed that if I recall.
