### ISSUE TITLE
Update contribution guidelines

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#689]
- [ ] current branching strategy
- [ ] commits should reference issues
- [ ] large enhancements should start with an issue, not a cold PR

**Comment by ms10398** [comment]
I claim this issue will make a relevant PR soon.

**Comment by ms10398** [comment]
I claim this issue I would love to contribute to the repository.

**Comment by ms10398** [comment]
Can you tell me more about the current branching strategy as I am new and I dont know about it

**Comment by prateekiiest** [comment]
Hey @bmuenzenmeyer ,
I would like to solve this issue.
I am sending a PR soon for this.

**Comment by prateekiiest** [comment]
Should I submit this on the dev branch or the master one?

**Comment by ms10398** [comment]
I was already working on it.
