### ISSUE TITLE
New `data_loader.js` module `loadFile` method loads the wrong file

### ISSUE THREAD

**Issue by phawxby** [pattern-lab/patternlab-node#692]
I am using Pattern Lab Node `v2.11.1` on `Windows`, with Node `v8.4.0`, using the `Gulp` Edition.

##### Steps to Reproduce

Given this file structure
* hero
  * hero-left-short.json
  * hero-left-short,mustache
  * hero-left.json
  * hero-left.mustache

##### Expected Behavior

`hero-left.mustache` should build using `hero-left.json`

##### Actual Behavior

`hero-left.mustache` builds using `hero-left-short.json`

##### Example

Adding the following lines to `loadFile`
```javascript
    if (dataFilesFullPath.indexOf("\\hero-left*.") > -1) {
      console.log(dataFilesFullPath);
      console.log(dataFiles);
      console.log(dataFile);
    }
```

Results in the following console output
```shell
hero/hero-left*.{json,yml,yaml}
[ 'hero/hero-left-short.json',
  'hero/hero-left.json' ]
hero/hero-left-short.json
```

**Comment by bmuenzenmeyer** [comment]
Nice catch! Sorry for the :bug:

Will check this out asap
