### ISSUE TITLE
Incremental Builds: _meta modifications don't rebuild

### ISSUE THREAD

**Issue by acarnwath** [pattern-lab/patternlab-node#695]
I am using Pattern Lab Node `v2.9.3` on `Mac`, with Node `v7.6.0`, using the `Gulp` Edition.

##### Expected Behavior
With incremental builds enabled, when modifications are made to `_meta/_00-head.mustache` or `_meta/_01-foot.mustache`, I would expect a complete rebuild of the project.

##### Actual Behavior
The watcher does pick up on it, but it does not appear to rebuild anything.
```
[11:10:55] Starting 'watch'...
[11:15:30] Starting 'build'...
Incremental builds enabled.
[11:16:13] Finished 'build' after 43 s
```

##### Steps to Reproduce
In patternlab-config.json, `"cleanPublic" : false`
In the project directory, run `gulp patternlab:serve`
After it is done building, make a change in `_meta/_00-head.mustache`

**Comment by bmuenzenmeyer** [comment]
Hi @acarnwath good timing - @tburny was just mentioning this to me but I was unsure if we ever created a tracking issue for it.
