### ISSUE TITLE
Document pl node features on patternlab.io

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#70]
Review and reconcile https://github.com/pattern-lab/website/tree/dev/patternlabsite/docs with current version of software

- [x] [advanced-auto-regenerate.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-auto-regenerate.md)
- [x] [advanced-clean-public.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-clean-public.md)
- [x] [advanced-config-options.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-config-options.md)
- [x] [advanced-exporting-patterns.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-exporting-patterns.md)
- [x] <del>[advanced-generating-css.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-generating-css.md)</del> Not implemented
- [x] <del>[advanced-integration-with-compass.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-integration-with-compass.md) </del> Not implemented
- [x] <del> [advanced-integration-with-grunt.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-integration-with-grunt.md) </del> Not applicable. PL Node uses Grunt or Gulp as foundational portions
- [x] [advanced-keyboard-shortcuts.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-keyboard-shortcuts.md)
- [x] [advanced-page-follow.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-page-follow.md)
- [x] [advanced-pattern-lab-nav.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-pattern-lab-nav.md)
- [x] [advanced-reload-browser.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/advanced-reload-browser.md)
- [x] [command-line.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/command-line.md)
- [x]  <del>[command-prompt-windows.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/command-prompt-windows.md) </del> Not applicable
- [x] [data-json-mustache.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/data-json-mustache.md)
- [x] [data-link-variable.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/data-link-variable.md)
- [x] [data-listitems.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/data-listitems.md)
- [x] [data-pattern-specific.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/data-pattern-specific.md)
- [x] [editing-source-files.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/editing-source-files.md)
- [x] [first-run.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/first-run.md)
- [x] [index.html](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/index.html)
- [x] [installation.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/installation.md)
- [x] [pattern-add-new.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-add-new.md)
- [x] [pattern-adding-annotations.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-adding-annotations.md) - identical, no references
- [x]  <del>[pattern-converting.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-converting.md)</del> - looks like a dead file
- [x] [pattern-header-footer.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-header-footer.md)
- [x] [pattern-hiding.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-hiding.md) - identical, no references
- [x] [pattern-including.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-including.md)
- [x] [pattern-linking.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-linking.md)
- [x] [pattern-managing-assets.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-managing-assets.md)
- [x] [pattern-mobile-view.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-mobile-view.md) - not implemented
- [x] [pattern-organization.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-organization.md)
- [x] [pattern-parameters.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-parameters.md)
- [x] [pattern-pseudo-patterns.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-pseudo-patterns.md)
- [x] [pattern-reorganizing.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-reorganizing.md)
- [x] [pattern-states.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-states.md)
- [x] [pattern-stylemodifier.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-stylemodifier.md)
- [x] [requirements.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/requirements.md)
- [x] [upgrading.md](https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/upgrading.md)

### NEW THINGS

- [x] Grunt vs Gulp - added to install.md

**Comment by bmuenzenmeyer** [comment]
Progress has started on this here: https://github.com/bmuenzenmeyer/website

Opened an issue for each proposed page:

 - [x] https://github.com/bmuenzenmeyer/website/issues/1
 - [x] https://github.com/bmuenzenmeyer/website/issues/2
 - [ ] https://github.com/bmuenzenmeyer/website/issues/3
 - [ ] https://github.com/bmuenzenmeyer/website/issues/4
 - [ ] https://github.com/bmuenzenmeyer/website/issues/5
 - [ ] https://github.com/bmuenzenmeyer/website/issues/6
 - [ ] https://github.com/bmuenzenmeyer/website/issues/7
 - [ ] https://github.com/bmuenzenmeyer/website/issues/8
 - [ ] https://github.com/bmuenzenmeyer/website/issues/9
 - [ ] https://github.com/bmuenzenmeyer/website/issues/10
 - [ ] https://github.com/bmuenzenmeyer/website/issues/11
 - [ ] https://github.com/bmuenzenmeyer/website/issues/12
 - [ ] https://github.com/bmuenzenmeyer/website/issues/13
 - [ ] https://github.com/bmuenzenmeyer/website/issues/14
 - [ ] https://github.com/bmuenzenmeyer/website/issues/15
 - [ ] https://github.com/bmuenzenmeyer/website/issues/16
 - [ ] https://github.com/bmuenzenmeyer/website/issues/17
 - [ ] https://github.com/bmuenzenmeyer/website/issues/18
 - [ ] https://github.com/bmuenzenmeyer/website/issues/19
 - [ ] https://github.com/bmuenzenmeyer/website/issues/20
 - [ ] https://github.com/bmuenzenmeyer/website/issues/21
 - [ ] https://github.com/bmuenzenmeyer/website/issues/22
 - [ ] https://github.com/bmuenzenmeyer/website/issues/23
 - [ ] https://github.com/bmuenzenmeyer/website/issues/24
 - [ ] https://github.com/bmuenzenmeyer/website/issues/25
 - [ ] https://github.com/bmuenzenmeyer/website/issues/26
 - [ ] https://github.com/bmuenzenmeyer/website/issues/27
 - [ ] https://github.com/bmuenzenmeyer/website/issues/28
 - [ ] https://github.com/bmuenzenmeyer/website/issues/29
 - [ ] https://github.com/bmuenzenmeyer/website/issues/30

**Comment by bmuenzenmeyer** [comment]
If anyone wants to help with the above, feel free to send a PR to the node-docs branch of https://github.com/bmuenzenmeyer/website

**Comment by bmuenzenmeyer** [comment]
First revision created and sent for PR review. https://github.com/pattern-lab/website/pull/34

**Comment by bmuenzenmeyer** [comment]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Well, this feels good. <a href="https://t.co/hCRfOR1jyo">https://t.co/hCRfOR1jyo</a> &#10;All Pattern Lab Node features documented alongside Pattern Lab PHP. Now to close some gaps!</p>&mdash; Brian Muenzenmeyer (@bmuenzenmeyer) <a href="https://twitter.com/bmuenzenmeyer/status/673010663577419776">December 5, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by bradfrost** [comment]
Great work!

**Comment by bmuenzenmeyer** [comment]
Thanks Brad. It was good to see how far it's come and see how much depth there is in the pattern lab product itself
