### ISSUE TITLE
Pass theme config to front end

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#700]
https://github.com/pattern-lab/styleguidekit-assets-default/issues/75

**Comment by waseem18** [comment]
Can I take this up as a part of hacktoberfest @bmuenzenmeyer ?

**Comment by bmuenzenmeyer** [comment]
already done - sorry

![image](https://user-images.githubusercontent.com/298435/31053804-02eabf8a-a66b-11e7-9055-47fd0920e305.png)

**Comment by waseem18** [comment]
Cool! No worries
