### ISSUE TITLE
Support Async Rendering

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#707]
This one's for you, @geoffp 

Somehow we never made an issue for this.

This should support a number of endeavors we are pursuing:

- [ ] React Engine
- [ ] Twig Engine
- [ ] Liquid Engine
- [ ] Web/HTTP?
- [ ] Performance Increases?

**Comment by sghoweri** [comment]
^ also add native PHP Twig support to this as well. 

Spent most of the day today spinning my wheels trying to get async PHP-based Twig templates working with some level of success (success in that I can get compiled template responses from the PHP side of the house + managed to hack together some critically needed file path info that's required for those templates to compile successfully) however without a callback or support for Promises (or something to that effect) I'm hitting a bit of a brick wall here. =/

CC @EvanLovely

**Comment by bmuenzenmeyer** [comment]
> Spent most of the day today spinning my wheels trying to get async PHP-based Twig templates working with some level of success

@geoffp has the work in flight - I'd suggest we wait for it to land before moving forward with #554 and #285

**Comment by sghoweri** [comment]
Yeah - I mentioned the same thing to Evan yesterday. Putting this on ice till async support lands.

**Comment by geoffp** [comment]
I'm on it. I'll make time this week and next.

**Comment by tburny** [comment]
I'd like to suggest testing with https://github.com/tburny/patternengine-node-noop if it is useful somehow :)

**Comment by geoffp** [comment]
🎉
