### ISSUE TITLE
Support view all pages in pattern linking

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#714]
Implement https://github.com/pattern-lab/the-spec/issues/35

Pattern Lab exports `patternPaths` and `viewAllPaths` separately to the UI within [ui_builder](https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/ui_builder.js#L555-L591), since they've never had to co-mingle prior to this spec enhancement.

Then, when patterns are linked, I believe they are checked only against `patternPaths` to resolve the location.

The first thing I'd try would be to concatenate `viewAllPaths` into the `patternPaths` export and then see if a link like `<a href="{{ link.viewall-atoms-all }}">Go to all Atoms</a>` works (assuming you have a Pattern Type called atoms).

If that doesn't work, more tech design needs to occur.

**Comment by JosefBredereck** [comment]
Fixed with #1143 in [V5.12.0](https://www.npmjs.com/package/@pattern-lab/core)
