### ISSUE TITLE
Remove vestigial configuration entries

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#745]
While documenting PL Node 3.0 configuration I found the following dead config entries:

- [ ] `ignored-extensions`
- [ ] `ignored-directories`

Check that these are removed from:

- [x] this repo
- [x] edition-node-gulp
- [x] edition-node-grunt
- [x] edition-node
- [ ] edition-node-webpack
- [x] cli

**Comment by bmuenzenmeyer** [comment]
@mbulfair made any progress on your end?

**Comment by bmuenzenmeyer** [comment]
calling this done as a tracking issue has been opened in the comcast repo

**Comment by mbulfair** [comment]
Removed from webpack edition for future releases
