### ISSUE TITLE
Add mechanism to call serve without first building

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#752]
`serve()` should be altered so a user can call `serve()` (the internal function below) without first building.

``` js
    serve: function (options) {
      options.watch = true;
      return this.build(() => {}, options).then(function () {
        serve(patternlab);
      });
    },
```

I am thinking an option that would change the code to something like

``` js
    serve: function (options) {
      if (options.serveOnly) {
        serve(patternlab);
        return Promise.resolve();
      }      
      options.watch = true;
      return this.build(() => {}, options).then(function () {
        serve(patternlab);
      });
    },
```

this is pseudocode, but I think it'd work

**Comment by bmuenzenmeyer** [comment]
Is this a capability people find missing in their workflow?
Is it really that much of a burden, in a world with incremental builds, to have PL do it's thing prior to local serving?

**Comment by raphaelokon** [comment]
In any way: If it is viable to our users, we should have two dedicated functions imho.

**Comment by bmuenzenmeyer** [comment]
Closing this for now
