### ISSUE TITLE
Pseudopatterns not working in version 2.12.0

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#755]
I suspect not everyone will be able to upgrade to 3.0.0 immediately.

Porting #744 into 2.X will help current users

**Comment by raphaelokon** [comment]
The issue title says #744, but #714 is linked

**Comment by bmuenzenmeyer** [comment]
fixed

**Comment by acarnwath** [comment]
For clarity (because I keep coming back to reference this question!): I'm having issues that seem to start in 2.11.0, if I downgrade to 2.10.0 I no longer see problems.

**Comment by bmuenzenmeyer** [comment]
hey @acarnwath thanks for the confirmation! I realized while re-reading this thread (especially my comment "fixed it") might suggest that this is no longer a 2.X issue. 

This issue remains open as a good first contribution for someone to take on. #744 provides a pretty straightforward changeset to apply against https://github.com/pattern-lab/patternlab-node/tree/v2.12.0

**Comment by JosefBredereck** [comment]
This isn't an issue anymore ?! 🤞
