### ISSUE TITLE
Server Error when viewing pattern info under mustache on staging site

### ISSUE THREAD

**Issue by jephjohnson** [pattern-lab/patternlab-node#767]
I am using Pattern Lab Node `Pattern Lab / Node - v2.12.0` on `Mac`, with Node `v9.3.0`, using the `Webpack` Edition.

##### Expected Behavior
I should be able to view the mustache partials when viewing pattern info when my site is hosted online. This works fine when I am viewing locally.

##### Actual Behavior
I am getting a 404

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

##### Steps to Reproduce
- host your 'public' folder on your server
- view 'mustache' under 'show pattern info' from the dropdown menu in the top right

**Comment by jephjohnson** [comment]
@bmuenzenmeyer - Any thoughts on this?

**Comment by bmuenzenmeyer** [comment]
@jephjohnson this looks like something that was attempted to be fixed by the likes of https://github.com/pattern-lab/patternlab-node/pull/649

In Pattern Lab of days past, we have a `basePath` property in the configuration that passed through to the frontend in order to support this behavior. I think we will revisit this behavior in the next few weeks. I see it as a more tenable option after we convert to a monorepo

**Comment by jephjohnson** [comment]
@bmuenzenmeyer - Cool, thanks for the update

**Comment by lizannemarie** [comment]
Hello! We had this issue, and found declaring the mime type for the partials in the web.config caused the partials to render in the tabs :) (Running on IIS)

`<configuration>
<system.webServer>
<staticContent>
 
<mimeMap fileExtension=".mustache" mimeType="application/mustache" />
 
</staticContent>
</system.webServer>
</configuration>`

**Comment by HalfdanDK** [comment]
lol

**Comment by HalfdanDK** [comment]
[www.nog.dk](url)

**Comment by bmuenzenmeyer** [comment]
do you have something to say @HalfdanDK ?
