### ISSUE TITLE
Investigate why PL Node does not render the Demo homepage correctly

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#781]
http://demo.patternlab.io/?p=pages-homepage when run with Pattern Lab Node does not show you the blog posts. The header also seems off. The demo uses a lot of native arrays, with data merging of page-level json. Investigate, fix, cover with unit tests

Expected

![image](https://user-images.githubusercontent.com/298435/35172729-659beb94-fd2e-11e7-9c20-11c193ffa59e.png)

Actual

![image](https://user-images.githubusercontent.com/298435/35172716-55b1eef4-fd2e-11e7-8d77-32833511ed74.png)

**Comment by bmuenzenmeyer** [comment]
🕵️ After some investigation - I've discovered the culprit: [block-media@inreview.mustache](https://github.com/pattern-lab/starterkit-mustache-demo/blob/develop/dist/_patterns/01-molecules/blocks/block-media%40inreview.mustache) when included across two different patterns. In the case above, the home page renders this fine but subsequent renders do not. Rather that track down the exact reason for this, we are dropping support for the old method in favor of the [markdown approach](https://github.com/pattern-lab/the-spec/issues/16)

This syntax for [documenting patterns](http://patternlab.io/docs/pattern-documenting.html) has been for a while to use the companion markdown file instead of this file convention. Removing the `@inreview` from the filename restores the functionality expected. 

Adding a note in the [upgrade instructions](https://github.com/pattern-lab/patternlab-node/wiki/Upgrading) about this.

**Comment by bradfrost** [comment]
Nice sleuthing, @bmuenzenmeyer!

**Comment by bmuenzenmeyer** [comment]
Thanks @bradfrost  - I've also replaced that code within https://github.com/pattern-lab/starterkit-mustache-demo/commit/16c7961a5e747a211c4c1a4068dd365eab470b6c
