### ISSUE TITLE
Pattern Lab picks up README from empty source/_patterns dir

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node#786]
I am using Pattern Lab Node `v3.0.0-alpha.7`  using the `Gulp` Edition.

##### Expected Behavior
Expected to silently ignore an empty `source/_patterns` dir

##### Actual Behavior
```
Finished 'patternlab:build'
Could not find pattern referenced with partial syntax README.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.
```
##### Steps to Reproduce
(Assuming you have Pattern Lab v3-alpha.7 linked)
1. Install `edition-node-gulp-2.0.0-alpha.1`
2. Run `gulp patternlab:build`

**Comment by bmuenzenmeyer** [comment]
It appears to me as if every `.md` file is getting picked up, when before they were fine. We need to investigate further.

**Comment by raphaelokon** [comment]
That is very likely to be true :-)

**Comment by reinos** [comment]
Same problem here for the .md files. But we also have this problem on simple patterns with just some HTML an no other fancy stuff.

```
Could not find pattern referenced with partial syntax README.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or with
in data as a link.
Could not find pattern referenced with partial syntax gallery\00-gallery.ee. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different temp
late or within data as a link.
Could not find pattern referenced with partial syntax gallery\00-gallery.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different temp
late or within data as a link.
Could not find pattern referenced with partial syntax navigation\00-navigation.ee. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a differen
t template or within data as a link.
Could not find pattern referenced with partial syntax navigation\00-navigation.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a differen
t template or within data as a link.
Could not find pattern referenced with partial syntax navigation\01-navigation-1.ee. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a differ
ent template or within data as a link.
Could not find pattern referenced with partial syntax navigation\01-navigation-1.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a differ
ent template or within data as a link.
```
![image](https://user-images.githubusercontent.com/633730/36542309-c3f8291a-17e0-11e8-8e84-eebe84db9030.png)

in the final build it looks that the structure has been made, but the content is missing
![image](https://user-images.githubusercontent.com/633730/36542399-fd10c8f6-17e0-11e8-8ca0-4f31e6b9536a.png)

**Comment by bmuenzenmeyer** [comment]
@raphaelokon found the bug

in PL 2.12.0 this same logic is done here:

https://github.com/pattern-lab/patternlab-node/blob/v2.12.0/core/lib/pattern_assembler.js#L395-L399

``` js

 for (i = 0; i < patternlab.patterns.length; i++) {
      if (patternlab.patterns[i].relPath === file) {
        currentPattern = patternlab.patterns[i];
      }
    }

```

Over the course of refactoring I decided that this logic was close enough to `get()` that it would cover the cases we want - excepting that the new method tries to be informative about missing files.

**Comment by TheTravisM** [comment]
Is there a solution to this issue?

**Comment by JaiDoubleU** [comment]
> Is there a solution to this issue?

Same question here.  I'm seeing it in patternlab node 3.0

**Comment by puppycodes** [comment]
+1
