### ISSUE TITLE
Overwrite listItems.json from higher lvl include

### ISSUE THREAD

**Issue by DruMasterMunch** [pattern-lab/patternlab-node#789]
I am using Pattern Lab Node `v1.4.0` on `Windows`, with Node `v6.11.0`, using the `Gulp ` Edition.

Hi,

Maybe i'm juste missing something. I have a simple includes chain :
organism > molecule > atom

atom.mustache : 
`
... output a bunch of listitems variables ...
{{test}}
`

molecule.mustache: 
```
{{#listItems.twelve}}
        {{> atoms-atom}}
{{/listItems.twelve}}
```
organism.mustache:
`{{>molecules-molecule}}`

##### Expected Behavior
organism.json should be able to pass a variable "test": "data" to atom.mustache
And my organism should display 12 atoms containing listitems variables followed by "data"

##### Actual Behavior
molecule.json can achieve that, it works 
organism.json don't, the "data" is never displayed

Removing the "listitems" loop solve the problem, and my organism display "data", but juste once (and ofc, i loose all my listitems datas)

I suppose molecule.json, being on the same level as the listitems calls, can overwrite it, whereas organism.json can't.

##### Steps to Reproduce
Take a fresh 1.4 install, and follow my file structure above.

I really hope there's a way to get this work, i've thought about some workaround (using simple lists, reorganizing patterns...), but none of them is a viable option for my purpose.

Thanks for your time

**Comment by bmuenzenmeyer** [comment]
Hello @DruMasterMunch 

can you provide the exact files you are using, either as text here or as a ZIP file?

**Comment by DruMasterMunch** [comment]
Hi,

No problem, i'll be more specific :

Unzip "plab1.4-ListitemsIssue.zip" at root level of a fresh 1.4 patternlab-gulp install.

1)
npm install > gulp patternlab:serve
You should see one atom, one molecule, and one organism, each pattern has a data.json attached.
In patternlab, you should notice that

- Atom render the listItems data and the data from atom.json

- Molecule render a list of 12 atoms, with listItem data and the data form molecule.json

- Organism render the list of 12 atoms with listItems data, **but data form molecule.json**

**==> It should render the data form organism.json**

2) 
Go to source\_patterns\01-molecules\molecule.mustache, and remove the listItems, leaving only one include of atoms-atom :
`{{>atoms-atom}}`

Go to patternlab, and see that the organism render now the **data form organism.json**

**If listItems is not used, it behaves as it should**

3)
Take back the listItems in \_patterns\01-molecules\molecule.mustache:
`{{#listItems.twelve}}
    {{>atoms-atom}}
{{/listItems.twelve}}`

Now remove the \_patterns\01-molecules\molecule.json file.
Go to patternlab and see that the organism render no data at all from "text" variable, not even form atom.json

**I think that pattern using listItems.json, car be overwritten only by json file on the same level (here molecule). If there is no such file, the data is searched in listItems.json. Here, as the data doesnt exists in listItems.json, the data is not displayed.**

4)
Going further => You can set an "text": "data from listItems.json" variable for each item in listItems.json.
If you do so, you will notice that just the atom level display data from atom.json. The molecule and organism display both data from litsItems.json.
If you want to test it, you can take my modified "listitems.zip"

Could be great to have a way to overwrite variable from the calling pattern (here the organism), that bypass listItems.json.


[listitems.zip](https://github.com/pattern-lab/patternlab-node/files/1674025/listitems.zip)
[plab1.4-ListitemsIssue.zip](https://github.com/pattern-lab/patternlab-node/files/1673929/plab1.4-ListitemsIssue.zip)
