### ISSUE TITLE
Investigate improvements to plugin system

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#812]
taken from chat:

as for the plugin no longer working, i cannot be certain but a player in all of this with 3.0 is that with the introduction of the async rendering stack, plugins may no longer execute properly. what should probably be done is a registration of plugins and events they care about, with each being registered with a handler that returns a promise (unless I suppose some plugins could opt out as truly fire-and-forget, unmanaged event handlers?). i don't see any other way around this. i think plugins worked via luck in 2.X due to the synchronous nature of the whole stack, but pushing more core processing into the async side exposes these flaws.

**Comment by mdmccarley89** [comment]
I was able to get the installPlugin function working in our setup. However, on the next run of patternlab, it errors when it reaches findModules.js. It appears that the issue is related to the hardcoded string 'plugin-' that is being passed in.

**Comment by bmuenzenmeyer** [comment]
https://github.com/sindresorhus/p-event
https://www.npmjs.com/package/event-to-promise

**Comment by JosefBredereck** [comment]
Is this the leading issue for this task?

**Comment by bmuenzenmeyer** [comment]
this was resolved with #1066 IMO
