### ISSUE TITLE
Move engine-nunjucks into this repo

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#814]
In talking with @danwhite85 he expressed interest in being brought into the fold.

**Comment by bmuenzenmeyer** [comment]
@danwhite85 this is now on `dev` !

**Comment by danwhite85** [comment]
Awesome! How would you like me to handle future changes? Just fork +  PR?

**Comment by bmuenzenmeyer** [comment]
I added you to the repo as a collaborator - so you should be able to directly push branches.
PRs still best for changes, however
