### ISSUE TITLE
header.hbs is hidden in the Pattern Navigation

### ISSUE THREAD

**Issue by simonknittel** [pattern-lab/patternlab-node#818]
I am using Pattern Lab Node `v2.12.0` on `Mac`, with Node `v8.9.4`, using a `Custom` Edition.

##### Expected Behavior
Organism called header.hbs shows up in the navigation.

##### Actual Behavior
Organism called header.hbs doesn't show up in the navigation.

We could reproduce this issue on two different PatternLab projects. One is brand new and the other one is older but always up-to-date with the patternlab-node version. On the older instance it also worked before.

##### Steps to Reproduce
- Create an organisms called header.hbs
- Start PatternLab
- Look for HEADER in the navigation (you won't find it)

###### Workaround
- Create an organisms called site-header.hbs
- Start PatternLab
- Look for SITE HEADER in the navigation

**Comment by JosefBredereck** [comment]
@bmuenzenmeyer this works in the current version. Do we want to keep this old issue from 2018?

**Comment by bmuenzenmeyer** [comment]
closing. thanks @JosefBredereck !
