### ISSUE TITLE
Reconcile Pattern Lab vs patternlab

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#819]
In output, when we reference PL - we should be consistent in our use of the library name

https://github.com/pattern-lab/patternlab-node/blob/master/packages/core/src/lib/help.js#L10

https://github.com/pattern-lab/patternlab-node/blob/master/packages/cli/bin/cli-actions/version.js#L7

https://github.com/pattern-lab/patternlab-node/commit/0cb2995db04a5ba73e0e76bca3dc55cee7ea5eeb#diff-1da9fc5f8fb91e94f5812701a7961123R38

I've also seen `PatternLab`

**Comment by castastrophe** [comment]
@bmuenzenmeyer I can help fix this; I'm looking for a good first issue.   To confirm, Pattern Lab (uppercase with space) is preferred, correct?

**Comment by castastrophe** [comment]
I see this is was actually already addressed in #856 - nevermind!  :D

**Comment by bmuenzenmeyer** [comment]
@castastrophe yes I think I took care of most of it, but you're welcome to review an of the other messaging for consistency, or check out other [good first issues](https://github.com/pattern-lab/patternlab-node/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue+%3Amortar_board%3A%22)
