### ISSUE TITLE
[cli] Output not rendering correctly

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#830]
I am using `cli@0.0.1-alpha.14` on Windows

##### Expected

```
⊙ patternlab → build: Yay, your PatternLab project was successfully built ☺
```

##### Actual - MINGW32

![image](https://user-images.githubusercontent.com/298435/37832097-94e2ae42-2e75-11e8-9f52-ebb0612bf66b.png)

##### Actual - Command Prompt

![image](https://user-images.githubusercontent.com/298435/37832093-8f0ef17e-2e75-11e8-8145-be0d738c4740.png)

##### Actual - Powershell

![image](https://user-images.githubusercontent.com/298435/37832080-85e4f4e0-2e75-11e8-8dc3-f9d5a8cfdf77.png)

**Comment by bmuenzenmeyer** [comment]
@raphaelokon I think we discussed this once - it'd be great if we could get this working - I really love the `⊙ patternlab →` part

**Comment by raphaelokon** [comment]
Hmm … I guess this is a user land problem. See https://github.com/nodejs/node-v0.x-archive/issues/7940 and is related to `chcp`

**Comment by bmuenzenmeyer** [comment]
I wasnt able to get it working quite yet - but I appreciate this documentation. It could help others!
