### ISSUE TITLE
Rename annotations.js to annotations.json

### ISSUE THREAD

**Issue by henk23** [pattern-lab/patternlab-node#836]
It's a json file, so why does it have a js file ending?
My IDE complains about corrupted js syntax and I think it is right about it.
What am I not seeing here?

**Comment by bmuenzenmeyer** [comment]
@henk23 it's a good question!

what you aren't seeing is the support for the legacy Pattern Lab annotations file - which was a js file instead of JSON/YML.  Since we are in 3.0 Alpha mode anyways, it'd be smart to fix this once and for all, which will make the code simpler too!

**Comment by bmuenzenmeyer** [comment]
fixed
