### ISSUE TITLE
Patterns without ##- file name prefixes do not display correctly in the menu

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#84]

**Comment by e2tha-e** [comment]
@bmuenzenmeyer I think this was fixed in pr #157

**Comment by bmuenzenmeyer** [comment]
@e2tha-e could very well be - I had some similar hunches. I'll make sure to double check once I overcome this pesky cold and revert my environment from node 4...

**Comment by bmuenzenmeyer** [comment]
@e2tha-e you are right. resolved and removed from roadmap
