### ISSUE TITLE
[cli] help does not call core help

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#842]
As people will increasingly use the CLI as part of their workflow, I'd argue that the help command from the CLI should in some capacity emit the core help. What do you think @raphaelokon ?

**Comment by raphaelokon** [comment]
Sorry for my late response … this one slipped through somehow. What are the contents of the core's help and the intentions to emit its help … the core is a core module that should not expose any help imho.
