### ISSUE TITLE
UIKit excluded tag support

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#844]
As part of #811 and #840 we hoped to deliver `excludedTags` support within a UIKit. This is certainly possible, but I wanted to release early with state support first.

If someone wants to take on this work it would look similar to https://github.com/pattern-lab/patternlab-node/pull/840/commits/87c9d0d2c315d9f6060df70fc41a7f4a9a5e9f9d

* add this filter to `uikitExcludePattern`
* add tests

**Comment by Hydraner** [comment]
Hey @bmuenzenmeyer , thanks for the great work on PL3. I am currently using tons of the "new" stuff and fought already a couple of issues and created PR's.

I'm not so much into node development so I hope to get some feedback to make things as good as possible to get some things commited.

I also didn't manage to get the test suite up and running, so all tests I wrote so far have been produced in blind flight mode. It would be great if you could give me some advice on this.

This issue should also fix #1079
