### ISSUE TITLE
Determine why lerna thinks additional packages are changed when they arent

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#850]
[This PR](https://github.com/pattern-lab/patternlab-node/pull/849) generated this publish: 

![image](https://user-images.githubusercontent.com/298435/39637679-617918ae-4f89-11e8-97bf-b1fb286d44f8.png)

**Comment by sghoweri** [comment]
@bmuenzenmeyer are you sure Lerna isn’t working exactly as expected here? 

Keep in mind that doing a publish with Lerna not only version-bumps the packages changed directly (ex. CLI and Core in your example ^), but ALSO updates the dependency versions of other packages that depend on those packages changed (ex. edition-node-gulp and edition-node, both of which depend on those CLI and Core packages that had the original changes).

Something to look into just in case! 😉

**Comment by bmuenzenmeyer** [comment]
I think you are right - my continued use of lerna at work has helped me understand this better.
