### ISSUE TITLE
When serving, patterns are not rebuilt on save

### ISSUE THREAD

**Issue by danwhite85** [pattern-lab/patternlab-node#852]
When serving, patterns are not rebuilt on save. Using 3.0.0-alpha.13

##### Expected Behavior
Patterns would be rebuilt, the browser reloaded, and changes displayed
##### Actual Behavior
Browser reloads, but no changes displayed. 
##### Steps to Reproduce
Setup a clean instance of [edition-node ](https://github.com/pattern-lab/patternlab-node/tree/master/packages/edition-node). Create a pattern. Serve. Modify pattern.

**Comment by taylor-benson** [comment]
I can confirm this as well, it looks like when I downgrade the following:
@pattern-lab/core": "^3.0.0-alpha.13" to 3.0.0-alpha.11 patterns rebuild on change.  

I have tried 3.0.0-alpha.12 and the patterns don't rebuild, so I would assume the breaking change was pushed with 3.0.0-alpha.12, @bmuenzenmeyer

**Comment by bmuenzenmeyer** [comment]
Thanks for the report - this frustrates me because it was the very thing I just spent a ton of time fixing. Need to see what regressed.
