### ISSUE TITLE
Move to Node 8

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#870]
Dropping 6 in favor of 8 will move with the Node LTS "Active" schedule, the industry as a whole, and allow us to use newer language features like async / await

- [ ] nvmrcs
- [ ] travis environments
- [ ] package.json engines
- [ ] documentation / README / shields

**Comment by EvanLovely** [comment]
Love this. Gotta say: `async` / `await` is super handy & much more readable than other approaches.

**Comment by benhalverson** [comment]
Hey @bmuenzenmeyer Do you mind if I work on this?

**Comment by sghoweri** [comment]
Reopening — my gut tells me that this should be pretty straight forward to bang out the minimum updates needed for this (aka we could upgrade to Node 8 but hold off refactoring any logic to use async/await till a later batch of updates).

**Comment by bradfrost** [comment]
@sghoweri That sounds good. I wouldn't trust me to do that upgrade, but in any case I'd hope the universe doesn't blow up by upgrading.

**Comment by benhalverson** [comment]
@bradfrost This is already done see #951 and https://github.com/pattern-lab/patternlab-node/pull/951#issuecomment-424449024 about going to node 10 instead of 8

**Comment by bradfrost** [comment]
@benhalverson ah thanks for the heads up. @sghoweri does this sort you out?

**Comment by sghoweri** [comment]
Closing this out. Going with Node >=10 sounds great to me (lots of optimizations we’ll be able to get in) and the updates bumping the min version needed (#951) shipped with the latest beta we cut last week!
