### ISSUE TITLE
[cli] plugin installation not working

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#873]
Steps to reproduce:

* branch `plugin-work`
* add `"@pattern-lab/plugin-tab": "^2.0.3-alpha.3", ` to `packages/edition-node-gulp/package.json`
* from root, `lerna bootstrap`

```
npm run patternlab install --plugins @pattern-lab/plugin-tab
```

not working

```
λ npm run patternlab install --plugins @pattern-lab/plugin-tab
> @pattern-lab/edition-node-gulp@2.0.0-alpha.11 patternlab D:\src\patternlab-node\packages\edition-node-gulp
> patternlab "install" "@pattern-lab/plugin-tab"
(node:10096) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'config' of undefined
(node:10096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bmuenzenmeyer** [comment]
@raphaelokon any ideas on this one. also pinged you on gitter

**Comment by raphaelokon** [comment]
@bmuenzenmeyer I'll take a look. Seems like it is missing the patternlab config. Have you initiated a project first?

**Comment by bmuenzenmeyer** [comment]
This is running inside the monorepo,  within packages/edition-node-gulp

**Comment by bmuenzenmeyer** [comment]
This is also not working with a live version of the CLI

**Comment by raphaelokon** [comment]
@bmuenzenmeyer You need to escape the args like so …
`npm run patternlab -- install --plugins @pattern-lab/plugin-tab`

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Also:
```js
const safePluginName = _.kebabCase(name); // Messes with scoped packages
```

**Comment by fallenturtle** [comment]
Is there a solution to the issue with using a plugin in PL3 where it says "Error: ENOENT: no such file or directory, scandir 'plugin-'" when you run gulp?

**Comment by raphaelokon** [comment]
@fallenturtle Not from the top of my head – I'll look into it.

**Comment by wasnlosdu** [comment]
I've created a test repo to reproduce the error.
https://github.com/wasnlosdu/patternlab-plugin-error-report

Hope this helps to resolve this issue

**Comment by aleksip** [comment]
This is still relevant, I think?

**Comment by sghoweri** [comment]
@aleksip I think this is still relevant but I also think we need to modernize how we handle plugins — basically how the Pattern Lab ecosystem can better support flexibility / extendability without compromising stability.

 For example, do we really need a `plugin` for adding new Tabs if the UI is an easy to customize web component? Maybe? (for providing data to pipe into that web component).

Schemas, Documented APIs, and Tests will help us get there.

**Comment by bradfrost** [comment]
@aleksip @sghoweri yep all around. Definitely want plugins to remain a crucial part of the Pattern Lab world (and from my end do a better job rounding them up and documenting them), but we want plugins to feel a nice layer on top of a solid foundation. As Salem is mentioning, there's definitely some opportunities to make certain parts more flexible and extensible, which I'm all in favor of.
