### ISSUE TITLE
Support for patternlinks

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#89]
https://github.com/pattern-lab/patternlab-php/blob/52eae82235f7f8f4d31410c189c20dc54ecf9e67/core/lib/PatternLab/Builder.php LINE 661

http://patternlab.io/docs/data-link-variable.html

**Comment by bmuenzenmeyer** [comment]
This is done.

:+1:

**Comment by bramsmulders** [comment]
It seems that the PHP version also supports pattern linking through data:
https://github.com/pattern-lab/patternlab-php/issues/161
It is undocumented, but it is still a feature alot of people like to see in the node version i guess.

**Comment by bmuenzenmeyer** [comment]
Hi @bramsmulders 

check out `.\source\_patterns\01-molecules\05-navigation\00-primary-nav.mustache` It has an arbitrary example to showcase this functionality. 

`<li><a href="{{ link.pages-homepage }}">Home</a></li>`

**Comment by bramsmulders** [comment]
@bmuenzenmeyer yep, that part of the code is in, and works super awesome. But what @bradfrost & @dmolsen were talking about was doing this in data: 

```
"foo": {
    "url" : "link.pages-about"
}
```
And read that out like this:
```
{{# foo }}
<a href="{{ url }}">Foo</a>
{{/ foo }}
```

And there the `{{url}}` is parsed and a correct link to the pattern in injected. This is currently not working in the node version of patternlab.

**Comment by bmuenzenmeyer** [comment]
hi @bramsmulders now I understand. Thanks for clarifying. I've created https://github.com/pattern-lab/patternlab-node/issues/171 to handle this
