### ISSUE TITLE
[cli] Running patternlab init in a directory without a package.json should create one

### ISSUE THREAD

**Issue by hdwebpros** [pattern-lab/patternlab-node#891]
I am using pattern-lab/cli@0.0.1-alpha.23 on `Windows, with Node `v9.9.0`, using a Vanilla Edition.

##### Expected Behavior
`npm install @pattern-lab/cli --save-dev` creates a package.json

##### Actual Behavior
It does not create a package.json

##### Steps to Reproduce
Open cmd in windows. Navigate to a blank folder. Run
`npm install @pattern-lab/cli --save-dev`
You get the `node_modules` folder and a `package-lock.json` file, but no package.json file

**Comment by hdwebpros** [comment]
Closing. This command needs a package.json file to run properly to begin with

**Comment by bmuenzenmeyer** [comment]
This was recently raised as an idea by @geoffp too - I think it a smart idea that would make for a simpler experience.

**Comment by bmuenzenmeyer** [comment]
@raphaelokon can you help make this possible?

**Comment by mfranzke** [comment]
The init of a pattern lab project is now done with `npm create pattern-lab` so I think we're save to close this issue (similar to #1142 and the problem described in that one is solved).
