### ISSUE TITLE
npm init -y && npx @pattern-lab/cli -c patternlab init fails on windows user with space

### ISSUE THREAD

**Issue by hdwebpros** [pattern-lab/patternlab-node#892]
I am trying to install @pattern-lab/edition-node@1.0.0-alpha.13 (I think) on Windows, with Node v9.9.0

##### Expected Behavior
`npm init -y && npx @pattern-lab/cli -c patternlab init` installs correctly for a user on Windows with a username with a space in it.

##### Actual Behavior
`npm init -y && npx @pattern-lab/cli -c patternlab init` creates:
```
Wrote to C:\websites\fail\package.json:
{
  "name": "fail",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Lastname\AppData\Roaming\npm-cache\_npx\10852" as it does not contain a package.json file.
```
I'm going to assume it should try to write a path to
`C:\Users\Firstname Lastname\AppData\Roaming\npm-cache\_npx\10852`

##### Steps to Reproduce
Be on Windows (10)
Make sure your folder within users has a space, like "Firstname Lastname"
Navigate to a blank folder and run `npm init -y && npx @pattern-lab/cli -c patternlab init`

**Comment by bmuenzenmeyer** [comment]
@hdwebpros can you provide your `npm -v` and `npx -v` info?

https://github.com/zkat/npx/issues/110 seems to indicate this should no longer be an issue

**Comment by hdwebpros** [comment]
NPM 6.1
NPX
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Lastname\AppData\Roaming\npm-cache\_npx\13512" as it does not contain a package.json file.
```

Which is the error with this issue

**Comment by hdwebpros** [comment]
I did find this:
https://github.com/zkat/npx/issues/146
So I ran `npm config set cache C:\tmp\nodejs\npm-cache --global`
and that seemed to cure this issue.

It also successfully installed the starter package (I have another [issue](https://github.com/pattern-lab/patternlab-node/issues/893) related to that). 

Progress!

**Comment by bmuenzenmeyer** [comment]
Excellent!

**Comment by moshiuramit** [comment]
> I did find this: [zkat/npx#146](https://github.com/zkat/npx/issues/146) So I ran `npm config set cache C:\tmp\nodejs\npm-cache --global` and that seemed to cure this issue.
> 
> It also successfully installed the starter package (I have another [issue](https://github.com/pattern-lab/patternlab-node/issues/893) related to that).
> 
> Progress!

Worked for me 
Thank you
