### ISSUE TITLE
Installing starterkit twig base errors out in Windows on PL Node

### ISSUE THREAD

**Issue by hdwebpros** [pattern-lab/patternlab-node#893]
I am trying to install [Patternlab Twig Engine](https://github.com/pattern-lab/patternlab-node/tree/master/packages/engine-twig) onto [Patternlab Node](https://github.com/pattern-lab/patternlab-node) on Windows, with Node 9.9.0

##### Expected Behavior
No errors :)

##### Actual Behavior
You get the error
```
 patternlab → Installed edition: @pattern-lab/edition-node
| ⊙ patternlab → Installing starterkit starterkit-twig-base⊙ patternlab → fetchPackage: Fetching required dependencies from npm failed for starterkit-twig-base with Error: Command failed: npm install pattern-lab/starterkit-twig-base
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR!
```

##### Steps to Reproduce
For reference, I'm using: https://github.com/pattern-lab/patternlab-node for instructions.
In Windows, open cmd and nav to a blank folder
Create a package.json. I used https://github.com/pattern-lab/patternlab-node/blob/master/package.json
Run `npm install @pattern-lab/cli --save-dev`
Then run `npm install @pattern-lab/engine-twig`
Add `"patternlab": "patternlab"` within your scripts within package.json
Then run `npm run patternlab init`
* choose root (enter) for the directory
* choose edition node
* choose starter twig base
* confirm

Then you get that error

**Comment by bmuenzenmeyer** [comment]
I cannot recreate this yet

**Comment by hdwebpros** [comment]
I have Git 2.16.1.windows.1 if that helps.

**Comment by hdwebpros** [comment]
Okay, all of my versions: 
node 9.9.0 (I wonder if that is too high?)
npm 6.1.0 (this also is a major version above yours)
php 7.2 (shouldn't matter)
composer 1.5.6 (close, shouldn't matter)
git 2.16.1 (current is 2.18)

Do you think I need to try to degrade my node and npm to match yours and try this again?

**Comment by hdwebpros** [comment]
Closing. My issue was that the package.json that I was trying to use wasn't complete enough or didn't have all the right things in it. The one I ended up using that worked was:
```
{
  "devDependencies": {
    "@pattern-lab/cli": "0.0.1-alpha.23",
    "lerna": "3.0.0-beta.21"
  },
  "scripts": {
    "bootstrap": "lerna bootstrap --hoist tap --hoist eslin* --hoist husky --hoist prettier --hoist pretty-quick",
    "precommit": "pretty-quick --staged",
    "prettier": "prettier --config .prettierrc --write ./**/*.js",
    "test": "lerna run test",
    "patternlab": "patternlab",
    "pl:build": "patternlab build --config ./patternlab-config.json",
    "pl:help": "patternlab --help",
    "pl:install": "patternlab install --config ./patternlab-config.json",
    "pl:serve": "patternlab serve --config ./patternlab-config.json",
    "pl:version": "patternlab --version"
  },
  "nyc": {
    "exclude": [
      "**/*_tests.js",
      "packages/cli",
      "packages/core/test",
      "packages/live-server"
    ]
  },
  "dependencies": {
    "@pattern-lab/engine-twig": "^0.2.1-alpha.5",
    "@pattern-lab/cli": "^0.0.1-alpha.23",
    "@pattern-lab/core": "^3.0.0-alpha.16",
    "@pattern-lab/engine-mustache": "^2.0.0-alpha.8",
    "@pattern-lab/uikit-workshop": "^1.0.0-alpha.7"
  }
}
```
and that worked. The one on https://github.com/pattern-lab/patternlab-node/blob/master/package.json didn't.

**Comment by bmuenzenmeyer** [comment]
> The one on https://github.com/pattern-lab/patternlab-node/blob/master/package.json didn't.

Yeah I wouldnt consider ever copying the package.json at the top of the monorepo, it doesn't have anything to do with the generated apps

Thanks again!
