### ISSUE TITLE
[core] PL3 does expend a given parameters used once using mustache

### ISSUE THREAD

**Issue by herrscherer** [pattern-lab/patternlab-node#912]
I am using Pattern Lab Node `v3.0.0-alpha.16` on `Mac`, with Node `v8.9.4`, using a `Gulp` Edition.

##### Expected Behavior
Parameter can be put out as often you want.
If parameter="hello!", {{ parameter }} {{ parameter }} should generate: hello! hello!

##### Actual Behavior
Parameter will be putted out only once.
If parameter="hello!", {{ parameter }} {{ parameter }} would generate: hello!

##### Steps to Reproduce
pages/test.mustache:
```mustache
{{> atoms-headline(headlineLevel: '2', label: 'Test headline level 2') }}
```

_patterns/atoms/headline.mustache:
```html
<h{{ headlineLevel }} class="{{ additionalClasses }}">{{ label }}</h{{ headlineLevel }}>
```

will result in (missing closing /h**2**)
```html
<h2 class="">Test headline level 2</h>
```

Thanks!

**Comment by bradfrost** [comment]
@herrscherer Hi there, just a heads up we're in the process of deprecating the use of pattern parameters as they aren't standard Mustache and add unnecessary complexity to the project. Soon, the default templating engine will be Handlebars, which allows parameters to be passed like so:

```
{{> atoms-headline headlineLevel="2" }}
```
In the meantime, you can pass in data using JSON both globally and at a component level, such as:

```
{
    "headlineLevel": "2"
}
```

**Comment by kraftner** [comment]
Any news on this? [The workaround above](https://github.com/pattern-lab/patternlab-node/issues/912#issuecomment-413140350) doesn't help if you're passing different parameters in the same component, something like:

```
{{> atoms-headline(headlineLevel: '2', label: 'Test headline level 2') }}
{{> atoms-headline(headlineLevel: '3', label: 'Test headline level 3') }}
```
This all has been working before. :cry:

**Comment by JosefBredereck** [comment]
I recommend using a newer version of pattern lab with handlebars engine.
Migrating files
1. Copy into project
2. Rename all file extensions
Windows
`forfiles /S /M *.mustache /C "cmd /c rename @file @fname.hbs"`
3. change call of {{> pattern(param: '1', param2:'2') }} to {{> pattern param="1" param2="2" }}

**Comment by bmuenzenmeyer** [comment]
closing as a workaround is mentioned above. mustache will not receive any further investment
