### ISSUE TITLE
[uikit-workshop] Remove copy-dist flag and logic from UIKit-Workshop

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#913]
Running `gulp --copy-dist=../../../public` is no longer necessary to build the uikit-workshop.

#904 cleaned this up even further to really just have to run `npm run setup && npm run watch` withi

- [ ] Update uikit-workshop/.github/CONTRIBUTING.md
- [ ] remove `copyPublic` function and calls from uikit-workshop's gulpfile

**Comment by bmuenzenmeyer** [comment]
Welcome @jbatley this is a great way to start. I would love to help you through the process.
Read through https://github.com/pattern-lab/patternlab-node/blob/master/.github/CONTRIBUTING.md and let me know if you have questions

**Comment by jbatley** [comment]
Hi @bmuenzenmeyer I believe I've followed anything correctly, any problems let me know!
