### ISSUE TITLE
Documenting Pseudo Patterns

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/patternlab-node#921]
I am using Pattern Lab Node `2.12.0` on `Mac`, with Node `v7.9.0`, using a `Gulp` Edition.

##### Expected Behavior
Creating a Markdown file that accompanies a pseudo pattern (i.e. creating `alert~negative.md` adjacent to `alert~negative.json`) should create accompanying documentation (such as `title` and description) for the negative alert pseudo-pattern.

##### Actual Behavior
Creating a file `alert~negative.md` that looks like this:

```
---
title: This is a negative alert 
---

Here is a negative description
```
Results in this output in Pattern Lab:

<img width="530" alt="screenshot 2018-08-13 11 42 00" src="https://user-images.githubusercontent.com/383701/44042384-198f056c-9eee-11e8-87b7-94c93eecac74.png">

##### Steps to Reproduce
1. Create a new pseudo pattern, such as `button~secondary.json`
2. Create a markdown file adjacent to the pseudo pattern, such as `button~secondary.md`
3. In the markdown file, create frontmatter updating the title `title: This is a secondary button` and description (raw markdown below the frontmatter)
4. Rebuild Pattern Lab and view pseudo pattern.

**Comment by heitoralthmann** [comment]
I find this behaviour to be missing from [patternlab-php](https://github.com/pattern-lab/patternlab-php) as well. Is it okay to go and recreate the issue on that project?

**Comment by bradfrost** [comment]
@heitoralthmann hey there! Thanks for the offer to recreate the issue. The trajectory of Pattern Lab involves bringing PL Node and PHP together, with PL Node serving as the main shell for most tasks (such as rendering the UI shell), but still kicking it over to the PHP engine to actually stitch together components. Issues like this are a good reason why we're moving down that path, lest we continue duplicating issues.

**Comment by heitoralthmann** [comment]
Hi @bradfrost! Thank for the kind explanation. I hope I may bring some good news to the table (for you or someone else landing on this topic):

Posting this issue on the **[Drupal Twig/#pattern-lab](https://drupaltwig.slack.com/archives/C550KL057/p1543582290001500)** slack channel I got the following answers from @aleksip:

>Try `pattern-variation.md`

And @ModulesUnraveled:

>I think @aleksip is right. For some reason, the markdown files don’t support the `~`. Just replace it with a regular `-` and you should be in business.

I hope it helps!

**Comment by bradfrost** [comment]
Awesome thanks @heitoralthmann! I think we should create an issue on the website to document this properly.

**Comment by heitoralthmann** [comment]
@bradfrost https://github.com/pattern-lab/website/issues/111 done! Do you have a suggestion as to which page this would fit best?

**Comment by bradfrost** [comment]
Going to close this out and comment on pattern-lab/website#111
