### ISSUE TITLE
.yaml and .yml support for pseudo patterns.

### ISSUE THREAD

**Issue by madhaze** [pattern-lab/patternlab-node#922]
I am using Pattern Lab Node `2.0.0` on `Linux`, with Node `v6.12.3`, using a `Grunt` Edition.

##### Expected Behavior
Tried using pseudo patterns with .yaml/.yml files.  Only looks to work with .json files.

Looking farther, I found where this is controlled:
https://github.com/pattern-lab/patternlab-node/blob/09902749958b6b7c5cdf543b3c60bd53b54d98da/packages/core/src/lib/pseudopattern_hunter.js#L27

Seems like .yaml and .yml files should also be supported.

**Comment by bmuenzenmeyer** [comment]
This would be a great enhancement! Care to write a PR?

**Comment by bryce-gilhome-cp** [comment]
Made a PR for this functionality, above
