### ISSUE TITLE
Incremental builds: Rebuild after editing JSON

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/patternlab-node#924]
I am using Pattern Lab Node 2.12.0 on Mac, with Node v7.9.0, using a Gulp Edition.

##### Expected Behavior
With `"cleanPublic" : false` set in PL's config file, incremental builds are enabled. This is great! Incremental builds should trigger when a template file (i.e. `alert.mustache`) or an accompanying data file (i.e. `alert.json`) gets updated. 

##### Actual Behavior
The incremental build only gets triggered when a template file (i.e. `alert.mustache`) gets updated. Changing `alert.json` for instance does not trigger a rebuild.

##### Steps to Reproduce
1. In `patternlab-config.json`, add the option `"cleanPublic" : false`, build PL
2. Open a pattern's accompanying data file (i.e. `alert.json` and make a change
3. Notice in the terminal that the incremental build does not trigger

Note: I'm not sure how this behavior should work with respect to global data files that live in the `_data/` folder, but I guess ideally any pattern that uses the values defined in the updated data would be rebuilt. That might be a tall order though!

**Comment by mbulfair** [comment]
@bradfrost I actually patched those issues with the webpack edition, where .json and .mustache are watched and triggered. I also made it so you can CLI pass --cleanPublic no matter what's in `patternlab-config.json`

**Comment by bradfrost** [comment]
@mbulfair very cool! Do you know what would be involved to get that into core? + @bmuenzenmeyer

**Comment by mbulfair** [comment]
It just was using webpack to watch for changes of the additional files, and it triggers a build on change.

**Comment by bradfrost** [comment]
Ah, I see! So we'd have to match that in Gulp or whatever other build process?

**Comment by mbulfair** [comment]
@bradfrost https://github.com/Comcast/patternlab-edition-node-webpack/blob/master/webpack.config.babel.js#L113-L114

**Comment by bradfrost** [comment]
WONDERFUL, thanks @mbulfair!

**Comment by mbulfair** [comment]
You're welcome @bradfrost

**Comment by bmuenzenmeyer** [comment]
I think this is fixed in 3.0. testing now

**Comment by bmuenzenmeyer** [comment]
Yes. it is. Can we close this as resolved then @bradfrost ?

**Comment by bradfrost** [comment]
@bmuenzenmeyer nice! If you tested it and it's in 3.0, then sure thing!
