### ISSUE TITLE
Unhandled promise rejection during 'npm run patternlab serve' causing patterns not being displayed

### ISSUE THREAD

**Issue by piotscig** [pattern-lab/patternlab-node#937]
I am using Pattern Lab Node v3.0.0-alpha.16 on Linux (KDE neon User Edition 5.13), with Node `v10.8.0`, using a Node Edition.

'node -v': v10.8.0
'npm -v': 6.4.1

##### Expected Behavior

After 'npm run patternlab serve' patterns should be displayed

##### Actual Behavior

Patterns are only displayed in top menu, but after clicking them nothing happens.
Atom .html file in /source is being built correctly

##### Steps to Reproduce

mkdir test-patternlab
cd test-patternlab
npm init -y && npx @pattern-lab/cli -c patternlab init

Directory for Pattern Lab project: // _[ENTER], empty input_
Edition: edition-node
Starter kit: starterkit-mustache-demo
Y

sudo npm install

// _adding required line to package.json_

sudo npm run patternlab build
sudo npm run patternlab serve

=======
Output:

> test-patternlab@1.0.0 patternlab /mnt/4F44EAD3553B133C/Strona017-StartUp/test-patternlab
> patternlab "serve"

Pattern Lab Node v3.0.0-alpha.16
Pattern Engine mustache: good to go
Incremental builds enabled.

Found a lower common denominator pattern state: inreview on molecules-block-media. Setting reverse lineage pattern organisms-media-list from <<blank>>
[...]

Built Pattern Lab front end
⊙ patternlab → build: Yay, your Pattern Lab project was successfully built ☺
⊙ patternlab → serve: Serving your files …
Pattern Lab Node v3.0.0-alpha.16
Pattern Lab Node v3.0.0-alpha.16
Pattern Engine mustache: already loaded, skipping.
Pattern Engine mustache: already loaded, skipping.
Incremental builds enabled.
Incremental builds enabled.

Found a lower common denominator pattern state: inreview on molecules-block-media. Setting reverse lineage pattern organisms-media-list from <<blank>>
[...]

Built Pattern Lab front end
Built Pattern Lab front end
Pattern Lab is watching for changes to files under source/
Pattern Lab is watching for changes to files under source/
Pattern Lab is being served from http://127.0.0.1:3000
Pattern Lab is being served from http://127.0.0.1:3000
(node:18688) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/mnt/4F44EAD3553B133C/Strona017-StartUp/test-patternlab/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
(node:18688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And patternlab doesn't work properly any more...

**Comment by piotscig** [comment]
Today I've recreated this error in a pure new pattern lab installation.

I got a pattern lab project that used to work, but later (_after node, npm etc. updates_) this strange behavior started. I've tried it on another computer and it also throws this unhandled promise rejection. And, what is worse, patterns are not being displayed :/

**Comment by bmuenzenmeyer** [comment]
May I ask why you are prepending your commands with `sudo`? 
I am able to initialize a new project (now on beta.0 as of today!) with the same options, and do not get an error when I run `npm run pl:serve`

**Comment by bmuenzenmeyer** [comment]
The instructions have changed a bit now they the node edition adds commands for users. Will update the README with https://github.com/pattern-lab/patternlab-node/issues/940
