### ISSUE TITLE
Include pseudo-pattern and have data travel with it

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/patternlab-node#938]
'm encountering this situation on a project right now.

## Use Case
An instance of Pattern Lab is used to house several demos across several products. Each demo product includes a `header` organism, but has different data (logo image, primary nav items, and other options). The user wants to be able to define that product data in exactly one place and have it be reflected on all the pages including that pseudo pattern.

## The Problem
In order to achieve a product-specific header, each JSON file associated with the demo (i.e. `demo1-homepage.json`, `demo1-contact.json`, `demo1-dashboard.json`) would need to contain the product-specific header data (i.e. `"logoImg": "demo1-logo.svg"`). That doesn't keep the data DRY, as changing the logo or primary nav items requires jumping into multiple JSON files. 

## The Proposal 
It would be great if users could create a pseudo-pattern like `header~demo1.json` and define all of the product-specific header data in that file. They can then include it elsewhere like so: `{{> organisms-header-demo1 }}` and that data defined in `header~demo1.json` would travel with it. 

## Pattern Parameters
Interestingly enough, keeping the data DRY is currently achievable using pattern parameters. Users can create a `header-demo1.mustache` file and include the header like so:

```
{{> organisms-header(logoImg: "demo1-logo.svg") }}
```

Then they can include `{{> organisms-header-demo1 }}` in all of their demo files and have the correct data appear on any page that includes the pattern that makes use of pattern parameters.

I know we're phasing out pattern parameters, and I don't know if other templating engines play nicely with this proposal, but I wanted to bring it up because it seems to be a legit use case.

**Comment by bmuenzenmeyer** [comment]
hey @bradfrost thanks for taking the time to write this up. I think it's high time we undertake https://github.com/pattern-lab/patternlab-node/projects/1#card-9342655 so we can better understand the limitations of Mustache and how it translates into our future state. 

Pattern Parameters will exist in Handlebars as first-class citizens when implemented in Handlebars and other PatternEngines.

Handlebars Partials with Parameters: https://handlebarsjs.com/partials.html#partial-parameters

What say you? port of the HikeTracker, or something else entirely?

**Comment by sghoweri** [comment]
For what it’s worth, this is something that’s pretty easy to accomplish with out of the box Twig —  no pseudo patterns required.

As a practical example, we have a base Share component in Bolt that’s configured with some default data we want to use in all our Pattern Lab demos.

https://github.com/bolt-design-system/bolt/blob/master/apps/pattern-lab/src/_patterns/02-components/share/_share-component-example.twig

Not only does this allow us to easily overwrite or build on top of this component’s data, but it also means that our demos can focus on what’s unique or different to specific use case.

Demo: https://boltdesignsystem.com/pattern-lab/?p=components-share-opacity-variations

Code: https://github.com/bolt-design-system/bolt/blob/master/apps/pattern-lab/src/_patterns/02-components/share/15-share-opacity-variations.twig — note how we’re adding the previously unset `opacity` option here + overriding the default text that shows up.

**Comment by bradfrost** [comment]
Reopening this just to continue to pick at it. @sghoweri thanks so much for the demo and the example. Would love to see how this kind of thing works with Handlebars as well.

**Comment by sghoweri** [comment]
@bradfrost lemme go update those original links... we’ve been doing some major reorganization work with how we manage the workshop vs storefront bits to Bolt so those original examples are 404ing 🙂

**Comment by sghoweri** [comment]
> @bradfrost lemme go update those original links... we’ve been doing some major reorganization work with how we manage the workshop vs storefront bits to Bolt so those original examples are 404ing 🙂

Updated!

**Comment by bradfrost** [comment]
Awesome thanks @sghoweri!
