### ISSUE TITLE
code viewer feature for individual patterns doesn't work ?

### ISSUE THREAD

**Issue by charbz** [pattern-lab/patternlab-node#94]
Node version doesn't generate pattern-name.escaped.html for me , so when I try using the "view code" on individual patterns , I see an HTTP error message ( cannot get ) .. I got fed up with this and wrote a fix to generate the escaped html .. I was wondering if this is an issue everyone else has ? or something i did wrong during the installation ? .. if this is a real bug I can put in a pull request for my fix ! :dart: :smile:

**Comment by bmuenzenmeyer** [comment]
Hi @charbz 

The dev branch is stable https://github.com/pattern-lab/patternlab-node/tree/dev and includes this fix. I am waiting on one more enhancement before releasing to master.

Try this and let me know if this resolves your issue.

**Comment by charbz** [comment]
Hi @bmuenzenmeyer , yes this fix works ! ( its almost the same as my local solution ) 
Thanks for the great library , cant wait for the new release :+1:

**Comment by bmuenzenmeyer** [comment]
Good to hear. Will close this when it reaches master.

**Comment by bmuenzenmeyer** [comment]
This was released to master just a few minutes ago. Thank you so much for the support!!!!!!
