### ISSUE TITLE
Warnings and missing module

### ISSUE THREAD

**Issue by benhalverson** [pattern-lab/patternlab-node#953]
I am using Pattern Lab Node `v3.0.0-beta1` on `Mac`, with Node `v10.9.0`, using a `node-cli` Edition.

##### Expected Behavior
No warnings or missing modules

##### Actual Behavior
```
Pattern Lab Node v3.0.0-beta.1
Pattern Engine mustache: good to go
Pattern Engine react: Cannot find module 'hogan'
Incremental builds enabled.
Built Pattern Lab front end
Please convert /Users/benhalverson/projects/svilab-styleguide/source/_annotations/annotations.js to JSON and rename it annotations.json.
Pattern Lab is watching for changes to files under source/
Pattern Lab is being served from http://127.0.0.1:3000
```

##### Steps to Reproduce
1. Follow the gettings started guide on using https://github.com/pattern-lab/patternlab-node#installation
``` 
mkdir new-project
cd new-project
npm init -y && npx @pattern-lab/cli -c patternlab init
```
If I run 
`npm run pl:serve` I see this message `Please convert /Users/benhalverson/projects/svilab-styleguide/source/_annotations/annotations.js to JSON and rename it annotations.json.`

Followed by 
2. `npm i @pattern-lab/engine-react` to install the react-engine
3. `npm run pl:serve`
I noticed a missing module hogan error.

**Comment by MartinDM** [comment]
I'm having a very similar issue to this, preventing running the front-end...

On cloning the repo, and installing the project via the CLI and selecting the 'node' version with the 'mustache-demo' starter kit, I then run `npm run pl:serve` 

This throws various missing packages as follows, which then exits and doesn't create the local server:

npm WARN @reach/visually-hidden@0.1.4 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/visually-hidden@0.1.4 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN prism-react@1.0.2 requires a peer of react@^15.0.2 || ^0.14.8 but none is installed. You must install peer dependencies yourself.
npm WARN react-animate-height@2.0.8 requires a peer of react@>=15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-animate-height@2.0.8 requires a peer of react-dom@>=15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-autosuggest@9.4.3 requires a peer of react@>=0.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-autowhatever@10.2.0 requires a peer of react@>=0.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-html-parser@2.0.2 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN recompose@0.22.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by JosefBredereck** [comment]
Still relevant?

**Comment by MartinDM** [comment]
Not here. Can be closed @JosefBredereck then if someone else encounters it they can always re-open the issue. Thank you both.
