### ISSUE TITLE
Pattern rendered without parameters

### ISSUE THREAD

**Issue by IcarusImageJu** [pattern-lab/patternlab-node#955]
I am using Pattern Lab Node `see below` on `Windows`, with Node `v10.5.0`, using a `Gulp | Custom` Edition.
"@pattern-lab/cli": "^0.0.1-beta.0",
    "@pattern-lab/core": "^3.0.0-beta.0",
    "@pattern-lab/engine-mustache": "^2.0.0-beta.0",
    "@pattern-lab/starterkit-mustache-demo": "^5.0.0",
    "@pattern-lab/uikit-workshop": "^1.0.0-beta.0",

##### Expected Behavior
I should have my pattern rendered with his parameters

##### Actual Behavior
It render the pattern but without any parameters and throw warning in the console logs.
##### Steps to Reproduce
I try to use a pattern with parameters and the complier tell me 
```
Could not replace offset with 0 inside <div draggable="true" class="graph-task{{#color}} graph-task_color_{{color}}{{/color}}{{#inactive}} graph-task_inactive{{/inactive}}{{#loading}} loading{{/loading}}"
    style="width: calc(3rem * {{length}}); left: calc(3rem * {{offset}})">
    <div class="graph-task__title">Cleaning</div>
    <div class="graph-task__ref">#itdm-2018-12-08</div>
    <div class="graph-task__off" style="width: calc(3rem * {{lengthOff}}); left: calc(3rem * {{offsetOff}} - 2px)"></div>
</div>
Could not replace length with 2 inside <div draggable="true" class="graph-task{{#color}} graph-task_color_{{color}}{{/color}}{{#inactive}} graph-task_inactive{{/inactive}}{{#loading}} loading{{/loading}}"
    style="width: calc(3rem * {{length}}); left: calc(3rem * {{offset}})">
    <div class="graph-task__title">Cleaning</div>
    <div class="graph-task__ref">#itdm-2018-12-08</div>
    <div class="graph-task__off" style="width: calc(3rem * {{lengthOff}}); left: calc(3rem * {{offsetOff}} - 2px)"></div>
</div>
```
when i try to call it like this
02-organisms/04-graph/02-graphContent.mustache
```
...
{{> molecules-graphTask(offset: 0, length: 3, color: "red", offsetOff: 0, lengthOff: 1)}}
{{> molecules-graphTask(offset: 3, length: 4, color: "blue", offsetOff: 3, lengthOff: 1)}}
...
```

And this is the pattern called
01-molecules/08-graph/00-graphTask.mustache
```
<div draggable="true" class="graph-task{{#color}} graph-task_color_{{color}}{{/color}}{{#inactive}} graph-task_inactive{{/inactive}}{{#loading}} loading{{/loading}}"
    style="width: calc(3rem * {{length}}); left: calc(3rem * {{offset}})">
    <div class="graph-task__title">Cleaning</div>
    <div class="graph-task__ref">#itdm-2018-12-08</div>
    <div class="graph-task__off" style="width: calc(3rem * {{lengthOff}}); left: calc(3rem * {{offsetOff}} - 2px)"></div>
</div>
```

**Comment by engelfrost** [comment]
Since I don't know what error messages you're getting this might or might not be helpful, but... 

I've had issus with numeric values (`{"value": 0}`). My issues were solved by using only strings (`{"value": "0"}`). 

(Side note: I just have to comment that the `style` attributes make my skin crawl 😄. I see these in our old production code now and again 😱...)

**Comment by IcarusImageJu** [comment]
Thx for the feedback @engelfrost .
This is the error message =>
`Could not replace offset with 0 inside <div draggable="true" class="graph-task{{#color}} graph-task_color_{{color}}{{/color}}{{#inactive}} graph-task_inactive{{/inactive}}{{#loading}} loading{{/loading}}"
    style="width: calc(3rem * {{length}}); left: calc(3rem * {{offset}})">
    <div class="graph-task__title">Cleaning</div>
    <div class="graph-task__ref">#itdm-2018-12-08</div>
    <div class="graph-task__off" style="width: calc(3rem * {{lengthOff}}); left: calc(3rem * {{offsetOff}} - 2px)"></div>
</div>
Could not replace length with 2 inside <div draggable="true" class="graph-task{{#color}} graph-task_color_{{color}}{{/color}}{{#inactive}} graph-task_inactive{{/inactive}}{{#loading}} loading{{/loading}}"
    style="width: calc(3rem * {{length}}); left: calc(3rem * {{offset}})">
    <div class="graph-task__title">Cleaning</div>
    <div class="graph-task__ref">#itdm-2018-12-08</div>
    <div class="graph-task__off" style="width: calc(3rem * {{lengthOff}}); left: calc(3rem * {{offsetOff}} - 2px)"></div>
</div>`

Okay, only string, no int, and it's working like a charm again. Thank you !!

(Yeah... the style attribute is messy and ugly and need to be replaced by the front developer in JSS with React ;) )

**Comment by ringods** [comment]
Ignore my comment. Just after posting it, I noticed the parameter was replaced only once. This is another reported issue I overlooked: #912

**Comment by mfranzke** [comment]
I am using Pattern Lab Node v5.10.1 on Mac OS, with Node v13.12.0, using @pattern-lab/edition-node Edition. The problem doesn’t occur any more on this setup. Could you please retest ?

I've used those test files, which are slightly modified to the orginal ones due to the migration from `mustache` to `hbs`:

`02-organisms/04-graph/02-graphContent.hbs`:
```hbs
{{> molecules-graphTask offset=0 length=3 color="red" offsetOff=0 lengthOff=1 }}
{{> molecules-graphTask offset=3 length=4 color="blue" offsetOff=3 lengthOff=1 }}
```
`01-molecules/08-graph/00-graphTask.hbs`:
```hbs
<div draggable="true" class="graph-task{{#if color}} graph-task_color_{{color}}{{/if}}{{#inactive}} graph-task_inactive{{/inactive}}{{#loading}} loading{{/loading}}"
    style="width: calc(3rem * {{length}}); left: calc(3rem * {{offset}})">
    <div class="graph-task__title">Cleaning</div>
    <div class="graph-task__ref">#itdm-2018-12-08</div>
    <div class="graph-task__off" style="width: calc(3rem * {{lengthOff}}); left: calc(3rem * {{offsetOff}} - 2px)"></div>
</div>
```
