### ISSUE TITLE
"Error processing meta patterns" / "TypeError: Cannot read property 'patternState' of undefined"

### ISSUE THREAD

**Issue by machal** [pattern-lab/patternlab-node#956]
I am using Pattern Lab Node `3.0.0-beta.1` on `Mac`, with Node `v10.2.0`, using a `Vanilla` Edition.

##### Expected Behavior

Build the Pattern Lab.

##### Actual Behavior

Pattern Lab UI is empty.

Error in the CLI:

```bash
$ npm run pl:build

> vzhuru-dolu@0.7.0 pl:build /Users/machal/Sites/vd-web/www
> patternlab build --config ./patternlab-config.json

Pattern Lab Node v3.0.0-beta.1
Pattern Engine mustache: good to go
Incremental builds enabled.
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-appearance-free from <<blank>>
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-full from <<blank>>
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-inverted from <<blank>>
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-narrower from <<blank>>
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-primary from <<blank>>
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-stronger from <<blank>>
Found a lower common denominator pattern state: needsreview on modules-button. Setting reverse lineage pattern modules-button-wide from <<blank>>
TypeError: Cannot read property 'patternState' of undefined
    at cascadePatternStates (/Users/machal/Sites/vd-web/www/node_modules/@pattern-lab/core/src/lib/lineage_hunter.js:124:31)
    at Object.cascade_pattern_states (/Users/machal/Sites/vd-web/www/node_modules/@pattern-lab/core/src/lib/lineage_hunter.js:172:7)
    at Promise.all.then (/Users/machal/Sites/vd-web/www/node_modules/@pattern-lab/core/src/lib/buildPatterns.js:101:32)
Error processing meta patterns
Built Pattern Lab front end
⊙ patternlab → build: Yay, your Pattern Lab project was successfully built ☺
```

##### Steps to Reproduce

```
$ npm run pl:build
```

+ contents of my `/source` : https://www.dropbox.com/s/07iqr7j67imhtqj/patternlab-source.zip?dl=0

**Comment by machal** [comment]
I had given a try to this and the problem disappeared when I removed `state:` from `.md` files.

For example - before:

```
---
title: Button
state: needsreview
---
```

For example - after:

```
---
title: Button
---
```

**Comment by Seanom** [comment]
Weirdly after going through and removing the state as mentioned above the error went, but then as I added them back in one by one the error did not come back.

I've recently set my repo on a new machine, I've had no previous issues with that repo. 
I'm also only using the default states, `inprogress` and `complete`

Once I got rid of the error message, I've been unable to get it to appear again

**Comment by dnwhte** [comment]
I am also having this issue with 3.0.1-alpha.0.

**Comment by dnwhte** [comment]
This issue seems to occur when renaming, moving, or adding a file when serving with cleanPublic = false. Doing a build with cleanPublic = true temporarily resolves the issue.

**Comment by markprins** [comment]
I encounter this bug from time to time too. Seems to happen, as said in previous comments, when moving files around, or renaming patterns. It also results in that  the specific pattern which triggers the fault will not work as long as the issue exists. 

cleanPublic is set to True. It seems that removing  the dependencyGraph.json _as well as_ cleaning up the public folder seemed to do the trick.

Will continue to monitor if it happens again and try to reproduce it or debug any further.
