### ISSUE TITLE
No file watcher & browser refresh in `patternlab:serve` gulp task.

### ISSUE THREAD

**Issue by ringods** [pattern-lab/patternlab-node#957]
I am using Pattern Lab Node `v3.0.0-beta-1` on `Mac`, with Node `v8.12.0`, using a `Gulp` Edition (tested with Gulp v3.9.1 and v4.0.0). 

##### Expected Behavior
When running `gulp patternlab:serve`, I want the local server to start and the file watcher to pick up changes with the cycle ending in a browser refresh.

##### Actual Behavior
The local server is started, but any change to my patterns is not picked up and there is no browser refresh. A manual refresh doesn't make a difference.

##### Steps to Reproduce
Create a new project and install PL 3.0.0-beta-1 with `edition-node-gulp` (on gulp 3.9.1). Just use the generated `gulpfile.js` with task `patternlab:serve`.

**Comment by mrkmiller** [comment]
I can confirm that I had the same issue.

**Comment by PhilipRowe** [comment]
I had the same issue as well! I managed to fix this by updating the serve function in the gulpfile.js to:

```
function serve() {
    return patternlab.server
        .serve({
            cleanPublic: config.cleanPublic,
            watch: true
        })
        .then(() => {
            // do something else when this promise resolves
        });
}
```

Adding the `watch: true` is the important part!

**Comment by martymcflysenior** [comment]
I'm seeing the same issue while using edition-twig (php engine) and starterkit-twig-demo. I'm using Pattern Lab Node v3.0.1. Any workarounds available without gulp?
