### ISSUE TITLE
How to write my own handlebars helper and use it in patternlab-node?

### ISSUE THREAD

**Issue by Miw0** [pattern-lab/patternlab-node#958]
I am using Pattern Lab Node `v2.12.0` on `Windows`, with Node `v8.11.1`, using a `Gulp` Edition.

I am very confused how to actually write my own handlebars helper and use it in patternlab-node. I read there are patternlab plugins but is this the correct way to load a handlebars helper?

I hope someone can point me in the right direction. I also didn't find any information about plugins or whatsoever on the official documentation page.

Thanks in advance.

**Comment by Miw0** [comment]
So I tried writing my own plugin and use it via `npm link`. Pattern Lab says it has been installed correctly but it doesn't seem to be executed when building. Thanks to poor documentation I am really lost. Has anyone been able to write a working plugin and could help me out?

**Comment by engelfrost** [comment]
Got something working, submitting PR soon

**Comment by Miw0** [comment]
@engelfrost really nice! Thank you! In the meanwhile I published a Pattern Lab plugin to resolve my usecase. If anyone is interested, feel free to use https://www.npmjs.com/package/plugin-node-patternlab-inline-assets

**Comment by engelfrost** [comment]
@Miw0 Cool, you figured the plugin thing out! I might combine our two solutions to make a helper-loading plugin.

**Comment by david-moldenhauer** [comment]
@Miw0 @engelfrost 
Adding a Handlebars helper is done via the plugin setting inside the patternlab-config.json:
"plugins": {
    "plugin-node-handlebars-helpers": {
      "enabled": true,
      "more_options": "options1"
    }
  }
the key "plugin-node-handlebars-helpers" is the npm modules name you can check https://github.com/david-moldenhauer/plugin-node-handlebars-helpers for more details.

**Comment by engelfrost** [comment]
Thanks @david-moldenhauer. A common way to add helpers/extensions to both Handlebars and Nunjucks is making it's way into the engines themselves now. If you have knowledge to add to the PR linked above based on your plugin that would be great!

**Comment by Miw0** [comment]
> 
> 
> @Miw0 @engelfrost
> Adding a Handlebars helper is done via the plugin setting inside the patternlab-config.json:
> "plugins": {
> "plugin-node-handlebars-helpers": {
> "enabled": true,
> "more_options": "options1"
> }
> }
> the key "plugin-node-handlebars-helpers" is the npm modules name you can check https://github.com/david-moldenhauer/plugin-node-handlebars-helpers for more details.

I first thought you build a plugin which would allow me to add any handlebars helper I need but I see that your plugin ist just a collection of useful util helpers. Anyway thanks for posting, this would have helped me alot 2 weeks ago!

**Comment by engelfrost** [comment]
Still relevant, waiting for PR to be processed

**Comment by engelfrost** [comment]
Still relevant

**Comment by engelfrost** [comment]
For anyone else who is impatient and needs this in PL v2 I've created this Handlebars Engine for myself. The project will not be maintained in the long run: https://github.com/engelfrost/patternengine-node-handlebars-extended

**Comment by engelfrost** [comment]
PR still waiting to be processed
