### ISSUE TITLE
Set Up Now.sh Deploys + Travis Integration for Pattern Lab Node Repo

### ISSUE THREAD

**Issue by sghoweri** [pattern-lab/patternlab-node#961]
@bmuenzenmeyer I think we should move forward with setting up now.sh + Travis integration with the Pattern Lab Node repo -- basically having any passing Travis build automatically deploy a staged preview (of some generated starterkits?...) for testing, always up to date docs and demos, etc.

We're already doing something [very similar](https://github.com/bolt-design-system/bolt/pull/900#issuecomment-427537728) with every PR and release in the Bolt Design System repo (including Github integration) so we have an easy to get to link we can share and reference for any upcoming changes upstream. As a bonus, this integration can also get used to deploy demos and docs to a live site / domain if configured with every new release.

I've already gone ahead and created a free OSS team for Pattern Lab -- identifying what makes the most sense to deploy + getting this integrated with the Github repo would probably be the next step...

**Comment by bradfrost** [comment]
I'd welcome a nice visual/working preview of what the latest PL build looks like.

**Comment by sghoweri** [comment]
Bump! Still relevant + still needed . Don't want to see this closed out prematurely :)

**Comment by sghoweri** [comment]
Bump
