### ISSUE TITLE
Probably superfluous dependencies in uikit-workshop

### ISSUE THREAD

**Issue by c1rrus** [pattern-lab/patternlab-node#964]
I am using Pattern Lab Node core `v3.0.0-beta.1` & uikit-workshop `v1.0.0-beta.0` on `Linux`, with Node `v8.12.0`, using a `Custom Gulp` Edition.

##### Expected Behavior
When I `npm install @pattern-lab/uikit-workshop` as a dependency in my project, it should only install its own dependencies that it needs at runtime, not things used for its development.

##### Actual Behavior
I noticed [PhantomJS](http://phantomjs.org/) being downloaded during my project's `npm install` setup. It's not something I'm using myself and, considering it's a relatively hefty download (~22mb). That feels like it should be a _dev_ dependency (as in, needed if you're contributing to `uikit-workshop` itself), but not a normal dependency that consumers would need.

##### Steps to Reproduce
- Make an empty directory
- `npm init -y` (to make a dummy `package.json`)
- `npm install @pattern-lab/uikit-workshop`

If you now look in `node_modules`, you'll see _a lot_ of packages there - including `phantomjs-prebuilt`. Considering the the UI Kit is just meant to be pre-compiled HTML, CSS & JS assets that get copied / served up by Pattern Lab, I'm surprised there are _any_ dependencies at all TBH.

##### Notes & suggested fix
I did a little digging and it's actually `jshint` that's at fault. Its current version (2.9.6) has a bug (which [they have already fixed](https://github.com/jshint/jshint/commit/f70250bf584a3661ecddbbc23f83173a7b09c248) and, I assume, will be fixed in a future release). _However_ considering that it's a linting tool I wouldn't expect `uikit-workshop` to list it as one of its non-dev dependencies.

If, in your `package.json` you move `jshint` to the `devDependencies`, then consumers like me will no longer install it and, by extension, also install PhantomJS. Only developers working directly on `uikit-workshop` would.

Looking at your `package.json`, I also noticed that`jshint` is additionally listed as a peer dependency? Is this intentional?

**Comment by bmuenzenmeyer** [comment]
Good sluething.  :male_detective: 

@sghoweri are we using jshint in your new ui or is it a holdover?

**Comment by sghoweri** [comment]
@bmuenzenmeyer nope, I typically use Prettier + Eslint so that dependency is definitely a holdover from the original front-end build. Nix it?

**Comment by bmuenzenmeyer** [comment]
@c1rrus Nix it

💀 ⚰️ 🥀 🌅
