### ISSUE TITLE
boolean converted to string

### ISSUE THREAD

**Issue by rosea1** [pattern-lab/patternlab-node#971]
I am using Pattern Lab Node `v2.0.0` on `Mac`, with Node `v8.10.0`, using a `Gulp` Edition.

#Expected Behavior

When passing pattern parameters to instantiate a pattern, and using the current patterns data as the attributes, i would expect a value of false passed to the instantiated pattern to be of type boolean and not string.

##### Actual Behavior

When using this data, false, seems to be converted to a string.

##### Steps to Reproduce

# Below is my mustache file for the molecule "accordion"

accordion.mustache file
```html
<div class="o-accordion" aria-expanded="{{isOpen}}" aria-controls="{{ id }}">
  {{^ iconRight }}
    <span class="inverted {{# isOpen }}expanded{{/ isOpen }}"
    data-icon="expand"></span>
  {{/ iconRight }}
  <h3 class="o-accordion_title">{{ placeholder }}</h3>
  {{# iconRight }}
    <span class="inverted {{# isOpen }}expanded{{/ isOpen }}"
    data-icon="expand"></span>
  {{/ iconRight }}   
</div>
```

In a page i am looping through local data and trying to instantiate the accordion molecule using a flag in the local data isOpen: true|false;

```json
{
  "regions": [
    {
      "region":"Americas",
      "isOpen": false,
      "id": "americas",
      "countries":[
        {
          "countryName": "United States",
          "icon": "usa"
        },
        {
          "countryName": "Canada",
          "icon": "canada"
        }
      ]
    },
    {
      "region":"Asia - Pacific",
      "isOpen": true,
      "id": "asiapac",
      "countries": [
        {
          "countryName": "Australia",
          "icon": "australia"
        },
        {
          "countryName": "Hong Kong",
          "icon": "hong-kong"
        },
        {
          "countryName": "Japan",
          "icon": "japan"
        },
        {
          "countryName": "China",
          "icon": "china"
        },
        {
          "countryName": "India",
          "icon": "india"
        },
        {
          "countryName": "Taiwan",
          "icon": "taiwan"
        }
      ]
    },
    {
      "region":"EMEA",
      "isOpen": false,
      "id": "emea",
      "subRegions": [
        {
          "subRegion": "Europe",
          "countries": [
            {
              "countryName": "Austria",
              "icon": "austria"
            },
            {
              "countryName": "Guernsey",
              "icon": "guernsey"
            }
          ]          
        },
        {
          "subRegion": "Middle East",
          "countries": [
            {
              "countryName": "Dubai UAE",
              "icon": "dubai"
            }
          ]
        }
      ]
    }
  ]
}
```

when using the accordion pattern like below;

```
  {{> molecules-accordion(placeholder:"{{region}}", iconRight: true, isOpen:"{{isOpen}}", showContent: false, id:"{{ id }}")}}
```
the boolean isOpen is being converted to a string, im guessing by the speech marks, however without the speech marks, patternLab throws and error.

**Comment by engelfrost** [comment]
My understanding has been that the Mustache engine does not supports this:

> Pattern parameters do not currently support [...] modifying/replacing variables in patterns included within the targeted pattern

...which I interpret as: The pattern containing the accordion pattern cannot pass data to the accordion pattern. This is one of the main reasons I've switched to the Handlebars engine. 

On the other hand, it sounds like `"{{region}}"` _is_ working for you? So I may be wrong.

**Comment by bradfrost** [comment]
Hey @rosea1,
Thanks for this issue. 

Alas, pattern parameters aren't standard Mustache, which is why they're on the road to be deprecated. Other templating engines like Handlebars (as @engelfrost pointed out) can handle these situations more elegantly. 

In the meantime, I'd suggest avoiding using pattern parameters in favor of using JSON across the board. In my own workflow, we tend to wrap specific instances of a pattern in some Mustache code that allows us to target it:

```
{{#regionAccordion}}
{{> molecules-accordion}}
{{/regionAccordion}}
```

We can then write data that looks like:

```
"regionAccordion" : {
   "placeholder": "region", 
    "iconRight": true, 
    "isOpen": true, 
     "showContent": false, 
     "id": "id"
}
```

Not sure exactly what structure you're going for, but hopefully that gives you an idea.
