### ISSUE TITLE
Missing essential file

### ISSUE THREAD

**Issue by thany** [pattern-lab/patternlab-node#972]
I'm trying to upgrade from PL 1.2 to 2.12. I got it installed, and now following the [upgrade steps](https://patternlab.io/docs/upgrading.html). But what does it mean to copy from `source/*` to `source/`? How is that useful? The way I read this, is to copy every file in the source directory, to the source directory. So, they are already there. What should I actually do? I'll skip this step for now.

Now when I try to start my project, it's throwing a weird error about a missing essential file in patternlab itself (not in my project)... It's almost as if the 2.12 release is incomplete?...

I am using Pattern Lab Node `v2.12` on `Windows`, with Node `v10.13`, using a `Gulp` (I think) Edition.

##### Expected Behavior

Just works, I guess?

##### Actual Behavior

When starting PL:
```
ERROR: missing an essential file from ./node_modules/patternlab-node/core/. Pattern Lab won't work without this file.
```

##### Steps to Reproduce

I'm not sure. I didn't set up this project initially, I'm just trying to upgrade it. And I'm not very experienced with PL specifically. So please go easy on me :)
It's been set up with Node 4.5 and PL 1.2, and I'm just trying to follow the upgrade path for 2.x.

**Comment by thany** [comment]
Update.

So my log says something about a missing files `node_modules\\patternlab-node\\core\\partials\\general-header.mustache`. But there's also a config option in my `config.json` in `paths.source.patternLabFiles` that is set to `"./node_modules/patternlab-node/core/"`. As you know, that directory exists, but doesn't container the general-header file.

So digging into the [configuration options](https://patternlab.io/docs/advanced-config-options.html). First of all, why is there *nothing* on what all those paths are?! Secondly, I tried to replace the `patternlabFiles` value with the default that's written down there. I then get a different error upon starting PL:

```
ERROR: missing an essential file from [object Object]. Pattern Lab won't work without this file.
```
Lolwut? It doesn't understand its very own default values? Okay then :(
Let's remove `patternlabFiles` from my config and let PL figure out its internal default, I was hoping. So now when I start PL, I get a different error again:
```
ERROR: missing an essential file from undefined. Pattern Lab won't work without this file.
```
So there is no such thing as a default! This `patternlabFiles` key is **required**, it seems. Why is that not in the documentation?

What I did next, was to create the files as in the documentation. So I created:
* `views/partials/general-header.mustache`
* `views/partials/general-footer.mustache`
* `views/partials/patternSection.mustache`
* `views/partials/patternSectionSubtype.mustache`
* `views/viewall.mustache`
And pointed `patternlabFiles` to a **string** as it appears to demand for: `"./public/views"`
Now I get a totally different error.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at processHeadPattern (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\patternlab-node\core\lib\patternlab.js:303:122)
    at buildPatterns (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\patternlab-node\core\lib\patternlab.js:556:5)
    at Object.build (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\patternlab-node\core\lib\patternlab.js:622:7)
    at Gulp.<anonymous> (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\gulpfile.js:372:6)
    at module.exports (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (c:\workspaces\Chocolate\ibn\Sources\IBN.Web.UI\static\node_modules\orchestrator\index.js:134:8)
```
Okay. What path does it want this time?
Mind you, those mustache files I created, are **empty**. There is (again) no documentation, it seems, as to what should be in them. Or where to get pre-existing ones.

**Comment by engelfrost** [comment]
Hi @thany, I am not an expert at the PL source code, and I have never even used v1. But I have a clue why the upgrade is not working:

> I'm trying to upgrade from PL 1.2 to 2.12. I got it installed, and now following the upgrade steps. But what does it mean to copy from source/* to source/? How is that useful?

It sounds like you don't have a clean installation of 2.12. You need to follow step 1 as instructed in the instructions, i.e. make a new, clean installation of 2.x. In step two, you move your sources (from e.g. `pattern-lab/sources/*` to `pattern-lab-v2/sources`, or whatever your v1 and v2 directories are called). You will need to follow through with all the steps (1-5) before you can run 2.x successfully.

**Comment by thany** [comment]
Well, I'm off the project anyway, and I wasn't going to give myself more than two hours to get this update going. Any more than that wouldn't be worth the time.

If I remember, I definitely went through all the steps word-for-word. But mind you, this is an old installation, it wasn't set up by me, and I had zero knowledge of PL when I started working with it 4 weeks earlier. I just used it the way it was set up, and kind of assumed it was set up the right way (if there's such a thing).

Anyway, to me this is another nail in the coffin for major upgrades. It is *always* better to provide smaller incremental upgrades, instead of a giant leap. You can see how it keeps people of moving along to the new version. And at the same time, I can imagine for the PL devs it is demotivating to keep maintaining the 1.x codebase.
