### ISSUE TITLE
 Inconsistencies building Pseudo Patterns in PL3 with the Handlebars engine

### ISSUE THREAD

**Issue by engelfrost** [pattern-lab/patternlab-node#974]
I am using Pattern Lab Node `v3.0.0-beta.1` on `Mac`, with Node `v10.11.0`, using a `Custom` Edition.

I am using the Handlebars engine. 

##### Expected Behavior

All pseudo patterns are built

##### Actual Behavior

Pseudo patterns are not built initially. After a few saves, they are. 

##### Steps to Reproduce

1. Start Pattern Lab 3. Pseudo patterns are missing the the browser UI. 
2. Save files
3. Reload browser UI
4. Repeat steps 2 and 3 until pseudo pattern appear in the browser UI

**Comment by bradfrost** [comment]
Hey @engelfrost, are you able to provide an example of pseudo-patterns that aren't being built?

**Comment by engelfrost** [comment]
Sure. here is a gist of tabs (from `02-atoms/50-tabs/`) https://gist.github.com/engelfrost/05a5bf51616e125ad6a37fb05fa4acdd

If I save `10-tabs~many.json` (no changes made) the pattern is built.

**Comment by engelfrost** [comment]
Solved in #978
