### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by MuTLY** [pattern-lab/patternlab-node#976]
I am using Pattern Lab Node `v3.0.0.-beta.1` on `Windows`, with Node `v8.10.0`, using a `Gulp` Edition.

##### Expected Behavior
To Pattern Lab build correctly

##### Actual Behavior
I'm getting lots of messages like the one below:

`RangeError: Invalid string length
    at String.replace (<anonymous>)
    at previousPromise.then (C:\Users\lrbarbosa\www\trs-legacy-pl-nodejs\node_modules\@pattern-lab\core\src\lib\parameter_hunter.js:326:65)
    at <anonymous>
RangeError: Invalid string length`

`RangeError: Invalid string length
    at String.replace (<anonymous>)
    at previousPromise.then (C:\Users\lrbarbosa\www\trs-legacy-pl-nodejs\node_modules\@pattern-lab\core\src\lib\parameter_hunter.js:326:65)
    at <anonymous>
RangeError: Invalid string length`

The problem is, how can I pinpoint the invalid strings?

##### Steps to Reproduce
None specific, though I am using my old PHP "source" version of Pattern Lab. I had to change a few keys here and there that were using dashes to NOT use them, as mentioned in another issue here. That fixed the "Invalid regular expression" syntax error message I was also getting, but now I'm stuck on this one.

**Comment by MuTLY** [comment]
I was doing some research and found a pattern when using the query `pattern lab node "invalid string"` on search engines. It appears the issue is with the VM, not PL Node or Node. Basically the VM (V8 engine) is running out of memory and throwing this misleading error message on screen.

Based on this find, I'm at a lost on how to fix my PL Node instance. Note that the same `source` directory I'm trying to build with Node worked fine on the PHP version.

**Comment by engelfrost** [comment]
This is a guess, but could you be using numbers as data? In that case, try replacing them with strings (e.g. `4` - > `"4"`).

**Comment by MuTLY** [comment]
@engelfrost yes, I do have huge JSON files and so far I think that's the issue. As for numbers as data, that could be something, yes. I don't recall patterns being recursively included in each other. I'll dig deeper and try to find out. Thanks for the tips!

**Comment by engelfrost** [comment]
I have not looked deep enough into the source to tell if the Mustache or JSON files might cause this. But according to [big-json](https://www.npmjs.com/package/big-json) the maximum size for JSON.stringify is 512MB. According to [this source](https://github.com/nodejs/node/pull/10687) maximum size is ~256MB. 

In any case, the line that the error message points to is here: [parameter_hunter.js line L326](https://github.com/pattern-lab/patternlab-node/blob/dev/packages/core/src/lib/parameter_hunter.js#L326). Judging from variable names and [this comment](https://github.com/pattern-lab/patternlab-node/blob/dev/packages/core/src/lib/parameter_hunter.js#L248) it looks like the error occurs when trying to generate what I assume is the final HTML. I.e. neither the individual JSON files or Mustache files are too large themselves, but the result is.
