### ISSUE TITLE
Epic: Roadmap To v3.0

### ISSUE THREAD

**Issue by sghoweri** [pattern-lab/patternlab-node#983]
Sketching out the work I think is remaining till we can release the next beta version of PL Node + big ticket items left for the full v3.0 release.

Please let me know if I'm missing anything or got anything wrong here!

# Goals
1. ## Stability 
    - ie. the Pattern Lab Node v2.0 to v3.0 refactor work
2. ## Interoperability 
    - Move to monorepo ([DONE!](https://github.com/pattern-lab/patternlab-node/pull/806))
      - Publish monorepo pieces independently (ie release updates as they are ready to go?)
    - [Unify the Pattern Lab Ecosystems](https://github.com/pattern-lab/the-spec/issues/37) (ie. native PHP-based Twig support)
3. ## Flexibility / Customization 
    - [UIKit refactor](https://github.com/pattern-lab/patternlab-node/issues/909)
    - Customizations (light / dark mode, logo support, support for 3rd party UI add-ons, etc)
4. ## Maintainability
    - Automate release process
    - Docs & Demos
    - Automate Now.sh deployment of docs / demos
    - Pattern Lab as a platform vs PL as a monolith
5. ## [Platform Prep](https://github.com/pattern-lab/patternlab-node/issues/834)
    - Consumable, extendable, and interoperable design systems / pattern libraries

<hr>

## Work Remaining For Next Beta
- Merge in any open PRs that are good to go? Merge in current UIKit PRs?
- Confirm publishing / release process?
- Publish next release to NPM

## Work Remaining For v3.0 Release
- Markdown / Viewall path bugs
    - https://github.com/pattern-lab/patternlab-node/issues/970
- Docs
- Finish Twig Renderer integration
- Clean up, PR remaining UIKit refactor / rebuild updates 
    - CSS Vars for theming

**Comment by sghoweri** [comment]
Bump! Still open + still in progress. 🙂

**Comment by aleksip** [comment]
I would consider a working plugin system a must-have. Seems to me the plugin system is broken at the moment? The plugin system might also need some rearchitecting. Currently PL seems to assume that every package beginning with `plugin-` is a PL plugin. This means that it finds and tries to install Babel plugins, for example.

**Comment by sghoweri** [comment]
Bump

**Comment by sghoweri** [comment]
*fist bump*

**Comment by bmuenzenmeyer** [comment]
btw - 3.0 was accidentally released a while ago, see #1039 so not sure how much of this still applies

**Comment by ringods** [comment]
Can we close this issue in favor of more recent issues and the [core 2](https://github.com/pattern-lab/patternlab-node/projects/5) project board?

**Comment by bmuenzenmeyer** [comment]
i'm in favor. @sghoweri if you agree please close.

**Comment by sghoweri** [comment]
Closing out -- I'll open standalone tickets if there's anything worth keeping around (and still relevant) from this
