### ISSUE TITLE
Plugin minify html

### ISSUE THREAD

**Issue by JosefBredereck** [pattern-lab/patternlab-node#986]
Hello, I wanted to submit my plugin to [this page](https://github.com/pattern-lab/patternlab-node/wiki/Official-&-Community-Plugins).

The Plugin is called [plugin-node-minify-html](https://github.com/SlimeGames/plugin-node-minify-html) and its provided by me [@JosefBredereck](https://github.com/JosefBredereck)

**Comment by sghoweri** [comment]
Bump - want to make sure this isn't auto-closed.

**Comment by svalchinov** [comment]
Can this be look at please? This is a really useful plugin to have available

**Comment by bmuenzenmeyer** [comment]
sorry - this closed during my hiatus - will take a look!

**Comment by JosefBredereck** [comment]
Because it's just for formatting and a notice on another info page, I don't think it should be on the priority list. Also it maybe won't work with version 3 of Patternlab.

**Comment by bmuenzenmeyer** [comment]
> it maybe won't work with version 3 of Patternlab

yeah it may work by accident (wins the race condition), but we've moved from events to function hooks. ideally this implementation changes to look more like [plugin-tab](https://github.com/pattern-lab/patternlab-node/blob/dev/packages/plugin-tab/index.js#L50-L52)

**Comment by JosefBredereck** [comment]
If I find the time I will acquire the new way of handling plugins. Is there anything in the pipeline to change plugin loading or will it be consistent until V4 of PL?

**Comment by mfranzke** [comment]
@JosefBredereck I've included it in the listing on https://patternlab.io/docs/overview-of-pattern-lab's-ecosystem/#heading-plugins via pull request https://github.com/pattern-lab/patternlab-node/pull/1229
