### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by JoseTobias** [pattern-lab/patternlab-node#991]
I want to install the Pattern Lab 3.0.0.

##### Actual Behavior
Wrote to /home/tobias/Documentos/new-project/package.json:

`{
  "name": "new-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}`

`Unknown command line option: '-c'`
##### Steps to Reproduce
`mkdir new-project`
`cd new-project`
`npm init -y && npx @pattern-lab/cli -c patternlab init`

**Comment by karlschwaier** [comment]
Can't confirm that. It works on my machine (macOS 10.14.3, Node 10.15.1, npm 6.4.1).

**Comment by timcase** [comment]
I confirm exact same error above (Ubuntu 18.04, Node 10.15.1, npm 6.7.0)

**Comment by timcase** [comment]
I was able to get started based by following [the cli readme](https://github.com/pattern-lab/patternlab-node/tree/dev/packages/cli)

1. yarn add @pattern-lab/cli --dev
2. Edit package json
`"scripts": {
+ "patternlab": "patternlab"
},`
3. yarn run patternlab init
